## csv mean and std columns

In [42]:
import os
import cv2
import numpy as np
import pandas as pd

# Path to your folder
folder_path = r"D:\Aamir Gulzar\KSA_project2\Cancer-detection-classifier\Data_cleaning\PAIP_Data\Data"

# Initialize a list to hold data
data = []

# Iterate over all PNG files in the folder
for filename in os.listdir(folder_path):
    if filename.lower().endswith('.png'):
        filepath = os.path.join(folder_path, filename)
        
        # Read the image using OpenCV (in BGR format)
        image = cv2.imread(filepath)

        # Convert BGR to RGB
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Compute mean and std for each channel
        mean_r = np.mean(image_rgb[:, :, 0])
        mean_g = np.mean(image_rgb[:, :, 1])
        mean_b = np.mean(image_rgb[:, :, 2])
        std_r = np.std(image_rgb[:, :, 0])
        std_g = np.std(image_rgb[:, :, 1])
        std_b = np.std(image_rgb[:, :, 2])

        # Append to data list
        data.append({
            'patch_name': filename,
            'avg_R': mean_r,
            'avg_G': mean_g,
            'avg_B': mean_b,
            'std_R': std_r,
            'std_G': std_g,
            'std_B': std_b
        })

In [43]:
# Convert to DataFrame
df = pd.DataFrame(data)
df

,patch_name,avg_R,avg_G,avg_B,std_R,std_G,std_B
0,training_data_01_MSIH_x10240_y44776_patch00004...,183.149101,183.474407,184.250198,83.451217,83.230796,82.259939
1,training_data_01_MSIH_x10752_y3584_371.png,240.879059,239.467487,240.458199,10.397361,13.249032,10.329091
2,training_data_01_MSIH_x10752_y44776_patch00005...,182.929478,183.387585,184.036774,83.621275,83.374348,82.451683
3,training_data_01_MSIH_x10752_y9728_383.png,240.064068,238.309559,239.749710,11.637525,16.017374,12.107118
4,training_data_01_MSIH_x11264_y44776_patch00006...,182.834038,183.182899,183.912064,83.538197,83.349010,82.447273
...,...,...,...,...,...,...,...
6255,validation_data_30_nonMSIH_x512_y20480_8.png,221.379074,221.618031,221.901096,48.592815,48.699569,48.147749
6256,validation_data_30_nonMSIH_x5632_y1536_267.png,240.858345,241.378269,240.865139,9.029050,9.042939,8.667227
6257,validation_data_30_nonMSIH_x5632_y2048_268.png,241.475258,241.950039,241.526363,7.461050,7.407659,7.041214
6258,validation_data_30_nonMSIH_x6144_y0_302.png,242.436016,242.636345,242.419090,5.349561,5.504399,5.334903
6259,validation_data_30_nonMSIH_x6656_y6656_337.png,242.075901,241.654575,242.108212,5.472132,7.229547,5.558484

## setting label column

In [44]:
df['label']=0

In [45]:
import os
import pandas as pd

# Read all PNG filenames from label1 directory
label1_dir = r"D:\Aamir Gulzar\KSA_project2\Cancer-detection-classifier\Data_cleaning\PAIP_Data\Label1"
png_files = [f for f in os.listdir(label1_dir) if f.endswith('.png')]

# Set label = 1 for matching rows
df.loc[df['patch_name'].isin(png_files), 'label'] = 1

# Optional: save to file
# df.to_csv("updated_dataframe.csv", index=False)

print("Labels updated where PatchName matches PNG filenames.")

Labels updated where PatchName matches PNG filenames.

In [46]:
df

,patch_name,avg_R,avg_G,avg_B,std_R,std_G,std_B,label
0,training_data_01_MSIH_x10240_y44776_patch00004...,183.149101,183.474407,184.250198,83.451217,83.230796,82.259939,1
1,training_data_01_MSIH_x10752_y3584_371.png,240.879059,239.467487,240.458199,10.397361,13.249032,10.329091,0
2,training_data_01_MSIH_x10752_y44776_patch00005...,182.929478,183.387585,184.036774,83.621275,83.374348,82.451683,1
3,training_data_01_MSIH_x10752_y9728_383.png,240.064068,238.309559,239.749710,11.637525,16.017374,12.107118,0
4,training_data_01_MSIH_x11264_y44776_patch00006...,182.834038,183.182899,183.912064,83.538197,83.349010,82.447273,1
...,...,...,...,...,...,...,...,...
6255,validation_data_30_nonMSIH_x512_y20480_8.png,221.379074,221.618031,221.901096,48.592815,48.699569,48.147749,1
6256,validation_data_30_nonMSIH_x5632_y1536_267.png,240.858345,241.378269,240.865139,9.029050,9.042939,8.667227,1
6257,validation_data_30_nonMSIH_x5632_y2048_268.png,241.475258,241.950039,241.526363,7.461050,7.407659,7.041214,1
6258,validation_data_30_nonMSIH_x6144_y0_302.png,242.436016,242.636345,242.419090,5.349561,5.504399,5.334903,1
6259,validation_data_30_nonMSIH_x6656_y6656_337.png,242.075901,241.654575,242.108212,5.472132,7.229547,5.558484,0

In [47]:
len(df[df["label"]==1])

459

In [48]:
import pandas as pd
import os

# Base folder where all subfolders like training_data_07_nonMSIH exist
base_patch_dir = r"D:\Aamir Gulzar\dataset\paip_data\Patches"

# Function to build full patch path
def get_patch_location(patch_name):
    # Extract subfolder name from patch_name (first 4 parts before x/y/number)
    subfolder = '_'.join(patch_name.split('_')[:4])
    return os.path.join(base_patch_dir, subfolder, patch_name)

# Apply function to create patch_location column
df['patch_location'] = df['patch_name'].apply(get_patch_location)

# Optional: Save updated CSV (overwrite or create new)
df.to_csv('D:\Aamir Gulzar\KSA_project2\Cancer-detection-classifier\Data_cleaning\PAIP_SVM\patch_statistics.csv', index=False)

print("✅ 'patch_location' column added successfully.")

✅ 'patch_location' column added successfully.

In [32]:
# # Save to CSV
# df.to_csv('D:\Aamir Gulzar\KSA_project2\Cancer-detection-classifier\Data_cleaning\PAIP_SVM\patch_statistics.csv', index=False)

# print("CSV file 'patch_statistics.csv' has been created.")

In [41]:
df

,patch_name,avg_R,avg_G,avg_B,std_R,std_G,std_B,label,patch_location
0,training_data_01_MSIH_x10752_y3584_371.png,240.879059,239.467487,240.458199,10.397361,13.249032,10.329091,0,D:\Aamir Gulzar\dataset\paip_data\Patches\trai...
1,training_data_01_MSIH_x10752_y9728_383.png,240.064068,238.309559,239.749710,11.637525,16.017374,12.107118,0,D:\Aamir Gulzar\dataset\paip_data\Patches\trai...
2,training_data_01_MSIH_x11264_y8704_402.png,234.955982,231.094498,235.116627,21.560986,26.894151,19.305873,0,D:\Aamir Gulzar\dataset\paip_data\Patches\trai...
3,training_data_01_MSIH_x11776_y1536_408.png,240.368797,238.403931,239.894207,10.079387,13.925330,10.327174,0,D:\Aamir Gulzar\dataset\paip_data\Patches\trai...
4,training_data_01_MSIH_x11776_y5632_416.png,207.794716,202.451710,218.244450,51.556892,55.060034,36.053356,0,D:\Aamir Gulzar\dataset\paip_data\Patches\trai...
...,...,...,...,...,...,...,...,...,...
6120,validation_data_30_nonMSIH_x512_y20480_8.png,221.379074,221.618031,221.901096,48.592815,48.699569,48.147749,1,D:\Aamir Gulzar\dataset\paip_data\Patches\vali...
6121,validation_data_30_nonMSIH_x5632_y1536_267.png,240.858345,241.378269,240.865139,9.029050,9.042939,8.667227,1,D:\Aamir Gulzar\dataset\paip_data\Patches\vali...
6122,validation_data_30_nonMSIH_x5632_y2048_268.png,241.475258,241.950039,241.526363,7.461050,7.407659,7.041214,1,D:\Aamir Gulzar\dataset\paip_data\Patches\vali...
6123,validation_data_30_nonMSIH_x6144_y0_302.png,242.436016,242.636345,242.419090,5.349561,5.504399,5.334903,1,D:\Aamir Gulzar\dataset\paip_data\Patches\vali...
6124,validation_data_30_nonMSIH_x6656_y6656_337.png,242.075901,241.654575,242.108212,5.472132,7.229547,5.558484,0,D:\Aamir Gulzar\dataset\paip_data\Patches\vali...