In [1]:
# !pip install python-dotenv timm huggingface_hub
from dotenv import load_dotenv
import os
load_dotenv()
hf_token = os.getenv("HF_TOKEN")

In [2]:

# ─────────────────────────────────────────────────────────────────────────────
# Virchow2 Extractor Class
# Output shape:  TenCrop → (10, 2560)  |  FiveCrop → (5, 2560)
# 2560 = 1280 class token + 1280 mean patch token
# ─────────────────────────────────────────────────────────────────────────────
import torch
import timm
from PIL import Image
from torchvision import transforms
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform
from timm.layers import SwiGLUPacked
from huggingface_hub import login


class Virchow2ExtractorCrops:
    """
    Virchow2 tile-level feature extractor with TenCrop / FiveCrop augmentation.

    Architecture : ViT-H/14  (632M params)
    Embedding    : 2560-d  (1280 class token + 1280 mean patch token)
    """

    def __init__(self, device: str = 'cuda', crop_size: int = 256):
        login(token=hf_token)

        self.device = torch.device(device if torch.cuda.is_available() else 'cpu')
        print(f"[Virchow2] Loading model on {self.device} ...")

        # Load model exactly as the model card specifies
        self.model = timm.create_model(
            "hf-hub:paige-ai/Virchow2",
            pretrained=True,
            mlp_layer=SwiGLUPacked,
            act_layer=torch.nn.SiLU,
        ).to(self.device)
        self.model.eval()
        print("[Virchow2] Model loaded ✓")

        # Resolve normalization stats directly from model pretrained_cfg
        # (ImageNet stats: mean=(0.485,0.456,0.406), std=(0.229,0.224,0.225))
        data_cfg = resolve_data_config(self.model.pretrained_cfg, model=self.model)
        mean = data_cfg["mean"]
        std  = data_cfg["std"]

        # Per-crop transform: resize each crop → normalize
        self.eval_transform = transforms.Compose([
            transforms.Resize((224, 224)),  # ViT-H/14 expects 224×224 crops
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std),
        ])

        self.fivecrop_transform = transforms.Compose([
            transforms.FiveCrop(crop_size),
            transforms.Lambda(lambda crops: torch.stack(
                [self.eval_transform(c) for c in crops]
            )),
        ])

        self.tencrop_transform = transforms.Compose([
            transforms.TenCrop(crop_size),
            transforms.Lambda(lambda crops: torch.stack(
                [self.eval_transform(c) for c in crops]
            )),
        ])

    def _load_image(self, image) -> Image.Image:
        if isinstance(image, str):
            return Image.open(image).convert("RGB")
        return image.convert("RGB")

    @torch.inference_mode()
    def _forward(self, crops_tensor: torch.Tensor) -> torch.Tensor:
        """
        Forward pass for a batch of crops.
        crops_tensor : (N, 3, 224, 224)
        returns      : (N, 2560)  fp32
        """
        crops_tensor = crops_tensor.to(self.device)
        with torch.autocast(device_type=self.device.type, dtype=torch.float16):
            output = self.model(crops_tensor)   # (N, 261, 1280)

        # Tokens 1–4 are register tokens → skip them
        class_token  = output[:, 0]      # (N, 1280)
        patch_tokens = output[:, 5:]     # (N, 256, 1280)

        # Concatenate class token + mean patch token → 2560-d embedding
        embedding = torch.cat([class_token, patch_tokens.mean(dim=1)], dim=-1)  # (N, 2560)
        return embedding.cpu().float()

    def extract_fivecrop_features(self, image) -> torch.Tensor:
        """
        Extract features from 5 crops of an image.
        Returns tensor of shape (5, 2560).
        """
        img = self._load_image(image)
        crops_tensor = self.fivecrop_transform(img)   # (5, 3, 224, 224)
        return self._forward(crops_tensor)

    def extract_tencrop_features(self, image) -> torch.Tensor:
        """
        Extract features from 10 crops (5 original + 5 horizontal flips).
        Returns tensor of shape (10, 2560).
        """
        img = self._load_image(image)
        crops_tensor = self.tencrop_transform(img)    # (10, 3, 224, 224)
        return self._forward(crops_tensor)

In [3]:

# ─────────────────────────────────────────────────────────────────────────────
#  Quick sanity check (verify shapes before running full pipeline)
# ─────────────────────────────────────────────────────────────────────────────
import numpy as np

extractor = Virchow2ExtractorCrops(device='cuda')

dummy_img = Image.fromarray(np.random.randint(0, 255, (512, 512, 3), dtype=np.uint8))

feat_5  = extractor.extract_fivecrop_features(dummy_img)
feat_10 = extractor.extract_tencrop_features(dummy_img)

print(f"FiveCrop  shape : {feat_5.shape}   → expected (5,  2560)")
print(f"TenCrop   shape : {feat_10.shape}  → expected (10, 2560)")

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to C:\Users\datainsight\.cache\huggingface\token
Login successful
[Virchow2] Loading model on cuda ...
[Virchow2] Model loaded ✓
FiveCrop  shape : torch.Size([5, 2560])   → expected (5,  2560)
TenCrop   shape : torch.Size([10, 2560])  → expected (10, 2560)

c:\Users\datainsight\anaconda3\envs\exaonepath\lib\site-packages\timm\layers\attention.py:80: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  x = F.scaled_dot_product_attention(

In [3]:

# ─────────────────────────────────────────────────────────────────────────────
# Full pipeline 
# ─────────────────────────────────────────────────────────────────────────────
import glob
import pandas as pd
from tqdm import tqdm


def run_full_pipeline_Virchow2_crops(
    patch_data_dir: str,
    extractor: Virchow2ExtractorCrops,
    non_white_csv: str,
    output_root: str,
    mode: str = "fivecrop",      # "tencrop" → (10, 2560)  |  "fivecrop" → (5, 2560)
):
    assert mode in ("tencrop", "fivecrop"), "mode must be 'tencrop' or 'fivecrop'"
    extract_fn = (
        extractor.extract_tencrop_features if mode == "tencrop"
        else extractor.extract_fivecrop_features
    )

    # Load valid (non-white) patch names
    non_white_df = pd.read_csv(non_white_csv)
    valid_patch_names = set(non_white_df["patch_name"].astype(str))
    print(f"[Pipeline] Valid patches in CSV : {len(valid_patch_names):,}")
    print(f"[Pipeline] Mode                 : {mode}")
    print(f"[Pipeline] Output root          : {output_root}\n")

    slide_dirs = sorted(glob.glob(os.path.join(patch_data_dir, "*")))

    for slide_dir in tqdm(slide_dirs, desc="Slides", unit="slide", position=0):
        slide_name = os.path.basename(slide_dir)
        feat_dir   = os.path.join(output_root, slide_name)
        os.makedirs(feat_dir, exist_ok=True)

        # Filter to valid non-white patches only
        all_patches   = glob.glob(os.path.join(slide_dir, "*.png"))
        valid_patches = [p for p in all_patches
                         if os.path.basename(p) in valid_patch_names]

        if not valid_patches:
            tqdm.write(f"  ❌  No valid patches for {slide_name}")
            continue

        # Skip already-processed patches (resume-safe)
        done = {os.path.splitext(f.name)[0]
                for f in os.scandir(feat_dir) if f.name.endswith(".pt")}
        to_process = [p for p in valid_patches
                      if os.path.splitext(os.path.basename(p))[0] not in done]

        if not to_process:
            tqdm.write(f"  ⏭️  Skipped {slide_name} ({len(valid_patches):,} patches already done)")
            continue

        for patch_path in tqdm(to_process, desc=f"  {slide_name}",
                               unit="patch", position=1, leave=False):
            patch_name = os.path.splitext(os.path.basename(patch_path))[0]
            save_path  = os.path.join(feat_dir, patch_name + ".pt")
            try:
                features = extract_fn(patch_path)   # (10, 2560) or (5, 2560)
                torch.save(features, save_path)
            except Exception as e:
                tqdm.write(f"  ❌  Error on {patch_path}: {e}")

        tqdm.write(f"  ✅  {slide_name} — processed {len(to_process):,} new "
                   f"(total valid: {len(valid_patches):,})")

In [5]:
extractor = Virchow2ExtractorCrops(device='cuda')

run_full_pipeline_Virchow2_crops(
    patch_data_dir = r"D:\Aamir Gulzar\KSA_project2\dataset\patch_data",
    extractor      = extractor,
    non_white_csv  = r"D:\Aamir Gulzar\KSA_project2\dataset\final_merged_without_white.csv",
    output_root    = r"D:\Aamir Gulzar\KSA_project2\dataset\Features\Virchow2_fivecrop",
    mode           = "fivecrop",     # switch to "fivecrop" if needed
)

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to C:\Users\datainsight\.cache\huggingface\token
Login successful
[Virchow2] Loading model on cuda ...
[Virchow2] Model loaded ✓
[Pipeline] Valid patches in CSV : 1,377,933
[Pipeline] Mode                 : fivecrop
[Pipeline] Output root          : D:\Aamir Gulzar\KSA_project2\dataset\Features\Virchow2_fivecrop

Slides:   0%|          | 1/417 [01:37<11:14:50, 97.33s/slide]

  ✅  TCGA-3L-AA1B_nonMSIH — processed 1,878 new (total valid: 1,878)

Slides:   0%|          | 2/417 [05:15<19:23:19, 168.19s/slide]

  ✅  TCGA-4N-A93T_nonMSIH — processed 4,240 new (total valid: 4,240)

Slides:   1%|          | 3/417 [10:43<27:44:21, 241.21s/slide]

  ✅  TCGA-5M-AAT4_nonMSIH — processed 6,411 new (total valid: 6,411)

Slides:   1%|          | 4/417 [14:36<27:19:30, 238.19s/slide]

  ✅  TCGA-5M-AAT6_MSIH — processed 4,320 new (total valid: 4,320)

Slides:   1%|          | 5/417 [21:00<33:14:53, 290.52s/slide]

  ✅  TCGA-5M-AATE_nonMSIH — processed 7,583 new (total valid: 7,583)

Slides:   1%|▏         | 6/417 [21:38<23:22:26, 204.74s/slide]

  ✅  TCGA-A6-2671_nonMSIH — processed 710 new (total valid: 710)

Slides:   2%|▏         | 7/417 [22:27<17:31:02, 153.81s/slide]

  ✅  TCGA-A6-2681_nonMSIH — processed 840 new (total valid: 840)

Slides:   2%|▏         | 8/417 [24:31<16:23:16, 144.24s/slide]

  ✅  TCGA-A6-2685_nonMSIH — processed 2,428 new (total valid: 2,428)

Slides:   2%|▏         | 9/417 [26:26<15:18:38, 135.09s/slide]

  ✅  TCGA-A6-2686_MSIH — processed 2,258 new (total valid: 2,258)

Slides:   2%|▏         | 10/417 [28:19<14:31:33, 128.48s/slide]

  ✅  TCGA-A6-3807_nonMSIH — processed 2,337 new (total valid: 2,337)

Slides:   3%|▎         | 11/417 [30:20<14:14:00, 126.21s/slide]

  ✅  TCGA-A6-4105_nonMSIH — processed 2,365 new (total valid: 2,365)

Slides:   3%|▎         | 12/417 [31:03<11:21:08, 100.91s/slide]

  ✅  TCGA-A6-4107_nonMSIH — processed 836 new (total valid: 836)

Slides:   3%|▎         | 13/417 [31:57<9:43:50, 86.71s/slide]

  ✅  TCGA-A6-5657_nonMSIH — processed 1,047 new (total valid: 1,047)

Slides:   3%|▎         | 14/417 [32:49<8:32:13, 76.26s/slide]

  ✅  TCGA-A6-5660_nonMSIH — processed 1,016 new (total valid: 1,016)

Slides:   4%|▎         | 15/417 [33:35<7:28:31, 66.94s/slide]

  ✅  TCGA-A6-5661_MSIH — processed 875 new (total valid: 875)

Slides:   4%|▍         | 16/417 [34:02<6:08:17, 55.11s/slide]

  ✅  TCGA-A6-5662_nonMSIH — processed 532 new (total valid: 532)

Slides:   4%|▍         | 17/417 [35:36<7:24:53, 66.73s/slide]

  ✅  TCGA-A6-5664_nonMSIH — processed 1,840 new (total valid: 1,840)

Slides:   4%|▍         | 18/417 [36:16<6:29:00, 58.50s/slide]

  ✅  TCGA-A6-5665_MSIH — processed 764 new (total valid: 764)

Slides:   5%|▍         | 19/417 [38:03<8:06:13, 73.30s/slide]

  ✅  TCGA-A6-5666_nonMSIH — processed 2,097 new (total valid: 2,097)

Slides:   5%|▍         | 20/417 [38:24<6:20:42, 57.54s/slide]

  ✅  TCGA-A6-5667_nonMSIH — processed 415 new (total valid: 415)

Slides:   5%|▌         | 21/417 [39:53<7:21:24, 66.88s/slide]

  ✅  TCGA-A6-6137_nonMSIH — processed 1,593 new (total valid: 1,593)

Slides:   5%|▌         | 22/417 [40:48<6:58:18, 63.54s/slide]

  ✅  TCGA-A6-6138_nonMSIH — processed 1,090 new (total valid: 1,090)

Slides:   6%|▌         | 23/417 [41:52<6:56:17, 63.40s/slide]

  ✅  TCGA-A6-6142_nonMSIH — processed 1,133 new (total valid: 1,133)

Slides:   6%|▌         | 24/417 [42:21<5:47:33, 53.06s/slide]

  ✅  TCGA-A6-6648_nonMSIH — processed 572 new (total valid: 572)

Slides:   6%|▌         | 25/417 [43:00<5:21:02, 49.14s/slide]

  ✅  TCGA-A6-6649_nonMSIH — processed 789 new (total valid: 789)

Slides:   6%|▌         | 26/417 [43:57<5:34:53, 51.39s/slide]

  ✅  TCGA-A6-6651_nonMSIH — processed 1,110 new (total valid: 1,110)

Slides:   6%|▋         | 27/417 [44:20<4:39:19, 42.97s/slide]

  ✅  TCGA-A6-6652_nonMSIH — processed 446 new (total valid: 446)

Slides:   7%|▋         | 28/417 [45:33<5:36:19, 51.88s/slide]

  ✅  TCGA-A6-6653_MSIH — processed 1,411 new (total valid: 1,411)

Slides:   7%|▋         | 29/417 [46:53<6:30:30, 60.39s/slide]

  ✅  TCGA-A6-6654_nonMSIH — processed 1,588 new (total valid: 1,588)

Slides:   7%|▋         | 30/417 [47:37<5:56:13, 55.23s/slide]

  ✅  TCGA-A6-A565_nonMSIH — processed 779 new (total valid: 779)

Slides:   7%|▋         | 31/417 [49:06<7:01:26, 65.51s/slide]

  ✅  TCGA-A6-A566_nonMSIH — processed 1,716 new (total valid: 1,716)

Slides:   8%|▊         | 32/417 [51:02<8:36:58, 80.57s/slide]

  ✅  TCGA-A6-A567_nonMSIH — processed 2,231 new (total valid: 2,231)

Slides:   8%|▊         | 33/417 [52:46<9:21:58, 87.81s/slide]

  ✅  TCGA-A6-A56B_nonMSIH — processed 2,056 new (total valid: 2,056)

Slides:   8%|▊         | 34/417 [56:52<14:22:16, 135.08s/slide]

  ✅  TCGA-AA-3664_nonMSIH — processed 5,067 new (total valid: 5,067)

Slides:   8%|▊         | 35/417 [1:00:38<17:14:15, 162.45s/slide]

  ✅  TCGA-AA-3666_nonMSIH — processed 4,605 new (total valid: 4,605)

Slides:   9%|▊         | 36/417 [1:03:22<17:14:00, 162.84s/slide]

  ✅  TCGA-AA-3667_nonMSIH — processed 3,312 new (total valid: 3,312)

Slides:   9%|▉         | 37/417 [1:04:53<14:54:24, 141.22s/slide]

  ✅  TCGA-AA-3673_nonMSIH — processed 1,588 new (total valid: 1,588)

Slides:   9%|▉         | 38/417 [1:06:15<13:00:58, 123.64s/slide]

  ✅  TCGA-AA-3678_nonMSIH — processed 1,654 new (total valid: 1,654)

Slides:   9%|▉         | 39/417 [1:09:10<14:34:32, 138.82s/slide]

  ✅  TCGA-AA-3679_nonMSIH — processed 3,570 new (total valid: 3,570)

Slides:  10%|▉         | 40/417 [1:13:15<17:52:45, 170.73s/slide]

  ✅  TCGA-AA-3680_nonMSIH — processed 4,503 new (total valid: 4,503)

Slides:  10%|▉         | 41/417 [1:15:28<16:38:41, 159.37s/slide]

  ✅  TCGA-AA-3681_nonMSIH — processed 2,725 new (total valid: 2,725)

Slides:  10%|█         | 42/417 [1:26:18<31:57:13, 306.76s/slide]

  ✅  TCGA-AA-3684_nonMSIH — processed 13,657 new (total valid: 13,657)

Slides:  10%|█         | 43/417 [1:28:56<27:12:49, 261.95s/slide]

  ✅  TCGA-AA-3688_nonMSIH — processed 3,279 new (total valid: 3,279)

Slides:  11%|█         | 44/417 [1:31:33<23:53:44, 230.63s/slide]

  ✅  TCGA-AA-3692_nonMSIH — processed 2,903 new (total valid: 2,903)

Slides:  11%|█         | 45/417 [1:34:53<22:51:51, 221.27s/slide]

  ✅  TCGA-AA-3693_nonMSIH — processed 4,176 new (total valid: 4,176)

Slides:  11%|█         | 46/417 [1:36:38<19:13:35, 186.56s/slide]

  ✅  TCGA-AA-3696_nonMSIH — processed 2,092 new (total valid: 2,092)

Slides:  11%|█▏        | 47/417 [1:41:04<21:36:19, 210.22s/slide]

  ✅  TCGA-AA-3715_MSIH — processed 5,430 new (total valid: 5,430)

Slides:  12%|█▏        | 48/417 [1:43:35<19:45:05, 192.70s/slide]

  ✅  TCGA-AA-3811_MSIH — processed 3,179 new (total valid: 3,179)

Slides:  12%|█▏        | 49/417 [1:46:39<19:24:23, 189.85s/slide]

  ✅  TCGA-AA-3812_nonMSIH — processed 3,469 new (total valid: 3,469)

Slides:  12%|█▏        | 50/417 [1:47:39<15:22:57, 150.89s/slide]

  ✅  TCGA-AA-3814_nonMSIH — processed 1,230 new (total valid: 1,230)

Slides:  12%|█▏        | 51/417 [1:50:04<15:10:59, 149.34s/slide]

  ✅  TCGA-AA-3818_nonMSIH — processed 3,040 new (total valid: 3,040)

Slides:  12%|█▏        | 52/417 [1:52:20<14:43:16, 145.20s/slide]

  ✅  TCGA-AA-3819_nonMSIH — processed 2,527 new (total valid: 2,527)

Slides:  13%|█▎        | 53/417 [1:54:22<13:58:01, 138.13s/slide]

  ✅  TCGA-AA-3821_MSIH — processed 2,547 new (total valid: 2,547)

Slides:  13%|█▎        | 54/417 [1:56:39<13:55:20, 138.07s/slide]

  ✅  TCGA-AA-3831_nonMSIH — processed 2,931 new (total valid: 2,931)

Slides:  13%|█▎        | 55/417 [2:01:24<18:18:09, 182.01s/slide]

  ✅  TCGA-AA-3833_MSIH — processed 5,185 new (total valid: 5,185)

Slides:  13%|█▎        | 56/417 [2:04:06<17:38:59, 176.01s/slide]

  ✅  TCGA-AA-3837_nonMSIH — processed 3,214 new (total valid: 3,214)

Slides:  14%|█▎        | 57/417 [2:05:46<15:18:26, 153.07s/slide]

  ✅  TCGA-AA-3842_nonMSIH — processed 2,103 new (total valid: 2,103)

Slides:  14%|█▍        | 58/417 [2:07:58<14:39:09, 146.93s/slide]

  ✅  TCGA-AA-3844_nonMSIH — processed 2,773 new (total valid: 2,773)

Slides:  14%|█▍        | 59/417 [2:10:13<14:14:29, 143.21s/slide]

  ✅  TCGA-AA-3845_MSIH — processed 2,679 new (total valid: 2,679)

Slides:  14%|█▍        | 60/417 [2:11:12<11:42:24, 118.05s/slide]

  ✅  TCGA-AA-3846_nonMSIH — processed 1,278 new (total valid: 1,278)

Slides:  15%|█▍        | 61/417 [2:15:02<14:59:52, 151.67s/slide]

  ✅  TCGA-AA-3848_nonMSIH — processed 4,736 new (total valid: 4,736)

Slides:  15%|█▍        | 62/417 [2:17:02<14:00:18, 142.02s/slide]

  ✅  TCGA-AA-3850_nonMSIH — processed 2,484 new (total valid: 2,484)

Slides:  15%|█▌        | 63/417 [2:19:00<13:16:00, 134.92s/slide]

  ✅  TCGA-AA-3851_nonMSIH — processed 2,500 new (total valid: 2,500)

Slides:  15%|█▌        | 64/417 [2:20:39<12:09:31, 124.00s/slide]

  ✅  TCGA-AA-3852_nonMSIH — processed 2,054 new (total valid: 2,054)

Slides:  16%|█▌        | 65/417 [2:21:36<10:11:00, 104.15s/slide]

  ✅  TCGA-AA-3854_nonMSIH — processed 1,036 new (total valid: 1,036)

Slides:  16%|█▌        | 66/417 [2:24:20<11:54:12, 122.09s/slide]

  ✅  TCGA-AA-3855_nonMSIH — processed 3,536 new (total valid: 3,536)

Slides:  16%|█▌        | 67/417 [2:29:57<18:07:23, 186.41s/slide]

  ✅  TCGA-AA-3856_nonMSIH — processed 6,984 new (total valid: 6,984)

Slides:  16%|█▋        | 68/417 [2:30:32<13:41:17, 141.20s/slide]

  ✅  TCGA-AA-3858_nonMSIH — processed 755 new (total valid: 755)

Slides:  17%|█▋        | 69/417 [2:32:42<13:18:07, 137.61s/slide]

  ✅  TCGA-AA-3864_MSIH — processed 2,829 new (total valid: 2,829)

Slides:  17%|█▋        | 70/417 [2:34:39<12:40:07, 131.43s/slide]

  ✅  TCGA-AA-3866_nonMSIH — processed 2,526 new (total valid: 2,526)

Slides:  17%|█▋        | 71/417 [2:36:34<12:09:11, 126.45s/slide]

  ✅  TCGA-AA-3867_nonMSIH — processed 2,358 new (total valid: 2,358)

Slides:  17%|█▋        | 72/417 [2:38:42<12:10:36, 127.06s/slide]

  ✅  TCGA-AA-3875_nonMSIH — processed 2,653 new (total valid: 2,653)

Slides:  18%|█▊        | 73/417 [2:41:04<12:34:51, 131.66s/slide]

  ✅  TCGA-AA-3877_MSIH — processed 3,045 new (total valid: 3,045)

Slides:  18%|█▊        | 74/417 [2:47:28<19:44:46, 207.25s/slide]

  ✅  TCGA-AA-3947_MSIH — processed 8,357 new (total valid: 8,357)

Slides:  18%|█▊        | 75/417 [2:49:40<17:32:02, 184.57s/slide]

  ✅  TCGA-AA-3949_MSIH — processed 2,720 new (total valid: 2,720)

Slides:  18%|█▊        | 76/417 [2:51:45<15:47:04, 166.64s/slide]

  ✅  TCGA-AA-3950_MSIH — processed 2,745 new (total valid: 2,745)

Slides:  18%|█▊        | 77/417 [2:52:54<12:59:01, 137.47s/slide]

  ✅  TCGA-AA-3952_nonMSIH — processed 1,421 new (total valid: 1,421)

Slides:  19%|█▊        | 78/417 [2:55:39<13:44:11, 145.88s/slide]

  ✅  TCGA-AA-3956_nonMSIH — processed 3,439 new (total valid: 3,439)

Slides:  19%|█▉        | 79/417 [2:59:18<15:45:01, 167.76s/slide]

  ✅  TCGA-AA-3966_MSIH — processed 4,784 new (total valid: 4,784)

Slides:  19%|█▉        | 80/417 [3:01:42<15:02:24, 160.67s/slide]

  ✅  TCGA-AA-3968_nonMSIH — processed 2,597 new (total valid: 2,597)

Slides:  19%|█▉        | 81/417 [3:06:32<18:35:57, 199.28s/slide]

  ✅  TCGA-AA-3971_nonMSIH — processed 5,800 new (total valid: 5,800)

Slides:  20%|█▉        | 82/417 [3:09:31<17:59:43, 193.38s/slide]

  ✅  TCGA-AA-3973_nonMSIH — processed 3,720 new (total valid: 3,720)

Slides:  20%|█▉        | 83/417 [3:13:05<18:30:40, 199.52s/slide]

  ✅  TCGA-AA-3975_nonMSIH — processed 4,686 new (total valid: 4,686)

Slides:  20%|██        | 84/417 [3:14:49<15:47:10, 170.66s/slide]

  ✅  TCGA-AA-3976_nonMSIH — processed 1,878 new (total valid: 1,878)

Slides:  20%|██        | 85/417 [3:17:17<15:07:21, 163.98s/slide]

  ✅  TCGA-AA-3979_nonMSIH — processed 3,148 new (total valid: 3,148)

Slides:  21%|██        | 86/417 [3:20:28<15:50:15, 172.25s/slide]

  ✅  TCGA-AA-3982_nonMSIH — processed 3,833 new (total valid: 3,833)

Slides:  21%|██        | 87/417 [3:24:02<16:55:57, 184.72s/slide]

  ✅  TCGA-AA-3984_nonMSIH — processed 3,813 new (total valid: 3,813)

Slides:  21%|██        | 88/417 [3:29:54<21:27:41, 234.84s/slide]

  ✅  TCGA-AA-3986_nonMSIH — processed 7,708 new (total valid: 7,708)

Slides:  21%|██▏       | 89/417 [3:31:58<18:21:09, 201.43s/slide]

  ✅  TCGA-AA-3989_nonMSIH — processed 2,661 new (total valid: 2,661)

Slides:  22%|██▏       | 90/417 [3:33:21<15:05:41, 166.18s/slide]

  ✅  TCGA-AA-3994_nonMSIH — processed 1,773 new (total valid: 1,773)

Slides:  22%|██▏       | 91/417 [3:39:18<20:13:54, 223.42s/slide]

  ✅  TCGA-AA-A010_nonMSIH — processed 7,149 new (total valid: 7,149)

Slides:  22%|██▏       | 92/417 [3:45:54<24:50:40, 275.20s/slide]

  ✅  TCGA-AA-A01P_MSIH — processed 8,176 new (total valid: 8,176)

Slides:  22%|██▏       | 93/417 [3:53:36<29:47:21, 330.99s/slide]

  ✅  TCGA-AA-A01R_MSIH — processed 8,904 new (total valid: 8,904)

Slides:  23%|██▎       | 94/417 [3:59:33<30:24:12, 338.86s/slide]

  ✅  TCGA-AA-A01S_nonMSIH — processed 6,357 new (total valid: 6,357)

Slides:  23%|██▎       | 95/417 [4:02:10<25:26:32, 284.45s/slide]

  ✅  TCGA-AA-A01T_nonMSIH — processed 3,198 new (total valid: 3,198)

Slides:  23%|██▎       | 96/417 [4:10:42<31:27:01, 352.71s/slide]

  ✅  TCGA-AA-A01V_nonMSIH — processed 10,531 new (total valid: 10,531)

Slides:  23%|██▎       | 97/417 [4:16:02<30:27:44, 342.70s/slide]

  ✅  TCGA-AA-A01X_nonMSIH — processed 6,090 new (total valid: 6,090)

Slides:  24%|██▎       | 98/417 [4:20:32<28:26:55, 321.05s/slide]

  ✅  TCGA-AA-A01Z_nonMSIH — processed 5,584 new (total valid: 5,584)

Slides:  24%|██▎       | 99/417 [4:25:13<27:17:40, 308.99s/slide]

  ✅  TCGA-AA-A024_nonMSIH — processed 5,716 new (total valid: 5,716)

Slides:  24%|██▍       | 100/417 [4:28:17<23:54:59, 271.61s/slide]

  ✅  TCGA-AA-A02E_nonMSIH — processed 3,789 new (total valid: 3,789)

Slides:  24%|██▍       | 101/417 [4:35:14<27:40:06, 315.21s/slide]

  ✅  TCGA-AA-A02F_nonMSIH — processed 8,534 new (total valid: 8,534)

Slides:  24%|██▍       | 102/417 [4:39:11<25:30:49, 291.59s/slide]

  ✅  TCGA-AA-A02H_nonMSIH — processed 4,208 new (total valid: 4,208)

Slides:  25%|██▍       | 103/417 [4:43:28<24:31:17, 281.14s/slide]

  ✅  TCGA-AA-A02O_nonMSIH — processed 5,532 new (total valid: 5,532)

Slides:  25%|██▍       | 104/417 [4:46:08<21:17:29, 244.89s/slide]

  ✅  TCGA-AA-A02Y_nonMSIH — processed 3,045 new (total valid: 3,045)

Slides:  25%|██▌       | 105/417 [4:49:47<20:32:21, 236.99s/slide]

  ✅  TCGA-AA-A03F_nonMSIH — processed 3,970 new (total valid: 3,970)

Slides:  25%|██▌       | 106/417 [4:57:38<26:32:55, 307.32s/slide]

  ✅  TCGA-AA-A03J_nonMSIH — processed 9,459 new (total valid: 9,459)

Slides:  26%|██▌       | 107/417 [4:58:05<19:13:40, 223.29s/slide]

  ✅  TCGA-AD-5900_MSIH — processed 575 new (total valid: 575)

Slides:  26%|██▌       | 108/417 [4:58:27<13:58:53, 162.89s/slide]

  ✅  TCGA-AD-6548_nonMSIH — processed 429 new (total valid: 429)

Slides:  26%|██▌       | 109/417 [4:59:12<10:54:25, 127.48s/slide]

  ✅  TCGA-AD-6888_nonMSIH — processed 896 new (total valid: 896)

Slides:  26%|██▋       | 110/417 [5:00:56<10:15:40, 120.33s/slide]

  ✅  TCGA-AD-6889_MSIH — processed 2,116 new (total valid: 2,116)

Slides:  27%|██▋       | 111/417 [5:01:16<7:40:10, 90.23s/slide]

  ✅  TCGA-AD-6890_nonMSIH — processed 367 new (total valid: 367)

Slides:  27%|██▋       | 112/417 [5:01:46<6:06:38, 72.13s/slide]

  ✅  TCGA-AD-6901_nonMSIH — processed 558 new (total valid: 558)

Slides:  27%|██▋       | 113/417 [5:02:02<4:40:14, 55.31s/slide]

  ✅  TCGA-AD-6963_nonMSIH — processed 320 new (total valid: 320)

Slides:  27%|██▋       | 114/417 [5:02:58<4:40:50, 55.61s/slide]

  ✅  TCGA-AD-6964_MSIH — processed 1,159 new (total valid: 1,159)

Slides:  28%|██▊       | 115/417 [5:03:19<3:48:10, 45.33s/slide]

  ✅  TCGA-AD-6965_nonMSIH — processed 444 new (total valid: 444)

Slides:  28%|██▊       | 116/417 [5:03:48<3:22:15, 40.32s/slide]

  ✅  TCGA-AD-A5EJ_MSIH — processed 579 new (total valid: 579)

Slides:  28%|██▊       | 117/417 [5:04:41<3:41:27, 44.29s/slide]

  ✅  TCGA-AD-A5EK_nonMSIH — processed 1,069 new (total valid: 1,069)

Slides:  28%|██▊       | 118/417 [5:05:49<4:16:07, 51.40s/slide]

  ✅  TCGA-AF-2687_nonMSIH — processed 1,369 new (total valid: 1,369)

Slides:  29%|██▊       | 119/417 [5:08:56<7:36:43, 91.96s/slide]

  ✅  TCGA-AF-2690_nonMSIH — processed 3,786 new (total valid: 3,786)

Slides:  29%|██▉       | 120/417 [5:09:34<6:15:34, 75.87s/slide]

  ✅  TCGA-AF-2693_nonMSIH — processed 754 new (total valid: 754)

Slides:  29%|██▉       | 121/417 [5:10:34<5:50:10, 70.98s/slide]

  ✅  TCGA-AF-3911_nonMSIH — processed 1,171 new (total valid: 1,171)

Slides:  29%|██▉       | 122/417 [5:11:44<5:47:50, 70.75s/slide]

  ✅  TCGA-AF-4110_nonMSIH — processed 1,421 new (total valid: 1,421)

Slides:  29%|██▉       | 123/417 [5:12:52<5:42:25, 69.88s/slide]

  ✅  TCGA-AF-6136_nonMSIH — processed 1,363 new (total valid: 1,363)

Slides:  30%|██▉       | 124/417 [5:13:30<4:54:29, 60.31s/slide]

  ✅  TCGA-AF-6655_nonMSIH — processed 761 new (total valid: 761)

Slides:  30%|██▉       | 125/417 [5:15:39<6:33:25, 80.84s/slide]

  ✅  TCGA-AF-6672_nonMSIH — processed 2,574 new (total valid: 2,574)

Slides:  30%|███       | 126/417 [5:18:05<8:07:52, 100.59s/slide]

  ✅  TCGA-AF-A56K_nonMSIH — processed 2,962 new (total valid: 2,962)

Slides:  30%|███       | 127/417 [5:20:37<9:20:15, 115.91s/slide]

  ✅  TCGA-AF-A56L_nonMSIH — processed 3,089 new (total valid: 3,089)

Slides:  31%|███       | 128/417 [5:21:15<7:25:55, 92.58s/slide]

  ✅  TCGA-AF-A56N_nonMSIH — processed 732 new (total valid: 732)

Slides:  31%|███       | 129/417 [5:22:09<6:28:25, 80.92s/slide]

  ✅  TCGA-AG-3726_nonMSIH — processed 957 new (total valid: 957)

Slides:  31%|███       | 130/417 [5:23:00<5:44:29, 72.02s/slide]

  ✅  TCGA-AG-3727_nonMSIH — processed 1,051 new (total valid: 1,051)

Slides:  31%|███▏      | 131/417 [5:24:04<5:31:27, 69.54s/slide]

  ✅  TCGA-AG-3878_nonMSIH — processed 1,281 new (total valid: 1,281)

Slides:  32%|███▏      | 132/417 [5:25:26<5:47:51, 73.23s/slide]

  ✅  TCGA-AG-3882_nonMSIH — processed 1,685 new (total valid: 1,685)

Slides:  32%|███▏      | 133/417 [5:28:30<8:24:38, 106.61s/slide]

  ✅  TCGA-AG-3883_nonMSIH — processed 3,637 new (total valid: 3,637)

Slides:  32%|███▏      | 134/417 [5:30:03<8:03:47, 102.57s/slide]

  ✅  TCGA-AG-3885_nonMSIH — processed 1,939 new (total valid: 1,939)

Slides:  32%|███▏      | 135/417 [5:31:07<7:07:04, 90.87s/slide]

  ✅  TCGA-AG-3887_nonMSIH — processed 1,270 new (total valid: 1,270)

Slides:  33%|███▎      | 136/417 [5:33:46<8:41:42, 111.40s/slide]

  ✅  TCGA-AG-3890_nonMSIH — processed 3,201 new (total valid: 3,201)

Slides:  33%|███▎      | 137/417 [5:35:57<9:07:33, 117.33s/slide]

  ✅  TCGA-AG-3892_nonMSIH — processed 2,705 new (total valid: 2,705)

Slides:  33%|███▎      | 138/417 [5:37:12<8:06:38, 104.66s/slide]

  ✅  TCGA-AG-3893_nonMSIH — processed 1,552 new (total valid: 1,552)

Slides:  33%|███▎      | 139/417 [5:39:03<8:12:46, 106.35s/slide]

  ✅  TCGA-AG-3894_nonMSIH — processed 2,294 new (total valid: 2,294)

Slides:  34%|███▎      | 140/417 [5:41:38<9:19:17, 121.15s/slide]

  ✅  TCGA-AG-3896_nonMSIH — processed 3,182 new (total valid: 3,182)

Slides:  34%|███▍      | 141/417 [5:45:12<11:24:34, 148.82s/slide]

  ✅  TCGA-AG-3898_nonMSIH — processed 3,845 new (total valid: 3,845)

Slides:  34%|███▍      | 142/417 [5:46:19<9:29:38, 124.29s/slide]

  ✅  TCGA-AG-3901_nonMSIH — processed 1,396 new (total valid: 1,396)

Slides:  34%|███▍      | 143/417 [5:49:31<11:00:38, 144.67s/slide]

  ✅  TCGA-AG-3902_nonMSIH — processed 4,048 new (total valid: 4,048)

Slides:  35%|███▍      | 144/417 [5:51:29<10:22:15, 136.76s/slide]

  ✅  TCGA-AG-3909_nonMSIH — processed 2,468 new (total valid: 2,468)

Slides:  35%|███▍      | 145/417 [5:54:17<11:02:31, 146.14s/slide]

  ✅  TCGA-AG-4001_nonMSIH — processed 3,369 new (total valid: 3,369)

Slides:  35%|███▌      | 146/417 [5:56:46<11:02:39, 146.71s/slide]

  ✅  TCGA-AG-4008_nonMSIH — processed 3,037 new (total valid: 3,037)

Slides:  35%|███▌      | 147/417 [5:58:42<10:19:09, 137.59s/slide]

  ✅  TCGA-AG-4015_nonMSIH — processed 2,503 new (total valid: 2,503)

Slides:  35%|███▌      | 148/417 [6:02:20<12:04:41, 161.64s/slide]

  ✅  TCGA-AG-4021_nonMSIH — processed 4,554 new (total valid: 4,554)

Slides:  36%|███▌      | 149/417 [6:05:30<12:40:34, 170.28s/slide]

  ✅  TCGA-AG-4022_nonMSIH — processed 3,776 new (total valid: 3,776)

Slides:  36%|███▌      | 150/417 [6:08:52<13:19:39, 179.70s/slide]

  ✅  TCGA-AG-A002_nonMSIH — processed 4,172 new (total valid: 4,172)

Slides:  36%|███▌      | 151/417 [6:12:55<14:41:26, 198.82s/slide]

  ✅  TCGA-AG-A008_nonMSIH — processed 4,871 new (total valid: 4,871)

Slides:  36%|███▋      | 152/417 [6:15:31<13:40:54, 185.87s/slide]

  ✅  TCGA-AG-A00C_nonMSIH — processed 3,215 new (total valid: 3,215)

Slides:  37%|███▋      | 153/417 [6:17:33<12:14:11, 166.86s/slide]

  ✅  TCGA-AG-A011_nonMSIH — processed 2,627 new (total valid: 2,627)

Slides:  37%|███▋      | 154/417 [6:22:07<14:32:22, 199.02s/slide]

  ✅  TCGA-AG-A015_nonMSIH — processed 5,589 new (total valid: 5,589)

Slides:  37%|███▋      | 155/417 [6:24:53<13:45:40, 189.09s/slide]

  ✅  TCGA-AG-A016_nonMSIH — processed 3,382 new (total valid: 3,382)

Slides:  37%|███▋      | 156/417 [6:26:07<11:11:55, 154.46s/slide]

  ✅  TCGA-AG-A01L_nonMSIH — processed 1,317 new (total valid: 1,317)

Slides:  38%|███▊      | 157/417 [6:28:07<10:24:25, 144.10s/slide]

  ✅  TCGA-AG-A01N_nonMSIH — processed 2,394 new (total valid: 2,394)

Slides:  38%|███▊      | 158/417 [6:35:56<17:23:04, 241.64s/slide]

  ✅  TCGA-AG-A01W_nonMSIH — processed 8,906 new (total valid: 8,906)

Slides:  38%|███▊      | 159/417 [6:40:07<17:30:53, 244.39s/slide]

  ✅  TCGA-AG-A01Y_nonMSIH — processed 5,119 new (total valid: 5,119)

Slides:  38%|███▊      | 160/417 [6:42:43<15:33:41, 217.98s/slide]

  ✅  TCGA-AG-A020_nonMSIH — processed 3,363 new (total valid: 3,363)

Slides:  39%|███▊      | 161/417 [6:45:07<13:54:56, 195.69s/slide]

  ✅  TCGA-AG-A026_nonMSIH — processed 3,001 new (total valid: 3,001)

Slides:  39%|███▉      | 162/417 [6:48:32<14:03:49, 198.55s/slide]

  ✅  TCGA-AG-A02N_MSIH — processed 4,418 new (total valid: 4,418)

Slides:  39%|███▉      | 163/417 [6:49:58<11:37:45, 164.83s/slide]

  ✅  TCGA-AG-A02X_nonMSIH — processed 1,831 new (total valid: 1,831)

Slides:  39%|███▉      | 164/417 [6:51:14<9:42:01, 138.03s/slide]

  ✅  TCGA-AH-6544_nonMSIH — processed 1,509 new (total valid: 1,509)

Slides:  40%|███▉      | 165/417 [6:51:26<7:01:15, 100.30s/slide]

  ✅  TCGA-AH-6547_nonMSIH — processed 241 new (total valid: 241)

Slides:  40%|███▉      | 166/417 [6:52:20<6:01:44, 86.47s/slide]

  ✅  TCGA-AH-6643_nonMSIH — processed 1,122 new (total valid: 1,122)

Slides:  40%|████      | 167/417 [6:52:48<4:46:51, 68.85s/slide]

  ✅  TCGA-AH-6644_nonMSIH — processed 557 new (total valid: 557)

Slides:  40%|████      | 168/417 [6:53:30<4:11:48, 60.68s/slide]

  ✅  TCGA-AH-6897_nonMSIH — processed 818 new (total valid: 818)

Slides:  41%|████      | 169/417 [6:54:03<3:36:55, 52.48s/slide]

  ✅  TCGA-AH-6903_nonMSIH — processed 650 new (total valid: 650)

Slides:  41%|████      | 170/417 [6:55:21<4:08:12, 60.29s/slide]

  ✅  TCGA-AM-5820_nonMSIH — processed 1,562 new (total valid: 1,562)

Slides:  41%|████      | 171/417 [6:57:02<4:56:50, 72.40s/slide]

  ✅  TCGA-AM-5821_MSIH — processed 2,035 new (total valid: 2,035)

Slides:  41%|████      | 172/417 [6:57:29<3:59:57, 58.77s/slide]

  ✅  TCGA-AU-3779_nonMSIH — processed 543 new (total valid: 543)

Slides:  41%|████▏     | 173/417 [6:58:28<3:59:42, 58.94s/slide]

  ✅  TCGA-AU-6004_MSIH — processed 1,168 new (total valid: 1,168)

Slides:  42%|████▏     | 174/417 [6:58:45<3:07:44, 46.36s/slide]

  ✅  TCGA-AY-4070_nonMSIH — processed 335 new (total valid: 335)

Slides:  42%|████▏     | 175/417 [6:59:06<2:35:44, 38.61s/slide]

  ✅  TCGA-AY-4071_nonMSIH — processed 426 new (total valid: 426)

Slides:  42%|████▏     | 176/417 [7:01:25<4:36:27, 68.83s/slide]

  ✅  TCGA-AY-5543_nonMSIH — processed 2,816 new (total valid: 2,816)

Slides:  42%|████▏     | 177/417 [7:04:35<7:00:22, 105.09s/slide]

  ✅  TCGA-AY-6196_nonMSIH — processed 3,831 new (total valid: 3,831)

Slides:  43%|████▎     | 178/417 [7:06:57<7:42:53, 116.21s/slide]

  ✅  TCGA-AY-6197_MSIH — processed 2,829 new (total valid: 2,829)

Slides:  43%|████▎     | 179/417 [7:08:30<7:13:41, 109.33s/slide]

  ✅  TCGA-AY-6386_nonMSIH — processed 1,862 new (total valid: 1,862)

Slides:  43%|████▎     | 180/417 [7:10:41<7:36:53, 115.67s/slide]

  ✅  TCGA-AY-A54L_nonMSIH — processed 2,604 new (total valid: 2,604)

Slides:  43%|████▎     | 181/417 [7:12:08<7:01:09, 107.07s/slide]

  ✅  TCGA-AY-A69D_nonMSIH — processed 1,739 new (total valid: 1,739)

Slides:  44%|████▎     | 182/417 [7:16:34<10:05:51, 154.69s/slide]

  ✅  TCGA-AY-A71X_nonMSIH — processed 5,452 new (total valid: 5,452)

Slides:  44%|████▍     | 183/417 [7:17:57<8:40:11, 133.38s/slide]

  ✅  TCGA-AY-A8YK_nonMSIH — processed 1,686 new (total valid: 1,686)

Slides:  44%|████▍     | 184/417 [7:20:20<8:49:03, 136.24s/slide]

  ✅  TCGA-AZ-4308_nonMSIH — processed 2,539 new (total valid: 2,539)

Slides:  44%|████▍     | 185/417 [7:24:19<10:45:47, 167.02s/slide]

  ✅  TCGA-AZ-4315_nonMSIH — processed 4,747 new (total valid: 4,747)

Slides:  45%|████▍     | 186/417 [7:28:02<11:47:14, 183.70s/slide]

  ✅  TCGA-AZ-4614_nonMSIH — processed 4,415 new (total valid: 4,415)

Slides:  45%|████▍     | 187/417 [7:31:25<12:06:56, 189.64s/slide]

  ✅  TCGA-AZ-4615_MSIH — processed 4,138 new (total valid: 4,138)

Slides:  45%|████▌     | 188/417 [7:34:17<11:43:35, 184.35s/slide]

  ✅  TCGA-AZ-4616_nonMSIH — processed 3,487 new (total valid: 3,487)

Slides:  45%|████▌     | 189/417 [7:36:40<10:52:55, 171.82s/slide]

  ✅  TCGA-AZ-4681_nonMSIH — processed 2,861 new (total valid: 2,861)

Slides:  46%|████▌     | 190/417 [7:39:32<10:50:18, 171.89s/slide]

  ✅  TCGA-AZ-4682_nonMSIH — processed 3,556 new (total valid: 3,556)

Slides:  46%|████▌     | 191/417 [7:43:33<12:05:32, 192.62s/slide]

  ✅  TCGA-AZ-5403_nonMSIH — processed 4,983 new (total valid: 4,983)

Slides:  46%|████▌     | 192/417 [7:45:11<10:16:12, 164.32s/slide]

  ✅  TCGA-AZ-5407_nonMSIH — processed 1,984 new (total valid: 1,984)

Slides:  46%|████▋     | 193/417 [7:47:52<10:09:47, 163.34s/slide]

  ✅  TCGA-AZ-6598_MSIH — processed 3,328 new (total valid: 3,328)

Slides:  47%|████▋     | 194/417 [7:50:19<9:48:49, 158.43s/slide]

  ✅  TCGA-AZ-6599_nonMSIH — processed 2,950 new (total valid: 2,950)

Slides:  47%|████▋     | 195/417 [7:54:09<11:05:35, 179.89s/slide]

  ✅  TCGA-AZ-6600_nonMSIH — processed 4,608 new (total valid: 4,608)

Slides:  47%|████▋     | 196/417 [7:57:21<11:16:15, 183.60s/slide]

  ✅  TCGA-AZ-6603_nonMSIH — processed 3,851 new (total valid: 3,851)

Slides:  47%|████▋     | 197/417 [8:00:44<11:33:42, 189.19s/slide]

  ✅  TCGA-AZ-6605_nonMSIH — processed 4,099 new (total valid: 4,099)

Slides:  47%|████▋     | 198/417 [8:03:54<11:31:22, 189.42s/slide]

  ✅  TCGA-AZ-6606_nonMSIH — processed 3,888 new (total valid: 3,888)

Slides:  48%|████▊     | 199/417 [8:05:47<10:05:03, 166.53s/slide]

  ✅  TCGA-CA-5254_nonMSIH — processed 2,309 new (total valid: 2,309)

Slides:  48%|████▊     | 200/417 [8:08:01<9:27:20, 156.87s/slide]

  ✅  TCGA-CA-5255_nonMSIH — processed 2,699 new (total valid: 2,699)

Slides:  48%|████▊     | 201/417 [8:09:13<7:52:57, 131.38s/slide]

  ✅  TCGA-CA-5256_nonMSIH — processed 1,428 new (total valid: 1,428)

Slides:  48%|████▊     | 202/417 [8:12:11<8:40:30, 145.26s/slide]

  ✅  TCGA-CA-5796_nonMSIH — processed 3,590 new (total valid: 3,590)

Slides:  49%|████▊     | 203/417 [8:13:47<7:45:25, 130.49s/slide]

  ✅  TCGA-CA-5797_nonMSIH — processed 1,916 new (total valid: 1,916)

Slides:  49%|████▉     | 204/417 [8:16:56<8:45:30, 148.03s/slide]

  ✅  TCGA-CA-6715_nonMSIH — processed 3,891 new (total valid: 3,891)

Slides:  49%|████▉     | 205/417 [8:19:45<9:05:28, 154.38s/slide]

  ✅  TCGA-CA-6716_nonMSIH — processed 3,345 new (total valid: 3,345)

Slides:  49%|████▉     | 206/417 [8:21:37<8:18:30, 141.75s/slide]

  ✅  TCGA-CA-6717_nonMSIH — processed 2,260 new (total valid: 2,260)

Slides:  50%|████▉     | 207/417 [8:24:03<8:20:09, 142.90s/slide]

  ✅  TCGA-CA-6718_nonMSIH — processed 2,936 new (total valid: 2,936)

Slides:  50%|████▉     | 208/417 [8:26:10<8:01:38, 138.27s/slide]

  ✅  TCGA-CA-6719_nonMSIH — processed 2,381 new (total valid: 2,381)

Slides:  50%|█████     | 209/417 [8:26:35<6:01:05, 104.16s/slide]

  ✅  TCGA-CI-6622_nonMSIH — processed 498 new (total valid: 498)

Slides:  50%|█████     | 210/417 [8:27:26<5:04:20, 88.22s/slide]

  ✅  TCGA-CI-6624_nonMSIH — processed 990 new (total valid: 990)

Slides:  51%|█████     | 211/417 [8:31:55<8:09:11, 142.48s/slide]

  ✅  TCGA-CK-4947_nonMSIH — processed 5,386 new (total valid: 5,386)

Slides:  51%|█████     | 212/417 [8:34:43<8:33:05, 150.17s/slide]

  ✅  TCGA-CK-4948_nonMSIH — processed 3,351 new (total valid: 3,351)

Slides:  51%|█████     | 213/417 [8:38:53<10:12:06, 180.03s/slide]

  ✅  TCGA-CK-4950_nonMSIH — processed 4,932 new (total valid: 4,932)

Slides:  51%|█████▏    | 214/417 [8:40:54<9:09:58, 162.56s/slide]

  ✅  TCGA-CK-4951_MSIH — processed 2,514 new (total valid: 2,514)

Slides:  52%|█████▏    | 215/417 [8:43:17<8:47:12, 156.60s/slide]

  ✅  TCGA-CK-4952_nonMSIH — processed 2,891 new (total valid: 2,891)

Slides:  52%|█████▏    | 216/417 [8:47:45<10:36:23, 189.97s/slide]

  ✅  TCGA-CK-5912_nonMSIH — processed 5,430 new (total valid: 5,430)

Slides:  52%|█████▏    | 217/417 [8:52:05<11:43:15, 210.98s/slide]

  ✅  TCGA-CK-5913_MSIH — processed 5,270 new (total valid: 5,270)

Slides:  52%|█████▏    | 218/417 [8:55:09<11:12:34, 202.79s/slide]

  ✅  TCGA-CK-5914_nonMSIH — processed 3,783 new (total valid: 3,783)

Slides:  53%|█████▎    | 219/417 [9:00:13<12:50:03, 233.35s/slide]

  ✅  TCGA-CK-5915_nonMSIH — processed 6,321 new (total valid: 6,321)

Slides:  53%|█████▎    | 220/417 [9:05:30<14:08:43, 258.49s/slide]

  ✅  TCGA-CK-5916_MSIH — processed 5,885 new (total valid: 5,885)

Slides:  53%|█████▎    | 221/417 [9:08:48<13:05:04, 240.33s/slide]

  ✅  TCGA-CK-6746_MSIH — processed 4,006 new (total valid: 4,006)

Slides:  53%|█████▎    | 222/417 [9:12:43<12:55:20, 238.57s/slide]

  ✅  TCGA-CK-6747_MSIH — processed 4,789 new (total valid: 4,789)

Slides:  53%|█████▎    | 223/417 [9:16:43<12:53:10, 239.12s/slide]

  ✅  TCGA-CK-6748_nonMSIH — processed 4,901 new (total valid: 4,901)

Slides:  54%|█████▎    | 224/417 [9:18:53<11:03:16, 206.20s/slide]

  ✅  TCGA-CK-6751_nonMSIH — processed 2,629 new (total valid: 2,629)

Slides:  54%|█████▍    | 225/417 [9:21:55<10:36:41, 198.97s/slide]

  ✅  TCGA-CL-4957_nonMSIH — processed 3,681 new (total valid: 3,681)

Slides:  54%|█████▍    | 226/417 [9:24:38<9:59:10, 188.22s/slide]

  ✅  TCGA-CL-5917_nonMSIH — processed 3,438 new (total valid: 3,438)

Slides:  54%|█████▍    | 227/417 [9:27:50<9:59:35, 189.34s/slide]

  ✅  TCGA-CL-5918_nonMSIH — processed 3,912 new (total valid: 3,912)

Slides:  55%|█████▍    | 228/417 [9:33:45<12:33:24, 239.18s/slide]

  ✅  TCGA-CM-4743_MSIH — processed 6,158 new (total valid: 6,158)

Slides:  55%|█████▍    | 229/417 [9:39:22<14:01:01, 268.41s/slide]

  ✅  TCGA-CM-4744_nonMSIH — processed 6,826 new (total valid: 6,826)

Slides:  55%|█████▌    | 230/417 [9:45:05<15:06:06, 290.73s/slide]

  ✅  TCGA-CM-4746_MSIH — processed 6,726 new (total valid: 6,726)

Slides:  55%|█████▌    | 231/417 [9:49:13<14:21:58, 278.06s/slide]

  ✅  TCGA-CM-4747_nonMSIH — processed 5,154 new (total valid: 5,154)

Slides:  56%|█████▌    | 232/417 [9:54:07<14:31:39, 282.70s/slide]

  ✅  TCGA-CM-4750_nonMSIH — processed 5,961 new (total valid: 5,961)

Slides:  56%|█████▌    | 233/417 [9:57:10<12:55:40, 252.94s/slide]

  ✅  TCGA-CM-4751_nonMSIH — processed 3,518 new (total valid: 3,518)

Slides:  56%|█████▌    | 234/417 [9:59:47<11:23:22, 224.06s/slide]

  ✅  TCGA-CM-4752_nonMSIH — processed 3,129 new (total valid: 3,129)

Slides:  56%|█████▋    | 235/417 [10:02:23<10:17:36, 203.61s/slide]

  ✅  TCGA-CM-5341_nonMSIH — processed 3,227 new (total valid: 3,227)

Slides:  57%|█████▋    | 236/417 [10:06:43<11:05:17, 220.54s/slide]

  ✅  TCGA-CM-5344_nonMSIH — processed 5,293 new (total valid: 5,293)

Slides:  57%|█████▋    | 237/417 [10:10:45<11:20:53, 226.96s/slide]

  ✅  TCGA-CM-5348_nonMSIH — processed 4,744 new (total valid: 4,744)

Slides:  57%|█████▋    | 238/417 [10:15:21<12:01:04, 241.70s/slide]

  ✅  TCGA-CM-5349_nonMSIH — processed 5,613 new (total valid: 5,613)

Slides:  57%|█████▋    | 239/417 [10:18:37<11:16:11, 227.93s/slide]

  ✅  TCGA-CM-5860_nonMSIH — processed 3,995 new (total valid: 3,995)

Slides:  58%|█████▊    | 240/417 [10:21:14<10:09:34, 206.63s/slide]

  ✅  TCGA-CM-5861_MSIH — processed 3,240 new (total valid: 3,240)

Slides:  58%|█████▊    | 241/417 [10:24:30<9:57:22, 203.65s/slide]

  ✅  TCGA-CM-5862_nonMSIH — processed 3,927 new (total valid: 3,927)

Slides:  58%|█████▊    | 242/417 [10:27:28<9:31:16, 195.86s/slide]

  ✅  TCGA-CM-5863_nonMSIH — processed 3,617 new (total valid: 3,617)

Slides:  58%|█████▊    | 243/417 [10:30:44<9:27:44, 195.77s/slide]

  ✅  TCGA-CM-5864_nonMSIH — processed 3,977 new (total valid: 3,977)

Slides:  59%|█████▊    | 244/417 [10:34:40<9:59:50, 208.04s/slide]

  ✅  TCGA-CM-5868_nonMSIH — processed 4,887 new (total valid: 4,887)

Slides:  59%|█████▉    | 245/417 [10:38:45<10:28:19, 219.18s/slide]

  ✅  TCGA-CM-6161_nonMSIH — processed 5,000 new (total valid: 5,000)

Slides:  59%|█████▉    | 246/417 [10:41:47<9:52:12, 207.79s/slide]

  ✅  TCGA-CM-6162_MSIH — processed 3,694 new (total valid: 3,694)

Slides:  59%|█████▉    | 247/417 [10:45:27<9:59:49, 211.70s/slide]

  ✅  TCGA-CM-6163_nonMSIH — processed 4,493 new (total valid: 4,493)

Slides:  59%|█████▉    | 248/417 [10:48:40<9:40:04, 205.95s/slide]

  ✅  TCGA-CM-6164_nonMSIH — processed 3,477 new (total valid: 3,477)

Slides:  60%|█████▉    | 249/417 [10:52:50<10:13:37, 219.15s/slide]

  ✅  TCGA-CM-6165_nonMSIH — processed 4,872 new (total valid: 4,872)

Slides:  60%|█████▉    | 250/417 [10:55:54<9:40:23, 208.52s/slide]

  ✅  TCGA-CM-6166_nonMSIH — processed 3,778 new (total valid: 3,778)

Slides:  60%|██████    | 251/417 [10:59:27<9:41:09, 210.05s/slide]

  ✅  TCGA-CM-6167_nonMSIH — processed 4,465 new (total valid: 4,465)

Slides:  60%|██████    | 252/417 [11:03:46<10:17:46, 224.64s/slide]

  ✅  TCGA-CM-6168_nonMSIH — processed 5,307 new (total valid: 5,307)

Slides:  61%|██████    | 253/417 [11:07:54<10:33:27, 231.75s/slide]

  ✅  TCGA-CM-6169_nonMSIH — processed 4,320 new (total valid: 4,320)

Slides:  61%|██████    | 254/417 [11:09:26<8:35:51, 189.89s/slide]

  ✅  TCGA-CM-6170_nonMSIH — processed 1,972 new (total valid: 1,972)

Slides:  61%|██████    | 255/417 [11:13:48<9:30:43, 211.38s/slide]

  ✅  TCGA-CM-6171_MSIH — processed 4,882 new (total valid: 4,882)

Slides:  61%|██████▏   | 256/417 [11:16:41<8:56:01, 199.76s/slide]

  ✅  TCGA-CM-6172_nonMSIH — processed 3,540 new (total valid: 3,540)

Slides:  62%|██████▏   | 257/417 [11:21:55<10:24:17, 234.11s/slide]

  ✅  TCGA-CM-6674_MSIH — processed 6,370 new (total valid: 6,370)

Slides:  62%|██████▏   | 258/417 [11:26:57<11:14:24, 254.49s/slide]

  ✅  TCGA-CM-6675_nonMSIH — processed 6,130 new (total valid: 6,130)

Slides:  62%|██████▏   | 259/417 [11:29:25<9:46:17, 222.64s/slide]

  ✅  TCGA-CM-6676_nonMSIH — processed 3,001 new (total valid: 3,001)

Slides:  62%|██████▏   | 260/417 [11:33:36<10:04:36, 231.06s/slide]

  ✅  TCGA-CM-6677_nonMSIH — processed 5,032 new (total valid: 5,032)

Slides:  63%|██████▎   | 261/417 [11:35:24<8:24:25, 194.01s/slide]

  ✅  TCGA-CM-6678_nonMSIH — processed 2,203 new (total valid: 2,203)

Slides:  63%|██████▎   | 262/417 [11:39:36<9:06:09, 211.42s/slide]

  ✅  TCGA-CM-6679_nonMSIH — processed 5,165 new (total valid: 5,165)

Slides:  63%|██████▎   | 263/417 [11:42:49<8:48:56, 206.08s/slide]

  ✅  TCGA-D5-5537_nonMSIH — processed 3,768 new (total valid: 3,768)

Slides:  63%|██████▎   | 264/417 [11:46:10<8:41:26, 204.49s/slide]

  ✅  TCGA-D5-5538_nonMSIH — processed 4,156 new (total valid: 4,156)

Slides:  64%|██████▎   | 265/417 [11:47:58<7:24:44, 175.55s/slide]

  ✅  TCGA-D5-5539_nonMSIH — processed 2,166 new (total valid: 2,166)

Slides:  64%|██████▍   | 266/417 [11:49:41<6:26:49, 153.71s/slide]

  ✅  TCGA-D5-5540_nonMSIH — processed 2,090 new (total valid: 2,090)

Slides:  64%|██████▍   | 267/417 [11:52:17<6:26:30, 154.61s/slide]

  ✅  TCGA-D5-5541_nonMSIH — processed 3,224 new (total valid: 3,224)

Slides:  64%|██████▍   | 268/417 [11:54:52<6:23:50, 154.57s/slide]

  ✅  TCGA-D5-6529_nonMSIH — processed 3,153 new (total valid: 3,153)

Slides:  65%|██████▍   | 269/417 [11:59:36<7:57:03, 193.40s/slide]

  ✅  TCGA-D5-6530_MSIH — processed 5,875 new (total valid: 5,875)

Slides:  65%|██████▍   | 270/417 [12:02:55<7:57:56, 195.08s/slide]

  ✅  TCGA-D5-6531_nonMSIH — processed 3,478 new (total valid: 3,478)

Slides:  65%|██████▍   | 271/417 [12:07:06<8:35:49, 211.99s/slide]

  ✅  TCGA-D5-6532_nonMSIH — processed 4,388 new (total valid: 4,388)

Slides:  65%|██████▌   | 272/417 [12:11:06<8:52:38, 220.41s/slide]

  ✅  TCGA-D5-6533_nonMSIH — processed 4,591 new (total valid: 4,591)

Slides:  65%|██████▌   | 273/417 [12:14:17<8:27:46, 211.57s/slide]

  ✅  TCGA-D5-6534_nonMSIH — processed 3,535 new (total valid: 3,535)

Slides:  66%|██████▌   | 274/417 [12:17:08<7:54:52, 199.25s/slide]

  ✅  TCGA-D5-6535_nonMSIH — processed 3,486 new (total valid: 3,486)

Slides:  66%|██████▌   | 275/417 [12:20:20<7:46:37, 197.16s/slide]

  ✅  TCGA-D5-6536_nonMSIH — processed 3,897 new (total valid: 3,897)

Slides:  66%|██████▌   | 276/417 [12:23:16<7:28:16, 190.76s/slide]

  ✅  TCGA-D5-6537_nonMSIH — processed 3,597 new (total valid: 3,597)

Slides:  66%|██████▋   | 277/417 [12:25:58<7:05:01, 182.15s/slide]

  ✅  TCGA-D5-6538_nonMSIH — processed 3,316 new (total valid: 3,316)

Slides:  67%|██████▋   | 278/417 [12:27:40<6:06:21, 158.14s/slide]

  ✅  TCGA-D5-6539_nonMSIH — processed 2,226 new (total valid: 2,226)

Slides:  67%|██████▋   | 279/417 [12:29:49<5:43:43, 149.45s/slide]

  ✅  TCGA-D5-6540_MSIH — processed 2,636 new (total valid: 2,636)

Slides:  67%|██████▋   | 280/417 [12:33:04<6:12:08, 162.98s/slide]

  ✅  TCGA-D5-6541_nonMSIH — processed 3,899 new (total valid: 3,899)

Slides:  67%|██████▋   | 281/417 [12:34:04<4:59:26, 132.10s/slide]

  ✅  TCGA-D5-6898_nonMSIH — processed 1,101 new (total valid: 1,101)

Slides:  68%|██████▊   | 282/417 [12:34:37<3:50:07, 102.27s/slide]

  ✅  TCGA-D5-6920_nonMSIH — processed 666 new (total valid: 666)

Slides:  68%|██████▊   | 283/417 [12:35:30<3:15:51, 87.70s/slide]

  ✅  TCGA-D5-6922_nonMSIH — processed 1,085 new (total valid: 1,085)

Slides:  68%|██████▊   | 284/417 [12:36:34<2:58:38, 80.59s/slide]

  ✅  TCGA-D5-6924_nonMSIH — processed 1,364 new (total valid: 1,364)

Slides:  68%|██████▊   | 285/417 [12:37:40<2:47:10, 75.99s/slide]

  ✅  TCGA-D5-6926_nonMSIH — processed 1,293 new (total valid: 1,293)

Slides:  69%|██████▊   | 286/417 [12:38:45<2:39:02, 72.85s/slide]

  ✅  TCGA-D5-6927_MSIH — processed 1,283 new (total valid: 1,283)

Slides:  69%|██████▉   | 287/417 [12:39:25<2:16:14, 62.88s/slide]

  ✅  TCGA-D5-6928_MSIH — processed 749 new (total valid: 749)

Slides:  69%|██████▉   | 288/417 [12:44:15<4:41:48, 131.07s/slide]

  ✅  TCGA-D5-6929_nonMSIH — processed 5,999 new (total valid: 5,999)

Slides:  69%|██████▉   | 289/417 [12:44:55<3:41:37, 103.89s/slide]

  ✅  TCGA-D5-6930_MSIH — processed 838 new (total valid: 838)

Slides:  70%|██████▉   | 290/417 [12:46:12<3:22:51, 95.84s/slide]

  ✅  TCGA-D5-6931_nonMSIH — processed 1,548 new (total valid: 1,548)

Slides:  70%|██████▉   | 291/417 [12:47:07<2:55:28, 83.56s/slide]

  ✅  TCGA-D5-6932_nonMSIH — processed 1,105 new (total valid: 1,105)

Slides:  70%|███████   | 292/417 [12:47:58<2:33:49, 73.84s/slide]

  ✅  TCGA-D5-7000_nonMSIH — processed 901 new (total valid: 901)

Slides:  70%|███████   | 293/417 [12:50:18<3:13:20, 93.55s/slide]

  ✅  TCGA-DC-4745_nonMSIH — processed 2,817 new (total valid: 2,817)

Slides:  71%|███████   | 294/417 [12:53:21<4:06:34, 120.28s/slide]

  ✅  TCGA-DC-4749_nonMSIH — processed 3,668 new (total valid: 3,668)

Slides:  71%|███████   | 295/417 [12:54:52<3:46:41, 111.49s/slide]

  ✅  TCGA-DC-5337_nonMSIH — processed 1,844 new (total valid: 1,844)

Slides:  71%|███████   | 296/417 [12:59:59<5:43:13, 170.20s/slide]

  ✅  TCGA-DC-5869_nonMSIH — processed 5,883 new (total valid: 5,883)

Slides:  71%|███████   | 297/417 [13:02:22<5:23:55, 161.96s/slide]

  ✅  TCGA-DC-6154_MSIH — processed 2,959 new (total valid: 2,959)

Slides:  71%|███████▏  | 298/417 [13:08:03<7:08:14, 215.92s/slide]

  ✅  TCGA-DC-6155_nonMSIH — processed 7,085 new (total valid: 7,085)

Slides:  72%|███████▏  | 299/417 [13:11:00<6:41:25, 204.12s/slide]

  ✅  TCGA-DC-6157_nonMSIH — processed 3,769 new (total valid: 3,769)

Slides:  72%|███████▏  | 300/417 [13:13:30<6:06:24, 187.91s/slide]

  ✅  TCGA-DC-6158_nonMSIH — processed 3,037 new (total valid: 3,037)

Slides:  72%|███████▏  | 301/417 [13:17:27<6:31:43, 202.61s/slide]

  ✅  TCGA-DC-6160_nonMSIH — processed 4,854 new (total valid: 4,854)

Slides:  72%|███████▏  | 302/417 [13:22:01<7:09:29, 224.09s/slide]

  ✅  TCGA-DC-6681_nonMSIH — processed 5,512 new (total valid: 5,512)

Slides:  73%|███████▎  | 303/417 [13:24:04<6:07:52, 193.62s/slide]

  ✅  TCGA-DC-6682_nonMSIH — processed 2,520 new (total valid: 2,520)

Slides:  73%|███████▎  | 304/417 [13:27:18<6:05:14, 193.94s/slide]

  ✅  TCGA-DC-6683_nonMSIH — processed 3,994 new (total valid: 3,994)

Slides:  73%|███████▎  | 305/417 [13:30:55<6:14:42, 200.73s/slide]

  ✅  TCGA-DM-A0X9_nonMSIH — processed 4,268 new (total valid: 4,268)

Slides:  73%|███████▎  | 306/417 [13:31:38<4:43:35, 153.29s/slide]

  ✅  TCGA-DM-A0XD_nonMSIH — processed 871 new (total valid: 871)

Slides:  74%|███████▎  | 307/417 [13:34:31<4:52:14, 159.40s/slide]

  ✅  TCGA-DM-A0XF_nonMSIH — processed 3,532 new (total valid: 3,532)

Slides:  74%|███████▍  | 308/417 [13:37:50<5:10:52, 171.12s/slide]

  ✅  TCGA-DM-A1D0_nonMSIH — processed 3,947 new (total valid: 3,947)

Slides:  74%|███████▍  | 309/417 [13:40:15<4:54:17, 163.49s/slide]

  ✅  TCGA-DM-A1D4_nonMSIH — processed 2,889 new (total valid: 2,889)

Slides:  74%|███████▍  | 310/417 [13:43:24<5:05:10, 171.12s/slide]

  ✅  TCGA-DM-A1D6_nonMSIH — processed 3,884 new (total valid: 3,884)

Slides:  75%|███████▍  | 311/417 [13:45:47<4:47:11, 162.56s/slide]

  ✅  TCGA-DM-A1D7_nonMSIH — processed 2,645 new (total valid: 2,645)

Slides:  75%|███████▍  | 312/417 [13:47:08<4:01:36, 138.06s/slide]

  ✅  TCGA-DM-A1D8_nonMSIH — processed 1,621 new (total valid: 1,621)

Slides:  75%|███████▌  | 313/417 [13:50:30<4:32:55, 157.45s/slide]

  ✅  TCGA-DM-A1D9_nonMSIH — processed 4,121 new (total valid: 4,121)

Slides:  75%|███████▌  | 314/417 [13:53:48<4:50:53, 169.45s/slide]

  ✅  TCGA-DM-A1DA_nonMSIH — processed 4,014 new (total valid: 4,014)

Slides:  76%|███████▌  | 315/417 [13:58:46<5:53:40, 208.05s/slide]

  ✅  TCGA-DM-A1DB_nonMSIH — processed 5,990 new (total valid: 5,990)

Slides:  76%|███████▌  | 316/417 [14:02:28<5:57:27, 212.35s/slide]

  ✅  TCGA-DM-A1HA_nonMSIH — processed 4,391 new (total valid: 4,391)

Slides:  76%|███████▌  | 317/417 [14:07:56<6:51:29, 246.89s/slide]

  ✅  TCGA-DM-A280_nonMSIH — processed 6,569 new (total valid: 6,569)

Slides:  76%|███████▋  | 318/417 [14:12:20<6:55:39, 251.92s/slide]

  ✅  TCGA-DM-A282_nonMSIH — processed 5,356 new (total valid: 5,356)

Slides:  76%|███████▋  | 319/417 [14:15:17<6:14:49, 229.49s/slide]

  ✅  TCGA-DM-A285_nonMSIH — processed 3,624 new (total valid: 3,624)

Slides:  77%|███████▋  | 320/417 [14:19:43<6:29:03, 240.65s/slide]

  ✅  TCGA-DM-A288_nonMSIH — processed 5,123 new (total valid: 5,123)

Slides:  77%|███████▋  | 321/417 [14:23:07<6:07:15, 229.54s/slide]

  ✅  TCGA-DM-A28A_nonMSIH — processed 4,130 new (total valid: 4,130)

Slides:  77%|███████▋  | 322/417 [14:26:21<5:46:33, 218.88s/slide]

  ✅  TCGA-DM-A28E_nonMSIH — processed 3,894 new (total valid: 3,894)

Slides:  77%|███████▋  | 323/417 [14:28:41<5:05:40, 195.12s/slide]

  ✅  TCGA-DM-A28F_nonMSIH — processed 2,832 new (total valid: 2,832)

Slides:  78%|███████▊  | 324/417 [14:32:10<5:09:00, 199.36s/slide]

  ✅  TCGA-DM-A28G_nonMSIH — processed 4,241 new (total valid: 4,241)

Slides:  78%|███████▊  | 325/417 [14:35:36<5:08:44, 201.35s/slide]

  ✅  TCGA-DM-A28H_nonMSIH — processed 3,768 new (total valid: 3,768)

Slides:  78%|███████▊  | 326/417 [14:40:26<5:45:46, 227.98s/slide]

  ✅  TCGA-DM-A28K_nonMSIH — processed 5,424 new (total valid: 5,424)

Slides:  78%|███████▊  | 327/417 [14:43:59<5:35:17, 223.52s/slide]

  ✅  TCGA-DM-A28M_nonMSIH — processed 4,345 new (total valid: 4,345)

Slides:  79%|███████▊  | 328/417 [14:45:35<4:34:57, 185.36s/slide]

  ✅  TCGA-DT-5265_nonMSIH — processed 1,957 new (total valid: 1,957)

Slides:  79%|███████▉  | 329/417 [14:50:02<5:07:32, 209.69s/slide]

  ✅  TCGA-DY-A0XA_nonMSIH — processed 5,433 new (total valid: 5,433)

Slides:  79%|███████▉  | 330/417 [14:52:35<4:39:37, 192.85s/slide]

  ✅  TCGA-DY-A1DC_nonMSIH — processed 3,142 new (total valid: 3,142)

Slides:  79%|███████▉  | 331/417 [14:56:25<4:52:19, 203.94s/slide]

  ✅  TCGA-DY-A1DD_nonMSIH — processed 4,682 new (total valid: 4,682)

Slides:  80%|███████▉  | 332/417 [14:58:27<4:13:49, 179.18s/slide]

  ✅  TCGA-DY-A1DF_nonMSIH — processed 2,464 new (total valid: 2,464)

Slides:  80%|███████▉  | 333/417 [15:02:00<4:25:08, 189.39s/slide]

  ✅  TCGA-DY-A1DG_nonMSIH — processed 4,409 new (total valid: 4,409)

Slides:  80%|████████  | 334/417 [15:04:21<4:01:51, 174.84s/slide]

  ✅  TCGA-EF-5830_nonMSIH — processed 2,809 new (total valid: 2,809)

Slides:  80%|████████  | 335/417 [15:06:42<3:45:01, 164.65s/slide]

  ✅  TCGA-EI-6506_nonMSIH — processed 2,451 new (total valid: 2,451)

Slides:  81%|████████  | 336/417 [15:09:23<3:40:48, 163.56s/slide]

  ✅  TCGA-EI-6507_MSIH — processed 3,267 new (total valid: 3,267)

Slides:  81%|████████  | 337/417 [15:11:59<3:35:18, 161.48s/slide]

  ✅  TCGA-EI-6508_nonMSIH — processed 3,269 new (total valid: 3,269)

Slides:  81%|████████  | 338/417 [15:13:36<3:06:54, 141.95s/slide]

  ✅  TCGA-EI-6509_nonMSIH — processed 1,927 new (total valid: 1,927)

Slides:  81%|████████▏ | 339/417 [15:16:01<3:05:41, 142.84s/slide]

  ✅  TCGA-EI-6510_nonMSIH — processed 2,982 new (total valid: 2,982)

Slides:  82%|████████▏ | 340/417 [15:19:21<3:25:39, 160.25s/slide]

  ✅  TCGA-EI-6511_nonMSIH — processed 4,146 new (total valid: 4,146)

Slides:  82%|████████▏ | 341/417 [15:23:22<3:53:19, 184.20s/slide]

  ✅  TCGA-EI-6512_nonMSIH — processed 4,880 new (total valid: 4,880)

Slides:  82%|████████▏ | 342/417 [15:27:38<4:17:21, 205.88s/slide]

  ✅  TCGA-EI-6513_nonMSIH — processed 5,185 new (total valid: 5,185)

Slides:  82%|████████▏ | 343/417 [15:30:36<4:03:25, 197.37s/slide]

  ✅  TCGA-EI-6514_nonMSIH — processed 3,295 new (total valid: 3,295)

Slides:  82%|████████▏ | 344/417 [15:31:05<2:58:51, 147.01s/slide]

  ✅  TCGA-EI-6881_nonMSIH — processed 558 new (total valid: 558)

Slides:  83%|████████▎ | 345/417 [15:32:18<2:29:47, 124.82s/slide]

  ✅  TCGA-EI-6882_MSIH — processed 1,532 new (total valid: 1,532)

Slides:  83%|████████▎ | 346/417 [15:34:27<2:29:11, 126.07s/slide]

  ✅  TCGA-EI-6883_nonMSIH — processed 2,572 new (total valid: 2,572)

Slides:  83%|████████▎ | 347/417 [15:35:23<2:02:28, 104.98s/slide]

  ✅  TCGA-EI-6884_nonMSIH — processed 1,122 new (total valid: 1,122)

Slides:  83%|████████▎ | 348/417 [15:36:20<1:44:03, 90.49s/slide]

  ✅  TCGA-EI-6885_nonMSIH — processed 1,210 new (total valid: 1,210)

Slides:  84%|████████▎ | 349/417 [15:37:10<1:29:05, 78.61s/slide]

  ✅  TCGA-EI-6917_nonMSIH — processed 1,011 new (total valid: 1,011)

Slides:  84%|████████▍ | 350/417 [15:38:09<1:21:09, 72.68s/slide]

  ✅  TCGA-EI-7002_nonMSIH — processed 1,094 new (total valid: 1,094)

Slides:  84%|████████▍ | 351/417 [15:38:50<1:09:27, 63.15s/slide]

  ✅  TCGA-EI-7004_nonMSIH — processed 805 new (total valid: 805)

Slides:  84%|████████▍ | 352/417 [15:43:00<2:08:55, 119.02s/slide]

  ✅  TCGA-F4-6459_nonMSIH — processed 4,979 new (total valid: 4,979)

Slides:  85%|████████▍ | 353/417 [15:46:06<2:28:34, 139.29s/slide]

  ✅  TCGA-F4-6460_nonMSIH — processed 3,799 new (total valid: 3,799)

Slides:  85%|████████▍ | 354/417 [15:50:24<3:03:27, 174.72s/slide]

  ✅  TCGA-F4-6461_nonMSIH — processed 5,239 new (total valid: 5,239)

Slides:  85%|████████▌ | 355/417 [15:51:37<2:28:59, 144.19s/slide]

  ✅  TCGA-F4-6463_nonMSIH — processed 1,457 new (total valid: 1,457)

Slides:  85%|████████▌ | 356/417 [15:53:35<2:18:36, 136.34s/slide]

  ✅  TCGA-F4-6569_nonMSIH — processed 2,382 new (total valid: 2,382)

Slides:  86%|████████▌ | 357/417 [15:56:04<2:20:14, 140.25s/slide]

  ✅  TCGA-F4-6570_MSIH — processed 2,990 new (total valid: 2,990)

Slides:  86%|████████▌ | 358/417 [15:58:24<2:17:53, 140.22s/slide]

  ✅  TCGA-F4-6703_MSIH — processed 2,872 new (total valid: 2,872)

Slides:  86%|████████▌ | 359/417 [15:59:59<2:02:17, 126.51s/slide]

  ✅  TCGA-F4-6704_nonMSIH — processed 1,861 new (total valid: 1,861)

Slides:  86%|████████▋ | 360/417 [16:02:19<2:04:02, 130.57s/slide]

  ✅  TCGA-F4-6805_nonMSIH — processed 2,757 new (total valid: 2,757)

Slides:  87%|████████▋ | 361/417 [16:05:45<2:23:10, 153.40s/slide]

  ✅  TCGA-F4-6806_nonMSIH — processed 4,081 new (total valid: 4,081)

Slides:  87%|████████▋ | 362/417 [16:09:55<2:47:13, 182.43s/slide]

  ✅  TCGA-F4-6807_nonMSIH — processed 4,940 new (total valid: 4,940)

Slides:  87%|████████▋ | 363/417 [16:14:11<3:03:53, 204.33s/slide]

  ✅  TCGA-F4-6808_nonMSIH — processed 5,017 new (total valid: 5,017)

Slides:  87%|████████▋ | 364/417 [16:17:57<3:06:16, 210.88s/slide]

  ✅  TCGA-F4-6809_nonMSIH — processed 4,583 new (total valid: 4,583)

Slides:  88%|████████▊ | 365/417 [16:19:43<2:35:32, 179.47s/slide]

  ✅  TCGA-F4-6854_nonMSIH — processed 2,125 new (total valid: 2,125)

Slides:  88%|████████▊ | 366/417 [16:20:43<2:02:04, 143.61s/slide]

  ✅  TCGA-F4-6855_nonMSIH — processed 1,096 new (total valid: 1,096)

Slides:  88%|████████▊ | 367/417 [16:23:43<2:08:42, 154.45s/slide]

  ✅  TCGA-F4-6856_MSIH — processed 3,617 new (total valid: 3,617)

Slides:  88%|████████▊ | 368/417 [16:26:39<2:11:26, 160.96s/slide]

  ✅  TCGA-F5-6464_nonMSIH — processed 3,610 new (total valid: 3,610)

Slides:  88%|████████▊ | 369/417 [16:29:06<2:05:18, 156.63s/slide]

  ✅  TCGA-F5-6465_nonMSIH — processed 2,560 new (total valid: 2,560)

Slides:  89%|████████▊ | 370/417 [16:32:24<2:12:31, 169.17s/slide]

  ✅  TCGA-F5-6571_nonMSIH — processed 4,197 new (total valid: 4,197)

Slides:  89%|████████▉ | 371/417 [16:34:17<1:56:44, 152.27s/slide]

  ✅  TCGA-F5-6702_nonMSIH — processed 2,271 new (total valid: 2,271)

Slides:  89%|████████▉ | 372/417 [16:34:55<1:28:25, 117.90s/slide]

  ✅  TCGA-F5-6811_nonMSIH — processed 691 new (total valid: 691)

Slides:  89%|████████▉ | 373/417 [16:38:03<1:41:52, 138.92s/slide]

  ✅  TCGA-F5-6814_nonMSIH — processed 3,682 new (total valid: 3,682)

Slides:  90%|████████▉ | 374/417 [16:40:33<1:42:00, 142.34s/slide]

  ✅  TCGA-F5-6863_nonMSIH — processed 2,985 new (total valid: 2,985)

Slides:  90%|████████▉ | 375/417 [16:42:17<1:31:41, 130.99s/slide]

  ✅  TCGA-F5-6864_nonMSIH — processed 1,995 new (total valid: 1,995)

Slides:  90%|█████████ | 376/417 [16:45:01<1:36:06, 140.65s/slide]

  ✅  TCGA-G4-6293_nonMSIH — processed 3,430 new (total valid: 3,430)

Slides:  90%|█████████ | 377/417 [16:48:57<1:52:58, 169.47s/slide]

  ✅  TCGA-G4-6294_nonMSIH — processed 4,722 new (total valid: 4,722)

Slides:  91%|█████████ | 378/417 [16:51:57<1:52:06, 172.49s/slide]

  ✅  TCGA-G4-6295_nonMSIH — processed 3,726 new (total valid: 3,726)

Slides:  91%|█████████ | 379/417 [16:56:08<2:04:15, 196.19s/slide]

  ✅  TCGA-G4-6297_nonMSIH — processed 5,139 new (total valid: 5,139)

Slides:  91%|█████████ | 380/417 [17:01:06<2:19:49, 226.74s/slide]

  ✅  TCGA-G4-6298_nonMSIH — processed 6,051 new (total valid: 6,051)

Slides:  91%|█████████▏| 381/417 [17:04:50<2:15:26, 225.74s/slide]

  ✅  TCGA-G4-6299_nonMSIH — processed 4,570 new (total valid: 4,570)

Slides:  92%|█████████▏| 382/417 [17:07:11<1:56:54, 200.42s/slide]

  ✅  TCGA-G4-6302_MSIH — processed 3,046 new (total valid: 3,046)

Slides:  92%|█████████▏| 383/417 [17:09:18<1:41:08, 178.50s/slide]

  ✅  TCGA-G4-6303_nonMSIH — processed 2,575 new (total valid: 2,575)

Slides:  92%|█████████▏| 384/417 [17:14:19<1:58:16, 215.04s/slide]

  ✅  TCGA-G4-6304_MSIH — processed 6,078 new (total valid: 6,078)

Slides:  92%|█████████▏| 385/417 [17:17:13<1:48:10, 202.83s/slide]

  ✅  TCGA-G4-6306_nonMSIH — processed 3,570 new (total valid: 3,570)

Slides:  93%|█████████▎| 386/417 [17:20:19<1:42:11, 197.80s/slide]

  ✅  TCGA-G4-6307_nonMSIH — processed 3,781 new (total valid: 3,781)

Slides:  93%|█████████▎| 387/417 [17:23:21<1:36:29, 192.99s/slide]

  ✅  TCGA-G4-6309_MSIH — processed 3,701 new (total valid: 3,701)

Slides:  93%|█████████▎| 388/417 [17:26:01<1:28:30, 183.13s/slide]

  ✅  TCGA-G4-6311_nonMSIH — processed 3,294 new (total valid: 3,294)

Slides:  93%|█████████▎| 389/417 [17:29:41<1:30:36, 194.15s/slide]

  ✅  TCGA-G4-6315_nonMSIH — processed 4,405 new (total valid: 4,405)

Slides:  94%|█████████▎| 390/417 [17:32:45<1:26:04, 191.28s/slide]

  ✅  TCGA-G4-6317_nonMSIH — processed 3,555 new (total valid: 3,555)

Slides:  94%|█████████▍| 391/417 [17:35:23<1:18:33, 181.28s/slide]

  ✅  TCGA-G4-6320_MSIH — processed 2,886 new (total valid: 2,886)

Slides:  94%|█████████▍| 392/417 [17:37:57<1:12:04, 172.97s/slide]

  ✅  TCGA-G4-6321_nonMSIH — processed 2,814 new (total valid: 2,814)

Slides:  94%|█████████▍| 393/417 [17:41:55<1:16:57, 192.38s/slide]

  ✅  TCGA-G4-6322_nonMSIH — processed 4,860 new (total valid: 4,860)

Slides:  94%|█████████▍| 394/417 [17:44:03<1:06:25, 173.29s/slide]

  ✅  TCGA-G4-6323_nonMSIH — processed 2,648 new (total valid: 2,648)

Slides:  95%|█████████▍| 395/417 [17:47:08<1:04:44, 176.58s/slide]

  ✅  TCGA-G4-6586_MSIH — processed 3,761 new (total valid: 3,761)

Slides:  95%|█████████▍| 396/417 [17:50:38<1:05:21, 186.73s/slide]

  ✅  TCGA-G4-6588_MSIH — processed 4,272 new (total valid: 4,272)

Slides:  95%|█████████▌| 397/417 [17:53:01<57:50, 173.50s/slide]

  ✅  TCGA-G4-6626_nonMSIH — processed 3,020 new (total valid: 3,020)

Slides:  95%|█████████▌| 398/417 [17:57:36<1:04:37, 204.08s/slide]

  ✅  TCGA-G4-6627_nonMSIH — processed 4,823 new (total valid: 4,823)

Slides:  96%|█████████▌| 399/417 [18:01:27<1:03:35, 211.99s/slide]

  ✅  TCGA-G4-6628_MSIH — processed 4,592 new (total valid: 4,592)

Slides:  96%|█████████▌| 400/417 [18:03:26<52:12, 184.29s/slide]

  ✅  TCGA-G5-6641_nonMSIH — processed 2,376 new (total valid: 2,376)

Slides:  96%|█████████▌| 401/417 [18:07:37<54:27, 204.24s/slide]

  ✅  TCGA-NH-A50T_nonMSIH — processed 4,445 new (total valid: 4,445)

Slides:  96%|█████████▋| 402/417 [18:10:52<50:20, 201.38s/slide]

  ✅  TCGA-NH-A50U_nonMSIH — processed 3,411 new (total valid: 3,411)

Slides:  97%|█████████▋| 403/417 [18:14:19<47:25, 203.24s/slide]

  ✅  TCGA-NH-A50V_nonMSIH — processed 4,077 new (total valid: 4,077)

Slides:  97%|█████████▋| 404/417 [18:18:20<46:26, 214.37s/slide]

  ✅  TCGA-NH-A5IV_MSIH — processed 4,738 new (total valid: 4,738)

Slides:  97%|█████████▋| 405/417 [18:20:41<38:28, 192.41s/slide]

  ✅  TCGA-NH-A6GA_nonMSIH — processed 2,918 new (total valid: 2,918)

Slides:  97%|█████████▋| 406/417 [18:25:11<39:32, 215.69s/slide]

  ✅  TCGA-NH-A6GB_nonMSIH — processed 5,249 new (total valid: 5,249)

Slides:  98%|█████████▊| 407/417 [18:28:32<35:13, 211.32s/slide]

  ✅  TCGA-NH-A6GC_nonMSIH — processed 4,013 new (total valid: 4,013)

Slides:  98%|█████████▊| 408/417 [18:32:16<32:15, 215.10s/slide]

  ✅  TCGA-NH-A8F8_nonMSIH — processed 4,086 new (total valid: 4,086)

Slides:  98%|█████████▊| 409/417 [18:36:57<31:18, 234.79s/slide]

  ✅  TCGA-QG-A5YV_nonMSIH — processed 4,699 new (total valid: 4,699)

Slides:  98%|█████████▊| 410/417 [18:40:35<26:48, 229.76s/slide]

  ✅  TCGA-QG-A5YW_nonMSIH — processed 3,628 new (total valid: 3,628)

Slides:  99%|█████████▊| 411/417 [18:43:43<21:44, 217.47s/slide]

  ✅  TCGA-QG-A5YX_nonMSIH — processed 3,727 new (total valid: 3,727)

Slides:  99%|█████████▉| 412/417 [18:47:10<17:51, 214.28s/slide]

  ✅  TCGA-QG-A5Z1_nonMSIH — processed 4,144 new (total valid: 4,144)

Slides:  99%|█████████▉| 413/417 [18:51:14<14:52, 223.06s/slide]

  ✅  TCGA-QG-A5Z2_MSIH — processed 4,849 new (total valid: 4,849)

Slides:  99%|█████████▉| 414/417 [18:54:41<10:55, 218.45s/slide]

  ✅  TCGA-QL-A97D_nonMSIH — processed 4,126 new (total valid: 4,126)

Slides: 100%|█████████▉| 415/417 [18:59:33<08:00, 240.26s/slide]

  ✅  TCGA-SS-A7HO_nonMSIH — processed 5,746 new (total valid: 5,746)

Slides: 100%|█████████▉| 416/417 [19:03:57<04:07, 247.35s/slide]

  ✅  TCGA-T9-A92H_nonMSIH — processed 5,462 new (total valid: 5,462)

Slides: 100%|██████████| 417/417 [19:08:21<00:00, 165.23s/slide]

  ✅  TCGA-WS-AB45_MSIH — processed 4,532 new (total valid: 4,532)

In [4]:
extractor = Virchow2ExtractorCrops(device='cuda')

run_full_pipeline_Virchow2_crops(
    patch_data_dir = r"D:\Aamir Gulzar\KSA_project2\paip_data\patch_data",
    extractor      = extractor,
    non_white_csv  = r"D:\Aamir Gulzar\KSA_project2\paip_data\final_merged_without_white.csv",
    output_root    = r"D:\Aamir Gulzar\KSA_project2\paip_data\Features\Virchow2_fivecrop_Updated",
    mode           = "fivecrop",     # switch to "fivecrop" if needed
)

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to C:\Users\datainsight\.cache\huggingface\token
Login successful
[Virchow2] Loading model on cuda ...
[Virchow2] Model loaded ✓
[Pipeline] Valid patches in CSV : 271,322
[Pipeline] Mode                 : fivecrop
[Pipeline] Output root          : D:\Aamir Gulzar\KSA_project2\paip_data\Features\Virchow2_fivecrop_Updated

Slides:   3%|▎         | 2/73 [00:00<00:03, 19.32slide/s]

  ⏭️  Skipped training_data_01_MSIH (3,196 patches already done)
  ⏭️  Skipped training_data_02_nonMSIH (4,412 patches already done)
  ⏭️  Skipped training_data_03_nonMSIH (1,955 patches already done)

Slides:   3%|▎         | 2/73 [00:00<00:03, 19.32slide/s]

  ⏭️  Skipped training_data_04_nonMSIH (3,198 patches already done)

Slides:  12%|█▏        | 9/73 [00:00<00:02, 27.10slide/s]

  ⏭️  Skipped training_data_05_MSIH (4,073 patches already done)
  ⏭️  Skipped training_data_06_MSIH (3,776 patches already done)
  ⏭️  Skipped training_data_07_nonMSIH (2,740 patches already done)
  ⏭️  Skipped training_data_08_nonMSIH (51 patches already done)
  ⏭️  Skipped training_data_09_nonMSIH (2,248 patches already done)

Slides:  12%|█▏        | 9/73 [00:00<00:02, 27.10slide/s]

  ⏭️  Skipped training_data_10_nonMSIH (2,452 patches already done)

Slides:  16%|█▋        | 12/73 [00:00<00:02, 24.60slide/s]

  ⏭️  Skipped training_data_11_nonMSIH (2,893 patches already done)
  ⏭️  Skipped training_data_12_MSIH (4,691 patches already done)
  ⏭️  Skipped training_data_13_nonMSIH (5,530 patches already done)

Slides:  21%|██        | 15/73 [00:00<00:02, 21.73slide/s]

  ⏭️  Skipped training_data_14_nonMSIH (2,674 patches already done)
  ⏭️  Skipped training_data_15_nonMSIH (3,834 patches already done)
  ⏭️  Skipped training_data_16_nonMSIH (3,018 patches already done)
  ⏭️  Skipped training_data_17_nonMSIH (3,437 patches already done)

Slides:  29%|██▉       | 21/73 [00:00<00:02, 21.10slide/s]

  ⏭️  Skipped training_data_18_nonMSIH (4,191 patches already done)
  ⏭️  Skipped training_data_20_MSIH (3,281 patches already done)
  ⏭️  Skipped training_data_21_nonMSIH (3,021 patches already done)
  ⏭️  Skipped training_data_22_nonMSIH (3,422 patches already done)
  ⏭️  Skipped training_data_23_nonMSIH (2,358 patches already done)

Slides:  33%|███▎      | 24/73 [00:01<00:02, 20.41slide/s]

  ⏭️  Skipped training_data_24_MSIH (4,756 patches already done)
  ⏭️  Skipped training_data_25_nonMSIH (4,176 patches already done)
  ⏭️  Skipped training_data_26_nonMSIH (3,518 patches already done)
  ⏭️  Skipped training_data_27_nonMSIH (4,206 patches already done)

Slides:  41%|████      | 30/73 [00:01<00:02, 19.80slide/s]

  ⏭️  Skipped training_data_28_nonMSIH (3,452 patches already done)
  ⏭️  Skipped training_data_29_nonMSIH (1,528 patches already done)
  ⏭️  Skipped training_data_31_nonMSIH (6,026 patches already done)
  ⏭️  Skipped training_data_32_MSIH (3,576 patches already done)

Slides:  47%|████▋     | 34/73 [00:01<00:01, 19.67slide/s]

  ⏭️  Skipped training_data_33_nonMSIH (3,912 patches already done)
  ⏭️  Skipped training_data_34_MSIH (3,547 patches already done)
  ⏭️  Skipped training_data_35_nonMSIH (4,217 patches already done)
  ⏭️  Skipped training_data_36_nonMSIH (3,239 patches already done)

Slides:  53%|█████▎    | 39/73 [00:01<00:01, 21.53slide/s]

  ⏭️  Skipped training_data_37_nonMSIH (3,189 patches already done)
  ⏭️  Skipped training_data_38_nonMSIH (5,119 patches already done)
  ⏭️  Skipped training_data_39_nonMSIH (2,877 patches already done)
  ⏭️  Skipped training_data_40_nonMSIH (1,811 patches already done)
  ⏭️  Skipped training_data_43_nonMSIH (2,633 patches already done)

Slides:  58%|█████▊    | 42/73 [00:02<00:01, 20.49slide/s]

  ⏭️  Skipped training_data_44_MSIH (4,286 patches already done)
  ⏭️  Skipped training_data_45_nonMSIH (1,395 patches already done)
  ⏭️  Skipped training_data_47_MSIH (6,260 patches already done)

Slides:  62%|██████▏   | 45/73 [00:02<00:01, 17.97slide/s]

  ⏭️  Skipped validation_data_01_nonMSIH (6,735 patches already done)
  ⏭️  Skipped validation_data_02_MSIH (5,694 patches already done)
  ⏭️  Skipped validation_data_03_nonMSIH (2,794 patches already done)

Slides:  64%|██████▍   | 47/73 [00:02<00:01, 16.87slide/s]

  ⏭️  Skipped validation_data_04_MSIH (5,889 patches already done)
  ⏭️  Skipped validation_data_05_nonMSIH (4,644 patches already done)
  ⏭️  Skipped validation_data_06_nonMSIH (4,071 patches already done)
  ⏭️  Skipped validation_data_07_nonMSIH (2,791 patches already done)

Slides:  73%|███████▎  | 53/73 [00:02<00:00, 20.35slide/s]

  ⏭️  Skipped validation_data_08_nonMSIH (2,181 patches already done)
  ⏭️  Skipped validation_data_09_nonMSIH (2,040 patches already done)
  ⏭️  Skipped validation_data_10_nonMSIH (2,922 patches already done)
  ⏭️  Skipped validation_data_11_MSIH (3,461 patches already done)

Slides:  77%|███████▋  | 56/73 [00:02<00:00, 18.54slide/s]

  ⏭️  Skipped validation_data_12_nonMSIH (5,500 patches already done)
  ⏭️  Skipped validation_data_13_nonMSIH (5,546 patches already done)
  ⏭️  Skipped validation_data_14_nonMSIH (2,596 patches already done)

Slides:  79%|███████▉  | 58/73 [00:02<00:00, 17.84slide/s]

  ⏭️  Skipped validation_data_15_MSIH (6,129 patches already done)
  ⏭️  Skipped validation_data_16_nonMSIH (3,021 patches already done)
  ⏭️  Skipped validation_data_17_nonMSIH (3,053 patches already done)

Slides:  86%|████████▋ | 63/73 [00:03<00:00, 18.25slide/s]

  ⏭️  Skipped validation_data_18_nonMSIH (5,542 patches already done)
  ⏭️  Skipped validation_data_19_nonMSIH (1,971 patches already done)
  ⏭️  Skipped validation_data_20_nonMSIH (3,353 patches already done)
  ⏭️  Skipped validation_data_21_nonMSIH (4,186 patches already done)
  ⏭️  Skipped validation_data_22_nonMSIH (2,007 patches already done)

Slides:  93%|█████████▎| 68/73 [00:03<00:00, 19.86slide/s]

  ⏭️  Skipped validation_data_23_nonMSIH (5,598 patches already done)
  ⏭️  Skipped validation_data_24_nonMSIH (2,133 patches already done)
  ⏭️  Skipped validation_data_25_nonMSIH (4,364 patches already done)
  ⏭️  Skipped validation_data_26_nonMSIH (2,417 patches already done)

Slides:  93%|█████████▎| 68/73 [00:03<00:00, 19.86slide/s]

  ⏭️  Skipped validation_data_27_MSIH (5,959 patches already done)

c:\Users\datainsight\anaconda3\envs\exaonepath\lib\site-packages\timm\layers\attention.py:80: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  x = F.scaled_dot_product_attention(
Slides:  96%|█████████▌| 70/73 [02:33<00:56, 18.73s/slide]

  ✅  validation_data_28_MSIH — processed 2,502 new (total valid: 7,452)

Slides:  97%|█████████▋| 71/73 [06:38<01:45, 52.91s/slide]

  ✅  validation_data_29_MSIH — processed 4,171 new (total valid: 4,171)

Slides:  99%|█████████▊| 72/73 [10:36<01:25, 85.60s/slide]

  ✅  validation_data_30_nonMSIH — processed 4,118 new (total valid: 4,118)

Slides: 100%|██████████| 73/73 [15:01<00:00, 12.34s/slide]

  ✅  validation_data_31_nonMSIH — processed 4,810 new (total valid: 4,810)

In [1]:
# ─────────────────────────────────────────────────────────────────────────────
# CELL — Environment Compatibility Check for Virchow2
# Run this in your existing environment BEFORE running Virchow2
# ─────────────────────────────────────────────────────────────────────────────
import importlib, subprocess, sys

def check(pkg, import_name=None):
    import_name = import_name or pkg
    try:
        mod = importlib.import_module(import_name)
        version = getattr(mod, "__version__", "unknown")
        print(f"  ✓  {pkg:<20} {version}")
        return True
    except ImportError:
        print(f"  ✗  {pkg:<20} NOT FOUND")
        return False

print("=" * 45)
print("  Virchow2 Environment Check")
print("=" * 45)

ok_torch = check("torch")
ok_timm  = check("timm")
ok_hf    = check("huggingface_hub")
check("torchvision")
check("PIL", "PIL")

# Extra: check timm version is >= 0.9.11 (required by Virchow2 model card)
import timm
from packaging import version
timm_ok = version.parse(timm.__version__) >= version.parse("0.9.11")
print(f"\n  timm >= 0.9.11 required   → {'✓ OK' if timm_ok else '✗ UPGRADE NEEDED: pip install timm --upgrade'}")

# Check SwiGLUPacked is available (key Virchow2 dependency)
try:
    from timm.layers import SwiGLUPacked
    print(f"  SwiGLUPacked available    → ✓ OK")
except ImportError:
    print(f"  SwiGLUPacked available    → ✗ NOT FOUND — upgrade timm: pip install timm --upgrade")

# Check CUDA
import torch
print(f"\n  CUDA available            → {'✓  ' + torch.cuda.get_device_name(0) if torch.cuda.is_available() else '✗  CPU only'}")
print(f"  PyTorch version           → {torch.__version__}")

print("\n" + "=" * 45)
if timm_ok:
    print("  ✅  Your environment is ready for Virchow2.")
    print("  No new environment needed.")
else:
    print("  ⚠️  Run:  pip install timm --upgrade")
    print("  Then re-run this cell to confirm.")
print("=" * 45)

=============================================
  Virchow2 Environment Check
=============================================
  ✓  torch                2.2.0
  ✓  timm                 1.0.17
  ✓  huggingface_hub      0.23.4
  ✓  torchvision          0.17.0
  ✓  PIL                  10.0.1

  timm >= 0.9.11 required   → ✓ OK
  SwiGLUPacked available    → ✓ OK

  CUDA available            → ✓  NVIDIA GeForce RTX 4090
  PyTorch version           → 2.2.0

=============================================
  ✅  Your environment is ready for Virchow2.
  No new environment needed.
=============================================

In [5]:
import torch
import random
from pathlib import Path

# ─── CONFIG ───────────────────────────────────────────────────────────────────
FEATURE_DIR = r"D:\Aamir Gulzar\KSA_project2\paip_data\Features\Virchow2_fivecrop_Updated"
N_SAMPLES   = 10   # how many random files to peek at
# ──────────────────────────────────────────────────────────────────────────────

all_files = list(Path(FEATURE_DIR).rglob("*.pt"))
sampled   = random.sample(all_files, min(N_SAMPLES, len(all_files)))

print(f"{'File':<60} {'Shape':<15} {'Crops'}")
print("─" * 90)
for path in sampled:
    tensor = torch.load(path, map_location="cpu", weights_only=True)
    crops  = "FiveCrop" if tensor.shape[0] == 5 else "TenCrop" if tensor.shape[0] == 10 else "Unknown"
    print(f"{path.name:<60} {str(tuple(tensor.shape)):<15} {crops}")
# ```

# **Output looks like:**
# ```
# File                                                         Shape           Crops
# ──────────────────────────────────────────────────────────────────────────────────────────
# patch_00123.pt                                               (5, 2560)       FiveCrop
# patch_00456.pt                                               (5, 2560)       FiveCrop
# ...
# ```

# ---

# ## Without Code

# Yes! Just open **Windows Explorer**, navigate to your feature folder, and open any `.pt` file is **not** human readable. But you can check **file size** instead:
# ```
# FiveCrop  (5, 2560)  float32 → 5  × 2560 × 4 bytes ≈  51 KB
# TenCrop  (10, 2560)  float32 → 10 × 2560 × 4 bytes ≈ 102 KB

File                                                         Shape           Crops
──────────────────────────────────────────────────────────────────────────────────────────
training_data_07_nonMSIH_x43088_y20721_patch02493.pt         (5, 2560)       FiveCrop
training_data_18_nonMSIH_x21248_y0_patch02204.pt             (5, 2560)       FiveCrop
training_data_14_nonMSIH_x31232_y33028_patch02103.pt         (5, 2560)       FiveCrop
training_data_14_nonMSIH_x35840_y30980_patch02332.pt         (5, 2560)       FiveCrop
training_data_31_nonMSIH_x42048_y11776_patch05376.pt         (5, 2560)       FiveCrop
validation_data_18_nonMSIH_x18305_y17408_patch00554.pt       (5, 2560)       FiveCrop
validation_data_12_nonMSIH_x10064_y28784_patch00915.pt       (5, 2560)       FiveCrop
training_data_40_nonMSIH_x40528_y36242_patch01454.pt         (5, 2560)       FiveCrop
validation_data_01_nonMSIH_x39504_y13824_patch04940.pt       (5, 2560)       FiveCrop
training_data_43_nonMSIH_x42736_y13810_patch01750.pt         (5, 2560)       FiveCrop

In [8]:
import torch
import random
from pathlib import Path
from tqdm import tqdm
import pandas as pd
from collections import Counter
from IPython.display import display

# ─── CONFIG ───────────────────────────────────────────────────────────────────
AGG_DIR        = r"D:\Aamir Gulzar\KSA_project2\paip_data\slide_aggregation\Caption_based_aggregation\Virchow2"
EXPECTED_SHAPE = torch.Size([14, 2560])
FEATURE_DIM    = 2560
SAMPLE_RATE    = 1.0        # 1.0 = check ALL files
all_groups     = ['ADI', 'DEB', 'LYM', 'PLC', 'LYA', 'MUC', 'MUS', 'NORM',
                  'ADE', 'STR', 'MES', 'CAR', 'PDC', 'SIG']
# ──────────────────────────────────────────────────────────────────────────────

def validate_aggregated_file(path: Path) -> dict:
    result = {
        "file"         : path.name,
        "slide_name"   : path.stem,
        "ok"           : False,
        "error"        : None,
        "shape"        : None,
        "dtype"        : None,
        "file_size_kb" : round(path.stat().st_size / 1024, 2),
        "has_nan"      : False,
        "has_inf"      : False,
        "n_zero_rows"  : 0,
        "zero_groups"  : [],
        "min"          : None,
        "max"          : None,
        "mean"         : None,
        "std"          : None,
    }

    try:
        tensor = torch.load(path, map_location="cpu", weights_only=True)

        # ── 1. Must be a tensor ───────────────────────────────────────────────
        if not isinstance(tensor, torch.Tensor):
            result["error"] = f"Not a tensor: {type(tensor)}"
            return result

        result["shape"] = tuple(tensor.shape)
        result["dtype"] = str(tensor.dtype)

        # ── 2. Shape must be (14, 2560) ───────────────────────────────────────
        if tensor.shape != EXPECTED_SHAPE:
            result["error"] = f"Wrong shape {tuple(tensor.shape)}, expected {tuple(EXPECTED_SHAPE)}"
            return result

        t = tensor.float()

        # ── 3. NaN / Inf ──────────────────────────────────────────────────────
        result["has_nan"] = bool(torch.isnan(t).any())
        result["has_inf"] = bool(torch.isinf(t).any())

        if result["has_nan"]:
            result["error"] = "Contains NaN"
            return result
        if result["has_inf"]:
            result["error"] = "Contains Inf"
            return result

        # ── 4. Per-row (per-group) zero check ─────────────────────────────────
        zero_mask             = (t == 0).all(dim=1)
        zero_indices          = zero_mask.nonzero(as_tuple=True)[0].tolist()
        result["n_zero_rows"] = len(zero_indices)
        result["zero_groups"] = [all_groups[i] for i in zero_indices]

        # ── 5. Value stats ────────────────────────────────────────────────────
        result["min"]  = round(float(t.min()), 6)
        result["max"]  = round(float(t.max()), 6)
        result["mean"] = round(float(t.mean()), 6)
        result["std"]  = round(float(t.std()), 6)

        result["ok"] = True

    except Exception as e:
        result["error"] = str(e)

    return result


def run_aggregation_check(agg_dir: str, sample_rate: float = SAMPLE_RATE):

    root      = Path(agg_dir)
    all_files = list(root.glob("*.pt"))
    total     = len(all_files)

    print(f"📂 Directory      : {root}")
    print(f"   .pt files found : {total:,}\n")

    if total == 0:
        print("❌ No .pt files found. Check your AGG_DIR path.")
        return None

    if sample_rate < 1.0:
        n_sample = max(1, int(total * sample_rate))
        sampled  = random.sample(all_files, n_sample)
        print(f"Sampling {sample_rate*100:.1f}% → checking {n_sample:,} files\n")
    else:
        sampled = all_files
        print(f"Checking ALL {total:,} files\n")

    # ── Sequential validation ─────────────────────────────────────────────────
    results = []
    for path in tqdm(sampled, desc="Validating"):
        results.append(validate_aggregated_file(path))

    df      = pd.DataFrame(results)
    ok      = df[df["ok"] == True]
    corrupt = df[df["ok"] == False]

    # ─────────────────────────────────────────────────────────────────────────
    # REPORT
    # ─────────────────────────────────────────────────────────────────────────
    print(f"\n{'═'*65}")
    print(f"  AGGREGATION VALIDATION REPORT")
    print(f"{'═'*65}")
    print(f"  Total files checked : {len(sampled):,}")
    print(f"  ✓ Clean             : {len(ok):,}")
    print(f"  ✗ Corrupt / Bad     : {len(corrupt):,}")
    print(f"{'═'*65}\n")

    # ── Shape distribution ────────────────────────────────────────────────────
    print(f"{'─'*65}")
    print(f"  SHAPE DISTRIBUTION  (expected: {tuple(EXPECTED_SHAPE)})")
    print(f"{'─'*65}")
    shape_counts = df["shape"].value_counts().reset_index()
    shape_counts.columns = ["Shape", "Count"]
    shape_counts["Match"] = shape_counts["Shape"].apply(
        lambda s: "✓" if str(s) == str(tuple(EXPECTED_SHAPE)) else "✗"
    )
    display(shape_counts)

    # ── Dtype distribution ────────────────────────────────────────────────────
    print(f"\n{'─'*65}")
    print(f"  DTYPE DISTRIBUTION")
    print(f"{'─'*65}")
    display(df["dtype"].value_counts().reset_index().rename(
        columns={"dtype": "DType", "count": "Count"}
    ))

    # ── File size stats ───────────────────────────────────────────────────────
    print(f"\n{'─'*65}")
    print(f"  FILE SIZE STATS (KB)  — expected ≈ {round(14 * 2560 * 4 / 1024, 1)} KB per file")
    print(f"{'─'*65}")
    display(df["file_size_kb"].describe().round(2).to_frame().T)

    # ── Zero group analysis ───────────────────────────────────────────────────
    if len(ok) > 0:
        print(f"\n{'─'*65}")
        print(f"  ZERO GROUP ANALYSIS  (groups with no patches = zero vector)")
        print(f"{'─'*65}")
        slides_with_zeros = (ok["n_zero_rows"] > 0).sum()
        print(f"  Slides with ≥1 zero group : {slides_with_zeros:,} / {len(ok):,}")
        print(f"  Avg zero groups per slide : {ok['n_zero_rows'].mean():.2f}\n")

        group_zero_counts = Counter()
        for zero_list in ok["zero_groups"]:
            group_zero_counts.update(zero_list)

        df_zero = pd.DataFrame(
            group_zero_counts.most_common(),
            columns=["Group", "Slides Where Zero"]
        )
        df_zero["% of slides"] = (df_zero["Slides Where Zero"] / len(ok) * 100).round(2)
        display(df_zero)

    # ── Value stats ───────────────────────────────────────────────────────────
    if len(ok) > 0:
        print(f"\n{'─'*65}")
        print(f"  TENSOR VALUE STATS  (across {len(ok):,} clean files)")
        print(f"{'─'*65}")
        display(ok[["min", "max", "mean", "std"]].describe().round(6))

    # ── Corrupt file details ──────────────────────────────────────────────────
    if len(corrupt) > 0:
        print(f"\n{'─'*65}")
        print(f"  ✗ CORRUPT FILES")
        print(f"{'─'*65}")
        error_summary = corrupt["error"].value_counts().reset_index()
        error_summary.columns = ["Error Type", "Count"]
        display(error_summary)
        print("\n  Corrupt file details:")
        display(corrupt[["file", "shape", "dtype", "error", "file_size_kb"]])

        out_csv = root / "corrupt_aggregated.csv"
        corrupt.to_csv(out_csv, index=False)
        print(f"\n  💾 Corrupt list saved → {out_csv}")
    else:
        print("\n✅ All aggregated files are valid and correct!")

    return df


# ─── RUN ──────────────────────────────────────────────────────────────────────
df_results = run_aggregation_check(
    agg_dir     = AGG_DIR,
    sample_rate = SAMPLE_RATE,
)

📂 Directory      : D:\Aamir Gulzar\KSA_project2\paip_data\slide_aggregation\Caption_based_aggregation\Virchow2
   .pt files found : 73

Checking ALL 73 files

Validating: 100%|██████████| 73/73 [00:00<00:00, 124.03it/s]

═════════════════════════════════════════════════════════════════
  AGGREGATION VALIDATION REPORT
═════════════════════════════════════════════════════════════════
  Total files checked : 73
  ✓ Clean             : 73
  ✗ Corrupt / Bad     : 0
═════════════════════════════════════════════════════════════════

─────────────────────────────────────────────────────────────────
  SHAPE DISTRIBUTION  (expected: (14, 2560))
─────────────────────────────────────────────────────────────────

        Shape  Count Match
0  (14, 2560)     73     ✓

─────────────────────────────────────────────────────────────────
  DTYPE DISTRIBUTION
─────────────────────────────────────────────────────────────────

           DType  Count
0  torch.float32     73

─────────────────────────────────────────────────────────────────
  FILE SIZE STATS (KB)  — expected ≈ 140.0 KB per file
─────────────────────────────────────────────────────────────────

              count    mean   std     min    25%    50%     75%     max
file_size_kb   73.0  141.29  0.03  141.22  141.3  141.3  141.31  141.31

─────────────────────────────────────────────────────────────────
  ZERO GROUP ANALYSIS  (groups with no patches = zero vector)
─────────────────────────────────────────────────────────────────
  Slides with ≥1 zero group : 9 / 73
  Avg zero groups per slide : 0.27

   Group  Slides Where Zero  % of slides
0    CAR                  5         6.85
1    ADE                  3         4.11
2    ADI                  2         2.74
3    PLC                  2         2.74
4    DEB                  1         1.37
5    LYA                  1         1.37
6    MUC                  1         1.37
7   NORM                  1         1.37
8    STR                  1         1.37
9    MES                  1         1.37
10   PDC                  1         1.37
11   SIG                  1         1.37

─────────────────────────────────────────────────────────────────
  TENSOR VALUE STATS  (across 73 clean files)
─────────────────────────────────────────────────────────────────

             min        max       mean        std
count  73.000000  73.000000  73.000000  73.000000
mean  -26.001900   7.976549  -0.007163   0.650084
std     4.715391   2.615072   0.001488   0.048217
min   -34.646152   5.460355  -0.010651   0.351733
25%   -29.499220   6.186872  -0.008037   0.629106
50%   -26.655603   6.834763  -0.007125   0.657640
75%   -23.902889   9.147350  -0.006480   0.672811
max   -13.142479  20.258640   0.000433   0.749826

✅ All aggregated files are valid and correct!