## ANN Classifier

In [1]:
import torch
from typing import Tuple, Dict, Any, List
import torch.nn.functional as F
import numpy as np
import time
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

class ANNClassifier:
    def __init__(self, input_dim=None, hidden_dim1=224, hidden_dim2=128, C=1.0, max_iter=100, verbose=True, random_state=42):
        self.C = C
        self.loss_func = torch.nn.CrossEntropyLoss()
        self.max_iter = max_iter
        self.random_state = random_state
        self.verbose = verbose
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.input_dim = input_dim  # Will be set during fit() if None
        self.hidden_dim1 = hidden_dim1
        self.hidden_dim2 = hidden_dim2
        self.model = None

    def compute_loss(self, preds, labels):
        loss = self.loss_func(preds, labels)
        wreg = 0.5 * sum((param.norm(p=2) for param in self.model.parameters()))  # L2 regularization
        return loss.mean() + (1.0 / self.C) * wreg

    def predict_proba(self, feats):
        feats = feats.to(self.device)
        with torch.no_grad():
            return torch.softmax(self.model(feats), dim=1)

    def fit(self, feats, labels):
        torch.manual_seed(self.random_state)
        np.random.seed(self.random_state)

        # Set input_dim if not set
        if self.input_dim is None:
            self.input_dim = feats.shape[1]

        self.model = torch.nn.Sequential(
            torch.nn.Linear(self.input_dim, self.hidden_dim1),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.3),
            torch.nn.Linear(self.hidden_dim1, self.hidden_dim2),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.3),
            torch.nn.Linear(self.hidden_dim2, 9)  # Assuming 9 classes
        ).to(self.device)

        for layer in self.model:
            if isinstance(layer, torch.nn.Linear):
                torch.nn.init.xavier_uniform_(layer.weight)

        feats = feats.to(self.device)
        labels = labels.long().to(self.device)

        opt = torch.optim.Adam(self.model.parameters(), lr=1e-3, weight_decay=1e-5)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(opt, mode='min', factor=0.5, patience=5)

        min_loss = np.inf
        patience = 10
        patience_counter = 0

        for epoch in range(self.max_iter):
            opt.zero_grad()
            preds = self.model(feats)
            loss = self.compute_loss(preds, labels)
            loss.backward()
            opt.step()
            scheduler.step(loss)

            if self.verbose and epoch % 10 == 0:
                print(f"Epoch {epoch}: Loss: {loss:.4f}")

            if loss < min_loss:
                min_loss = loss
                patience_counter = 0
                best_model = self.model.state_dict()
            else:
                patience_counter += 1

            # if patience_counter >= patience:
            #     print(f"Early stopping at epoch {epoch}")
            #     break

        self.model.load_state_dict(best_model)

        if self.verbose:
            print(f"Final Loss: {min_loss:.4f}")

In [2]:
def test_ANN_probe(
    classifier: ANNClassifier,
    test_feats: torch.Tensor,
    test_labels: torch.Tensor,
    prefix: str = "ann_",
    verbose: bool = True,
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    if verbose:
        print(f"ANN Probe Evaluation: Test shape {test_feats.shape}")

    probs_all = classifier.predict_proba(test_feats).cpu().numpy()
    preds_all = np.argmax(probs_all, axis=1)
    targets_all = test_labels.cpu().numpy()
    roc_kwargs = {"multi_class": "ovo", "average": "macro"}

    # ⬇️ Calculate accuracy
    accuracy = np.mean(preds_all == targets_all)
    print(f"✅ Test Accuracy: {accuracy * 100:.2f}%")

    # ⬇️ Eval metrics
    eval_metrics = get_eval_metrics(targets_all, preds_all, probs_all, True, prefix, roc_kwargs)
    dump = {"preds_all": preds_all, "probs_all": probs_all, "targets_all": targets_all}

    # ⬇️ Confusion matrix
    conf_matrix = confusion_matrix(targets_all, preds_all)
    print("Confusion Matrix:")
    plot_confusion_matrix(conf_matrix)
    
    # ⬇️ New plots for deeper insight
    plot_classification_report(targets_all, preds_all)
    plot_roc_multiclass(targets_all, probs_all, n_classes=9)
    plot_prediction_confidence(probs_all, preds_all, targets_all)


    return eval_metrics, dump

In [3]:
# Do this in main
import pandas as pd

df= pd.read_csv(r"D:\Aamir Gulzar\KSA_project2\dataset\final_merged_without_white.csv")

def is_non_white_patch(patch_path: str, valid_patch_names: set) -> int:
    patch_name = os.path.basename(patch_path)
    return int(patch_name in valid_patch_names)

def extract_coords(patch_name: str):
    try:
        base = os.path.splitext(patch_name)[0]
        parts = base.split('_')
        x = int([p for p in parts if p.startswith('x')][0][1:])
        y = int([p for p in parts if p.startswith('y')][0][1:])
        return x, y
    except Exception as e:
        print(f"❌ Error extracting coords from {patch_name}: {e}")
        return None, None

## Conch 224 five crop patch and crc100k 224 size

In [4]:
import json

with open(r'D:\Aamir Gulzar\KSA_project2\Cancer-detection-classifier\TissueClassifier_CRC100K\best_parameters\best_params_conch.json', 'r') as f:
    best_params = json.load(f)

print("✅ Loaded best_params from best_params_uni2.json",best_params)

✅ Loaded best_params from best_params_uni2.json {'hidden_dim1': 224, 'hidden_dim2': 128, 'C': 10.0, 'max_iter': 500}

### conch features 224 five crop pipeline

In [5]:
model_path = r"D:\Aamir Gulzar\KSA_project2\Cancer-detection-classifier\TissueClassifier_CRC100K\models\ann_crc100k_conch15.pth"

In [6]:
input_dim = 768

# Initialize classifier
model = ANNClassifier(
    input_dim=input_dim,
    hidden_dim1=best_params['hidden_dim1'],
    hidden_dim2=best_params['hidden_dim2'],
    C=best_params['C'],
    max_iter=best_params.get('max_iter', 100),
    verbose=True
)

# Build model architecture (required before loading weights)
model.model = torch.nn.Sequential(
    torch.nn.Linear(model.input_dim, model.hidden_dim1),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.3),
    torch.nn.Linear(model.hidden_dim1, model.hidden_dim2),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.3),
    torch.nn.Linear(model.hidden_dim2, 9)  # 9 classes assumed
).to(model.device)

# Load trained weights
model.model = torch.load(model_path, map_location=model.device)
model.model.to(model.device)
model.model.eval()

Sequential(
  (0): Linear(in_features=768, out_features=224, bias=True)
  (1): ReLU()
  (2): Dropout(p=0.3, inplace=False)
  (3): Linear(in_features=224, out_features=128, bias=True)
  (4): ReLU()
  (5): Dropout(p=0.3, inplace=False)
  (6): Linear(in_features=128, out_features=9, bias=True)
)

## New appraoch label with batches

In [7]:
import os
import h5py
import numpy as np
import pandas as pd
import torch
from tqdm import tqdm

# ========== CONFIGURATION ==========
patches_root = r"D:\Aamir Gulzar\KSA_project2\dataset\patch_data"
features_root = r"D:\Aamir Gulzar\KSA_project2\dataset\Features\Conch_v1_5_fivecrop_Updated"
non_white_csv = r"D:\Aamir Gulzar\KSA_project2\dataset\final_merged_without_white.csv"
BATCH_SIZE = 64  # You can adjust this based on your GPU memory

patch_groups_dir = r"D:\Aamir Gulzar\KSA_project2\dataset\Patch_groups_dict\connch_224_fivecrop"
output_slide_features = r"D:\Aamir Gulzar\KSA_project2\dataset\slide_aggregation\2-Averaging_FiveCrop\conch_224_fivecrop"

In [10]:
import pandas as pd

# Load valid patch names
non_white_df = pd.read_csv(non_white_csv)

valid_patch_names = set(
    non_white_df['patch_name'].astype(str).str.replace('.png', '.pt', regex=False)
)

# Repeat each row 5 times
df_expanded = non_white_df.loc[non_white_df.index.repeat(5)].copy()

# Add updated_patchName column
df_expanded["updated_patchName"] = (
    df_expanded["patch_name"].str.replace(".png", "", regex=False)
    + "_" + (df_expanded.groupby(level=0).cumcount() + 1).astype(str) + ".png"
)

df_expanded

,patch_location,patch_name,patch_number,patch_x,patch_y,avg_R,avg_G,avg_B,std_R,std_G,std_B,label,updated_patchName
0,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.png,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...
0,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.png,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...
0,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.png,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...
0,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.png,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...
0,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.png,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1377932,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.png,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_1.png
1377932,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.png,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_2.png
1377932,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.png,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_3.png
1377932,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.png,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_4.png
1377932,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.png,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_5.png

## Final Pipeline

In [11]:
import os
import torch
from tqdm import tqdm

# Collect all updates here for later update
updates = []
count = 0

for slide_name in tqdm(os.listdir(features_root), desc="🔍 Processing slides"):
    slide_feature_folder = os.path.join(features_root, slide_name)
    count += 1

    print(f"{count}: Processing slide: {slide_name}")

    if not os.path.isdir(slide_feature_folder):
        continue

    pt_files = sorted([
        f for f in os.listdir(slide_feature_folder)
        if f.endswith(".pt")
    ])

    batch_features = []
    batch_patch_names = []

    for idx, pt_file in enumerate(pt_files):
        pt_path = os.path.join(slide_feature_folder, pt_file)

        if is_non_white_patch(pt_path, valid_patch_names) == 0:
            continue

        try:
            features = torch.load(pt_path, map_location='cpu')  # (5, 768)
            if not isinstance(features, torch.Tensor):
                raise ValueError(f"Expected tensor, got {type(features)}")

            if features.shape != (5, 768):
                print(f"⚠️ Unexpected shape in {pt_file}: {features.shape}")
                continue

            # Directly extend the batch features with slices from the tensor
            batch_features.extend([features[i] for i in range(5)])

            # Generate corresponding patch names
            base = os.path.splitext(pt_file)[0]
            batch_patch_names.extend([f"{base}_{i+1}.png" for i in range(5)])

        except Exception as e:
            print(f"❌ Error reading {pt_path}: {e}")
            continue

        # Run model if batch full or last patch
        last_patch = (idx == len(pt_files) - 1)
        if len(batch_features) >= BATCH_SIZE or last_patch:
            try:
                tensor_batch = torch.stack(batch_features).to(model.device)  # shape: (B, 768)

                model.model.eval()
                with torch.no_grad():
                    outputs = model.model(tensor_batch)
                    predictions = torch.argmax(outputs, dim=1).cpu().tolist()

                updates.extend(zip(batch_patch_names, predictions))

            except Exception as e:
                print(f"❌ Inference error: {e}")

            # Free memory
            del tensor_batch, outputs
            torch.cuda.empty_cache()

            # Reset batch
            batch_features.clear()
            batch_patch_names.clear()

🔍 Processing slides:   0%|                                                                    | 0/417 [00:00<?, ?it/s]

1: Processing slide: TCGA-3L-AA1B_nonMSIH

🔍 Processing slides:   0%|▏                                                           | 1/417 [00:00<05:36,  1.24it/s]

2: Processing slide: TCGA-4N-A93T_nonMSIH

🔍 Processing slides:   0%|▎                                                           | 2/417 [00:02<08:48,  1.27s/it]

3: Processing slide: TCGA-5M-AAT4_nonMSIH

🔍 Processing slides:   1%|▍                                                           | 3/417 [00:04<12:55,  1.87s/it]

4: Processing slide: TCGA-5M-AAT6_MSIH

🔍 Processing slides:   1%|▌                                                           | 4/417 [00:06<12:00,  1.74s/it]

5: Processing slide: TCGA-5M-AATE_nonMSIH

🔍 Processing slides:   1%|▋                                                           | 5/417 [00:09<15:13,  2.22s/it]

6: Processing slide: TCGA-A6-2671_nonMSIH

🔍 Processing slides:   1%|▊                                                           | 6/417 [00:09<10:37,  1.55s/it]

7: Processing slide: TCGA-A6-2681_nonMSIH

🔍 Processing slides:   2%|█                                                           | 7/417 [00:11<11:39,  1.71s/it]

8: Processing slide: TCGA-A6-2685_nonMSIH

🔍 Processing slides:   2%|█▏                                                          | 8/417 [00:30<49:07,  7.21s/it]

9: Processing slide: TCGA-A6-2686_MSIH

🔍 Processing slides:   2%|█▎                                                        | 9/417 [00:50<1:16:08, 11.20s/it]

10: Processing slide: TCGA-A6-3807_nonMSIH

🔍 Processing slides:   2%|█▎                                                       | 10/417 [01:10<1:34:35, 13.95s/it]

11: Processing slide: TCGA-A6-4105_nonMSIH

🔍 Processing slides:   3%|█▌                                                       | 11/417 [01:30<1:46:52, 15.79s/it]

12: Processing slide: TCGA-A6-4107_nonMSIH

🔍 Processing slides:   3%|█▋                                                       | 12/417 [01:36<1:26:31, 12.82s/it]

13: Processing slide: TCGA-A6-5657_nonMSIH

🔍 Processing slides:   3%|█▊                                                       | 13/417 [01:44<1:16:15, 11.32s/it]

14: Processing slide: TCGA-A6-5660_nonMSIH

🔍 Processing slides:   3%|█▉                                                       | 14/417 [01:52<1:08:50, 10.25s/it]

15: Processing slide: TCGA-A6-5661_MSIH

🔍 Processing slides:   4%|██                                                       | 15/417 [01:59<1:01:46,  9.22s/it]

16: Processing slide: TCGA-A6-5662_nonMSIH

🔍 Processing slides:   4%|██▎                                                        | 16/417 [02:03<51:41,  7.73s/it]

17: Processing slide: TCGA-A6-5664_nonMSIH

🔍 Processing slides:   4%|██▎                                                      | 17/417 [02:17<1:04:00,  9.60s/it]

18: Processing slide: TCGA-A6-5665_MSIH

🔍 Processing slides:   4%|██▌                                                        | 18/417 [02:23<57:17,  8.61s/it]

19: Processing slide: TCGA-A6-5666_nonMSIH

🔍 Processing slides:   5%|██▌                                                      | 19/417 [02:36<1:04:20,  9.70s/it]

20: Processing slide: TCGA-A6-5667_nonMSIH

🔍 Processing slides:   5%|██▊                                                        | 20/417 [02:38<50:08,  7.58s/it]

21: Processing slide: TCGA-A6-6137_nonMSIH

🔍 Processing slides:   5%|██▉                                                        | 21/417 [02:48<53:49,  8.15s/it]

22: Processing slide: TCGA-A6-6138_nonMSIH

🔍 Processing slides:   5%|███                                                        | 22/417 [02:54<50:25,  7.66s/it]

23: Processing slide: TCGA-A6-6142_nonMSIH

🔍 Processing slides:   6%|███▎                                                       | 23/417 [03:00<47:13,  7.19s/it]

24: Processing slide: TCGA-A6-6648_nonMSIH

🔍 Processing slides:   6%|███▍                                                       | 24/417 [03:04<39:11,  5.98s/it]

25: Processing slide: TCGA-A6-6649_nonMSIH

🔍 Processing slides:   6%|███▌                                                       | 25/417 [03:08<36:29,  5.58s/it]

26: Processing slide: TCGA-A6-6651_nonMSIH

🔍 Processing slides:   6%|███▋                                                       | 26/417 [03:14<37:31,  5.76s/it]

27: Processing slide: TCGA-A6-6652_nonMSIH

🔍 Processing slides:   6%|███▊                                                       | 27/417 [03:17<30:29,  4.69s/it]

28: Processing slide: TCGA-A6-6653_MSIH

🔍 Processing slides:   7%|███▉                                                       | 28/417 [03:24<36:26,  5.62s/it]

29: Processing slide: TCGA-A6-6654_nonMSIH

🔍 Processing slides:   7%|████                                                       | 29/417 [03:33<41:42,  6.45s/it]

30: Processing slide: TCGA-A6-A565_nonMSIH

🔍 Processing slides:   7%|████▏                                                      | 30/417 [03:36<36:12,  5.61s/it]

31: Processing slide: TCGA-A6-A566_nonMSIH

🔍 Processing slides:   7%|████▍                                                      | 31/417 [03:45<41:22,  6.43s/it]

32: Processing slide: TCGA-A6-A567_nonMSIH

🔍 Processing slides:   8%|████▌                                                      | 32/417 [03:56<51:24,  8.01s/it]

33: Processing slide: TCGA-A6-A56B_nonMSIH

🔍 Processing slides:   8%|████▋                                                      | 33/417 [04:09<59:23,  9.28s/it]

34: Processing slide: TCGA-AA-3664_nonMSIH

🔍 Processing slides:   8%|████▋                                                    | 34/417 [04:38<1:37:32, 15.28s/it]

35: Processing slide: TCGA-AA-3666_nonMSIH

🔍 Processing slides:   8%|████▊                                                    | 35/417 [05:03<1:56:18, 18.27s/it]

36: Processing slide: TCGA-AA-3667_nonMSIH

🔍 Processing slides:   9%|████▉                                                    | 36/417 [05:20<1:53:44, 17.91s/it]

37: Processing slide: TCGA-AA-3673_nonMSIH

🔍 Processing slides:   9%|█████                                                    | 37/417 [05:28<1:34:55, 14.99s/it]

38: Processing slide: TCGA-AA-3678_nonMSIH

🔍 Processing slides:   9%|█████▏                                                   | 38/417 [05:37<1:21:43, 12.94s/it]

39: Processing slide: TCGA-AA-3679_nonMSIH

🔍 Processing slides:   9%|█████▎                                                   | 39/417 [05:56<1:33:21, 14.82s/it]

40: Processing slide: TCGA-AA-3680_nonMSIH

🔍 Processing slides:  10%|█████▍                                                   | 40/417 [06:22<1:54:34, 18.23s/it]

41: Processing slide: TCGA-AA-3681_nonMSIH

🔍 Processing slides:  10%|█████▌                                                   | 41/417 [06:38<1:50:29, 17.63s/it]

42: Processing slide: TCGA-AA-3684_nonMSIH

🔍 Processing slides:  10%|█████▋                                                   | 42/417 [08:15<4:18:12, 41.31s/it]

43: Processing slide: TCGA-AA-3688_nonMSIH

🔍 Processing slides:  10%|█████▉                                                   | 43/417 [08:36<3:39:59, 35.29s/it]

44: Processing slide: TCGA-AA-3692_nonMSIH

🔍 Processing slides:  11%|██████                                                   | 44/417 [08:54<3:06:11, 29.95s/it]

45: Processing slide: TCGA-AA-3693_nonMSIH

🔍 Processing slides:  11%|██████▏                                                  | 45/417 [09:19<2:57:52, 28.69s/it]

46: Processing slide: TCGA-AA-3696_nonMSIH

🔍 Processing slides:  11%|██████▎                                                  | 46/417 [09:30<2:24:25, 23.36s/it]

47: Processing slide: TCGA-AA-3715_MSIH

🔍 Processing slides:  11%|██████▍                                                  | 47/417 [10:02<2:39:02, 25.79s/it]

48: Processing slide: TCGA-AA-3811_MSIH

🔍 Processing slides:  12%|██████▌                                                  | 48/417 [10:20<2:24:57, 23.57s/it]

49: Processing slide: TCGA-AA-3812_nonMSIH

🔍 Processing slides:  12%|██████▋                                                  | 49/417 [10:41<2:19:35, 22.76s/it]

50: Processing slide: TCGA-AA-3814_nonMSIH

🔍 Processing slides:  12%|██████▊                                                  | 50/417 [10:48<1:50:58, 18.14s/it]

51: Processing slide: TCGA-AA-3818_nonMSIH

🔍 Processing slides:  12%|██████▉                                                  | 51/417 [11:07<1:51:15, 18.24s/it]

52: Processing slide: TCGA-AA-3819_nonMSIH

🔍 Processing slides:  12%|███████                                                  | 52/417 [11:23<1:47:33, 17.68s/it]

53: Processing slide: TCGA-AA-3821_MSIH

🔍 Processing slides:  13%|███████▏                                                 | 53/417 [11:39<1:44:21, 17.20s/it]

54: Processing slide: TCGA-AA-3831_nonMSIH

🔍 Processing slides:  13%|███████▍                                                 | 54/417 [11:55<1:40:40, 16.64s/it]

55: Processing slide: TCGA-AA-3833_MSIH

🔍 Processing slides:  13%|███████▌                                                 | 55/417 [12:23<2:01:34, 20.15s/it]

56: Processing slide: TCGA-AA-3837_nonMSIH

🔍 Processing slides:  13%|███████▋                                                 | 56/417 [12:41<1:56:49, 19.42s/it]

57: Processing slide: TCGA-AA-3842_nonMSIH

🔍 Processing slides:  14%|███████▊                                                 | 57/417 [12:52<1:42:12, 17.03s/it]

58: Processing slide: TCGA-AA-3844_nonMSIH

🔍 Processing slides:  14%|███████▉                                                 | 58/417 [13:06<1:36:52, 16.19s/it]

59: Processing slide: TCGA-AA-3845_MSIH

🔍 Processing slides:  14%|████████                                                 | 59/417 [13:21<1:33:02, 15.59s/it]

60: Processing slide: TCGA-AA-3846_nonMSIH

🔍 Processing slides:  14%|████████▏                                                | 60/417 [13:27<1:17:07, 12.96s/it]

61: Processing slide: TCGA-AA-3848_nonMSIH

🔍 Processing slides:  15%|████████▎                                                | 61/417 [13:52<1:37:09, 16.37s/it]

62: Processing slide: TCGA-AA-3850_nonMSIH

🔍 Processing slides:  15%|████████▍                                                | 62/417 [14:07<1:35:15, 16.10s/it]

63: Processing slide: TCGA-AA-3851_nonMSIH

🔍 Processing slides:  15%|████████▌                                                | 63/417 [14:22<1:32:42, 15.71s/it]

64: Processing slide: TCGA-AA-3852_nonMSIH

🔍 Processing slides:  15%|████████▋                                                | 64/417 [14:34<1:26:45, 14.75s/it]

65: Processing slide: TCGA-AA-3854_nonMSIH

🔍 Processing slides:  16%|████████▉                                                | 65/417 [14:41<1:12:17, 12.32s/it]

66: Processing slide: TCGA-AA-3855_nonMSIH

🔍 Processing slides:  16%|█████████                                                | 66/417 [15:01<1:25:50, 14.67s/it]

67: Processing slide: TCGA-AA-3856_nonMSIH

🔍 Processing slides:  16%|█████████▏                                               | 67/417 [15:42<2:11:29, 22.54s/it]

68: Processing slide: TCGA-AA-3858_nonMSIH

🔍 Processing slides:  16%|█████████▎                                               | 68/417 [15:46<1:39:16, 17.07s/it]

69: Processing slide: TCGA-AA-3864_MSIH

🔍 Processing slides:  17%|█████████▍                                               | 69/417 [16:03<1:37:38, 16.84s/it]

70: Processing slide: TCGA-AA-3866_nonMSIH

🔍 Processing slides:  17%|█████████▌                                               | 70/417 [16:17<1:32:26, 15.98s/it]

71: Processing slide: TCGA-AA-3867_nonMSIH

🔍 Processing slides:  17%|█████████▋                                               | 71/417 [16:30<1:27:49, 15.23s/it]

72: Processing slide: TCGA-AA-3875_nonMSIH

🔍 Processing slides:  17%|█████████▊                                               | 72/417 [16:46<1:28:50, 15.45s/it]

73: Processing slide: TCGA-AA-3877_MSIH

🔍 Processing slides:  18%|█████████▉                                               | 73/417 [17:04<1:32:58, 16.22s/it]

74: Processing slide: TCGA-AA-3947_MSIH

🔍 Processing slides:  18%|██████████                                               | 74/417 [17:53<2:28:11, 25.92s/it]

75: Processing slide: TCGA-AA-3949_MSIH

🔍 Processing slides:  18%|██████████▎                                              | 75/417 [18:08<2:09:23, 22.70s/it]

76: Processing slide: TCGA-AA-3950_MSIH

🔍 Processing slides:  18%|██████████▍                                              | 76/417 [18:23<1:55:59, 20.41s/it]

77: Processing slide: TCGA-AA-3952_nonMSIH

🔍 Processing slides:  18%|██████████▌                                              | 77/417 [18:31<1:34:11, 16.62s/it]

78: Processing slide: TCGA-AA-3956_nonMSIH

🔍 Processing slides:  19%|██████████▋                                              | 78/417 [18:49<1:37:21, 17.23s/it]

79: Processing slide: TCGA-AA-3966_MSIH

🔍 Processing slides:  19%|██████████▊                                              | 79/417 [19:15<1:51:22, 19.77s/it]

80: Processing slide: TCGA-AA-3968_nonMSIH

🔍 Processing slides:  19%|██████████▉                                              | 80/417 [19:29<1:41:15, 18.03s/it]

81: Processing slide: TCGA-AA-3971_nonMSIH

🔍 Processing slides:  19%|███████████                                              | 81/417 [20:01<2:04:39, 22.26s/it]

82: Processing slide: TCGA-AA-3973_nonMSIH

🔍 Processing slides:  20%|███████████▏                                             | 82/417 [20:27<2:09:59, 23.28s/it]

83: Processing slide: TCGA-AA-3975_nonMSIH

🔍 Processing slides:  20%|███████████▎                                             | 83/417 [20:53<2:13:54, 24.06s/it]

84: Processing slide: TCGA-AA-3976_nonMSIH

🔍 Processing slides:  20%|███████████▍                                             | 84/417 [21:03<1:49:54, 19.80s/it]

85: Processing slide: TCGA-AA-3979_nonMSIH

🔍 Processing slides:  20%|███████████▌                                             | 85/417 [21:20<1:45:01, 18.98s/it]

86: Processing slide: TCGA-AA-3982_nonMSIH

🔍 Processing slides:  21%|███████████▊                                             | 86/417 [21:40<1:46:27, 19.30s/it]

87: Processing slide: TCGA-AA-3984_nonMSIH

🔍 Processing slides:  21%|███████████▉                                             | 87/417 [22:00<1:47:26, 19.54s/it]

88: Processing slide: TCGA-AA-3986_nonMSIH

🔍 Processing slides:  21%|████████████                                             | 88/417 [22:42<2:24:20, 26.33s/it]

89: Processing slide: TCGA-AA-3989_nonMSIH

🔍 Processing slides:  21%|████████████▏                                            | 89/417 [22:57<2:05:15, 22.91s/it]

90: Processing slide: TCGA-AA-3994_nonMSIH

🔍 Processing slides:  22%|████████████▎                                            | 90/417 [23:07<1:43:34, 19.00s/it]

91: Processing slide: TCGA-AA-A010_nonMSIH

🔍 Processing slides:  22%|████████████▍                                            | 91/417 [23:45<2:13:47, 24.62s/it]

92: Processing slide: TCGA-AA-A01P_MSIH

🔍 Processing slides:  22%|████████████▌                                            | 92/417 [24:28<2:44:10, 30.31s/it]

93: Processing slide: TCGA-AA-A01R_MSIH

🔍 Processing slides:  22%|████████████▋                                            | 93/417 [25:18<3:15:29, 36.20s/it]

94: Processing slide: TCGA-AA-A01S_nonMSIH

🔍 Processing slides:  23%|████████████▊                                            | 94/417 [25:57<3:18:25, 36.86s/it]

95: Processing slide: TCGA-AA-A01T_nonMSIH

🔍 Processing slides:  23%|████████████▉                                            | 95/417 [26:16<2:49:51, 31.65s/it]

96: Processing slide: TCGA-AA-A01V_nonMSIH

🔍 Processing slides:  23%|█████████████                                            | 96/417 [27:11<3:26:55, 38.68s/it]

97: Processing slide: TCGA-AA-A01X_nonMSIH

🔍 Processing slides:  23%|█████████████▎                                           | 97/417 [27:46<3:19:43, 37.45s/it]

98: Processing slide: TCGA-AA-A01Z_nonMSIH

🔍 Processing slides:  24%|█████████████▍                                           | 98/417 [28:17<3:09:43, 35.69s/it]

99: Processing slide: TCGA-AA-A024_nonMSIH

🔍 Processing slides:  24%|█████████████▌                                           | 99/417 [28:48<3:00:31, 34.06s/it]

100: Processing slide: TCGA-AA-A02E_nonMSIH

🔍 Processing slides:  24%|█████████████▍                                          | 100/417 [29:11<2:43:53, 31.02s/it]

101: Processing slide: TCGA-AA-A02F_nonMSIH

🔍 Processing slides:  24%|█████████████▌                                          | 101/417 [29:56<3:04:38, 35.06s/it]

102: Processing slide: TCGA-AA-A02H_nonMSIH

🔍 Processing slides:  24%|█████████████▋                                          | 102/417 [30:18<2:43:40, 31.18s/it]

103: Processing slide: TCGA-AA-A02O_nonMSIH

🔍 Processing slides:  25%|█████████████▊                                          | 103/417 [30:49<2:43:02, 31.15s/it]

104: Processing slide: TCGA-AA-A02Y_nonMSIH

🔍 Processing slides:  25%|█████████████▉                                          | 104/417 [31:06<2:19:41, 26.78s/it]

105: Processing slide: TCGA-AA-A03F_nonMSIH

🔍 Processing slides:  25%|██████████████                                          | 105/417 [31:26<2:08:44, 24.76s/it]

106: Processing slide: TCGA-AA-A03J_nonMSIH

🔍 Processing slides:  25%|██████████████▏                                         | 106/417 [32:16<2:48:13, 32.46s/it]

107: Processing slide: TCGA-AD-5900_MSIH

🔍 Processing slides:  26%|██████████████▎                                         | 107/417 [32:19<2:02:01, 23.62s/it]

108: Processing slide: TCGA-AD-6548_nonMSIH

🔍 Processing slides:  26%|██████████████▌                                         | 108/417 [32:21<1:28:31, 17.19s/it]

109: Processing slide: TCGA-AD-6888_nonMSIH

🔍 Processing slides:  26%|██████████████▋                                         | 109/417 [32:26<1:08:42, 13.39s/it]

110: Processing slide: TCGA-AD-6889_MSIH

🔍 Processing slides:  26%|██████████████▊                                         | 110/417 [32:36<1:04:13, 12.55s/it]

111: Processing slide: TCGA-AD-6890_nonMSIH

🔍 Processing slides:  27%|███████████████▍                                          | 111/417 [32:39<48:46,  9.56s/it]

112: Processing slide: TCGA-AD-6901_nonMSIH

🔍 Processing slides:  27%|███████████████▌                                          | 112/417 [32:43<40:20,  7.94s/it]

113: Processing slide: TCGA-AD-6963_nonMSIH

🔍 Processing slides:  27%|███████████████▋                                          | 113/417 [32:46<31:55,  6.30s/it]

114: Processing slide: TCGA-AD-6964_MSIH

🔍 Processing slides:  27%|███████████████▊                                          | 114/417 [32:54<35:23,  7.01s/it]

115: Processing slide: TCGA-AD-6965_nonMSIH

🔍 Processing slides:  28%|███████████████▉                                          | 115/417 [32:59<31:46,  6.31s/it]

116: Processing slide: TCGA-AD-A5EJ_MSIH

🔍 Processing slides:  28%|████████████████▏                                         | 116/417 [33:06<31:57,  6.37s/it]

117: Processing slide: TCGA-AD-A5EK_nonMSIH

🔍 Processing slides:  28%|████████████████▎                                         | 117/417 [33:18<40:20,  8.07s/it]

118: Processing slide: TCGA-AF-2687_nonMSIH

🔍 Processing slides:  28%|████████████████▍                                         | 118/417 [33:32<49:59, 10.03s/it]

119: Processing slide: TCGA-AF-2690_nonMSIH

🔍 Processing slides:  29%|███████████████▉                                        | 119/417 [34:14<1:37:30, 19.63s/it]

120: Processing slide: TCGA-AF-2693_nonMSIH

🔍 Processing slides:  29%|████████████████                                        | 120/417 [34:22<1:19:29, 16.06s/it]

121: Processing slide: TCGA-AF-3911_nonMSIH

🔍 Processing slides:  29%|████████████████▏                                       | 121/417 [34:33<1:12:15, 14.65s/it]

122: Processing slide: TCGA-AF-4110_nonMSIH

🔍 Processing slides:  29%|████████████████▍                                       | 122/417 [34:46<1:09:31, 14.14s/it]

123: Processing slide: TCGA-AF-6136_nonMSIH

🔍 Processing slides:  29%|████████████████▌                                       | 123/417 [34:58<1:06:09, 13.50s/it]

124: Processing slide: TCGA-AF-6655_nonMSIH

🔍 Processing slides:  30%|█████████████████▏                                        | 124/417 [35:05<56:13, 11.51s/it]

125: Processing slide: TCGA-AF-6672_nonMSIH

🔍 Processing slides:  30%|████████████████▊                                       | 125/417 [35:27<1:11:52, 14.77s/it]

126: Processing slide: TCGA-AF-A56K_nonMSIH

🔍 Processing slides:  30%|████████████████▉                                       | 126/417 [35:53<1:27:20, 18.01s/it]

127: Processing slide: TCGA-AF-A56L_nonMSIH

🔍 Processing slides:  30%|█████████████████                                       | 127/417 [36:24<1:45:06, 21.75s/it]

128: Processing slide: TCGA-AF-A56N_nonMSIH

🔍 Processing slides:  31%|█████████████████▏                                      | 128/417 [36:31<1:24:10, 17.48s/it]

129: Processing slide: TCGA-AG-3726_nonMSIH

🔍 Processing slides:  31%|█████████████████▎                                      | 129/417 [36:40<1:12:17, 15.06s/it]

130: Processing slide: TCGA-AG-3727_nonMSIH

🔍 Processing slides:  31%|█████████████████▍                                      | 130/417 [36:51<1:04:55, 13.57s/it]

131: Processing slide: TCGA-AG-3878_nonMSIH

🔍 Processing slides:  31%|█████████████████▌                                      | 131/417 [37:04<1:05:03, 13.65s/it]

132: Processing slide: TCGA-AG-3882_nonMSIH

🔍 Processing slides:  32%|█████████████████▋                                      | 132/417 [37:20<1:07:56, 14.30s/it]

133: Processing slide: TCGA-AG-3883_nonMSIH

🔍 Processing slides:  32%|█████████████████▊                                      | 133/417 [37:55<1:37:07, 20.52s/it]

134: Processing slide: TCGA-AG-3885_nonMSIH

🔍 Processing slides:  32%|█████████████████▉                                      | 134/417 [38:13<1:33:05, 19.74s/it]

135: Processing slide: TCGA-AG-3887_nonMSIH

🔍 Processing slides:  32%|██████████████████▏                                     | 135/417 [38:25<1:21:26, 17.33s/it]

136: Processing slide: TCGA-AG-3890_nonMSIH

🔍 Processing slides:  33%|██████████████████▎                                     | 136/417 [38:54<1:37:48, 20.88s/it]

137: Processing slide: TCGA-AG-3892_nonMSIH

🔍 Processing slides:  33%|██████████████████▍                                     | 137/417 [39:19<1:43:12, 22.12s/it]

138: Processing slide: TCGA-AG-3893_nonMSIH

🔍 Processing slides:  33%|██████████████████▌                                     | 138/417 [39:34<1:32:13, 19.83s/it]

139: Processing slide: TCGA-AG-3894_nonMSIH

🔍 Processing slides:  33%|██████████████████▋                                     | 139/417 [39:55<1:34:22, 20.37s/it]

140: Processing slide: TCGA-AG-3896_nonMSIH

🔍 Processing slides:  34%|██████████████████▊                                     | 140/417 [40:27<1:50:26, 23.92s/it]

141: Processing slide: TCGA-AG-3898_nonMSIH

🔍 Processing slides:  34%|██████████████████▉                                     | 141/417 [41:07<2:11:42, 28.63s/it]

142: Processing slide: TCGA-AG-3901_nonMSIH

🔍 Processing slides:  34%|███████████████████                                     | 142/417 [41:21<1:50:58, 24.21s/it]

143: Processing slide: TCGA-AG-3902_nonMSIH

🔍 Processing slides:  34%|███████████████████▏                                    | 143/417 [42:00<2:11:24, 28.78s/it]

144: Processing slide: TCGA-AG-3909_nonMSIH

🔍 Processing slides:  35%|███████████████████▎                                    | 144/417 [42:14<1:50:05, 24.20s/it]

145: Processing slide: TCGA-AG-4001_nonMSIH

🔍 Processing slides:  35%|███████████████████▍                                    | 145/417 [42:34<1:43:48, 22.90s/it]

146: Processing slide: TCGA-AG-4008_nonMSIH

🔍 Processing slides:  35%|███████████████████▌                                    | 146/417 [42:56<1:43:13, 22.85s/it]

147: Processing slide: TCGA-AG-4015_nonMSIH

🔍 Processing slides:  35%|███████████████████▋                                    | 147/417 [43:15<1:37:33, 21.68s/it]

148: Processing slide: TCGA-AG-4021_nonMSIH

🔍 Processing slides:  35%|███████████████████▉                                    | 148/417 [43:50<1:55:11, 25.69s/it]

149: Processing slide: TCGA-AG-4022_nonMSIH

🔍 Processing slides:  36%|████████████████████                                    | 149/417 [44:23<2:04:00, 27.76s/it]

150: Processing slide: TCGA-AG-A002_nonMSIH

🔍 Processing slides:  36%|████████████████████▏                                   | 150/417 [44:55<2:08:43, 28.93s/it]

151: Processing slide: TCGA-AG-A008_nonMSIH

🔍 Processing slides:  36%|████████████████████▎                                   | 151/417 [45:33<2:21:15, 31.86s/it]

152: Processing slide: TCGA-AG-A00C_nonMSIH

🔍 Processing slides:  36%|████████████████████▍                                   | 152/417 [45:59<2:12:22, 29.97s/it]

153: Processing slide: TCGA-AG-A011_nonMSIH

🔍 Processing slides:  37%|████████████████████▌                                   | 153/417 [46:18<1:58:02, 26.83s/it]

154: Processing slide: TCGA-AG-A015_nonMSIH

🔍 Processing slides:  37%|████████████████████▋                                   | 154/417 [47:02<2:19:57, 31.93s/it]

155: Processing slide: TCGA-AG-A016_nonMSIH

🔍 Processing slides:  37%|████████████████████▊                                   | 155/417 [47:40<2:26:34, 33.57s/it]

156: Processing slide: TCGA-AG-A01L_nonMSIH

🔍 Processing slides:  37%|████████████████████▉                                   | 156/417 [47:49<1:53:45, 26.15s/it]

157: Processing slide: TCGA-AG-A01N_nonMSIH

🔍 Processing slides:  38%|█████████████████████                                   | 157/417 [48:07<1:43:28, 23.88s/it]

158: Processing slide: TCGA-AG-A01W_nonMSIH

🔍 Processing slides:  38%|█████████████████████▏                                  | 158/417 [49:16<2:41:19, 37.37s/it]

159: Processing slide: TCGA-AG-A01Y_nonMSIH

🔍 Processing slides:  38%|█████████████████████▎                                  | 159/417 [49:47<2:32:40, 35.51s/it]

160: Processing slide: TCGA-AG-A020_nonMSIH

🔍 Processing slides:  38%|█████████████████████▍                                  | 160/417 [50:06<2:10:23, 30.44s/it]

161: Processing slide: TCGA-AG-A026_nonMSIH

🔍 Processing slides:  39%|█████████████████████▌                                  | 161/417 [50:22<1:51:20, 26.10s/it]

162: Processing slide: TCGA-AG-A02N_MSIH

🔍 Processing slides:  39%|█████████████████████▊                                  | 162/417 [50:44<1:46:24, 25.04s/it]

163: Processing slide: TCGA-AG-A02X_nonMSIH

🔍 Processing slides:  39%|█████████████████████▉                                  | 163/417 [50:54<1:26:41, 20.48s/it]

164: Processing slide: TCGA-AH-6544_nonMSIH

🔍 Processing slides:  39%|██████████████████████                                  | 164/417 [51:02<1:09:57, 16.59s/it]

165: Processing slide: TCGA-AH-6547_nonMSIH

🔍 Processing slides:  40%|██████████████████████▉                                   | 165/417 [51:03<50:27, 12.02s/it]

166: Processing slide: TCGA-AH-6643_nonMSIH

🔍 Processing slides:  40%|███████████████████████                                   | 166/417 [51:09<42:53, 10.25s/it]

167: Processing slide: TCGA-AH-6644_nonMSIH

🔍 Processing slides:  40%|███████████████████████▏                                  | 167/417 [51:12<33:39,  8.08s/it]

168: Processing slide: TCGA-AH-6897_nonMSIH

🔍 Processing slides:  40%|███████████████████████▎                                  | 168/417 [51:17<29:08,  7.02s/it]

169: Processing slide: TCGA-AH-6903_nonMSIH

🔍 Processing slides:  41%|███████████████████████▌                                  | 169/417 [51:20<24:23,  5.90s/it]

170: Processing slide: TCGA-AM-5820_nonMSIH

🔍 Processing slides:  41%|███████████████████████▋                                  | 170/417 [51:29<28:00,  6.81s/it]

171: Processing slide: TCGA-AM-5821_MSIH

🔍 Processing slides:  41%|███████████████████████▊                                  | 171/417 [51:40<33:27,  8.16s/it]

172: Processing slide: TCGA-AU-3779_nonMSIH

🔍 Processing slides:  41%|███████████████████████▉                                  | 172/417 [51:43<26:33,  6.50s/it]

173: Processing slide: TCGA-AU-6004_MSIH

🔍 Processing slides:  41%|████████████████████████                                  | 173/417 [51:49<25:44,  6.33s/it]

174: Processing slide: TCGA-AY-4070_nonMSIH

🔍 Processing slides:  42%|████████████████████████▏                                 | 174/417 [51:51<20:06,  4.97s/it]

175: Processing slide: TCGA-AY-4071_nonMSIH

🔍 Processing slides:  42%|████████████████████████▎                                 | 175/417 [51:53<16:39,  4.13s/it]

176: Processing slide: TCGA-AY-5543_nonMSIH

🔍 Processing slides:  42%|████████████████████████▍                                 | 176/417 [52:09<30:40,  7.64s/it]

177: Processing slide: TCGA-AY-6196_nonMSIH

🔍 Processing slides:  42%|████████████████████████▌                                 | 177/417 [52:36<54:26, 13.61s/it]

178: Processing slide: TCGA-AY-6197_MSIH

🔍 Processing slides:  43%|███████████████████████▉                                | 178/417 [52:58<1:04:04, 16.08s/it]

179: Processing slide: TCGA-AY-6386_nonMSIH

🔍 Processing slides:  43%|████████████████████████                                | 179/417 [53:11<1:00:19, 15.21s/it]

180: Processing slide: TCGA-AY-A54L_nonMSIH

🔍 Processing slides:  43%|████████████████████████▏                               | 180/417 [53:27<1:00:53, 15.42s/it]

181: Processing slide: TCGA-AY-A69D_nonMSIH

🔍 Processing slides:  43%|█████████████████████████▏                                | 181/417 [53:38<54:51, 13.95s/it]

182: Processing slide: TCGA-AY-A71X_nonMSIH

🔍 Processing slides:  44%|████████████████████████▍                               | 182/417 [54:12<1:18:27, 20.03s/it]

183: Processing slide: TCGA-AY-A8YK_nonMSIH

🔍 Processing slides:  44%|████████████████████████▌                               | 183/417 [54:23<1:07:58, 17.43s/it]

184: Processing slide: TCGA-AZ-4308_nonMSIH

🔍 Processing slides:  44%|████████████████████████▋                               | 184/417 [54:41<1:08:05, 17.53s/it]

185: Processing slide: TCGA-AZ-4315_nonMSIH

🔍 Processing slides:  44%|████████████████████████▊                               | 185/417 [55:18<1:30:05, 23.30s/it]

186: Processing slide: TCGA-AZ-4614_nonMSIH

🔍 Processing slides:  45%|████████████████████████▉                               | 186/417 [55:48<1:38:04, 25.47s/it]

187: Processing slide: TCGA-AZ-4615_MSIH

🔍 Processing slides:  45%|█████████████████████████                               | 187/417 [56:17<1:41:07, 26.38s/it]

188: Processing slide: TCGA-AZ-4616_nonMSIH

🔍 Processing slides:  45%|█████████████████████████▏                              | 188/417 [56:38<1:34:19, 24.71s/it]

189: Processing slide: TCGA-AZ-4681_nonMSIH

🔍 Processing slides:  45%|█████████████████████████▍                              | 189/417 [56:56<1:26:31, 22.77s/it]

190: Processing slide: TCGA-AZ-4682_nonMSIH

🔍 Processing slides:  46%|█████████████████████████▌                              | 190/417 [57:19<1:27:12, 23.05s/it]

191: Processing slide: TCGA-AZ-5403_nonMSIH

🔍 Processing slides:  46%|█████████████████████████▋                              | 191/417 [58:01<1:48:00, 28.68s/it]

192: Processing slide: TCGA-AZ-5407_nonMSIH

🔍 Processing slides:  46%|█████████████████████████▊                              | 192/417 [58:18<1:33:52, 25.03s/it]

193: Processing slide: TCGA-AZ-6598_MSIH

🔍 Processing slides:  46%|█████████████████████████▉                              | 193/417 [58:46<1:36:48, 25.93s/it]

194: Processing slide: TCGA-AZ-6599_nonMSIH

🔍 Processing slides:  47%|██████████████████████████                              | 194/417 [59:11<1:35:12, 25.62s/it]

195: Processing slide: TCGA-AZ-6600_nonMSIH

🔍 Processing slides:  47%|██████████████████████████▏                             | 195/417 [59:41<1:40:28, 27.15s/it]

196: Processing slide: TCGA-AZ-6603_nonMSIH

🔍 Processing slides:  47%|█████████████████████████▍                            | 196/417 [1:00:04<1:35:17, 25.87s/it]

197: Processing slide: TCGA-AZ-6605_nonMSIH

🔍 Processing slides:  47%|█████████████████████████▌                            | 197/417 [1:00:27<1:31:37, 24.99s/it]

198: Processing slide: TCGA-AZ-6606_nonMSIH

🔍 Processing slides:  47%|█████████████████████████▋                            | 198/417 [1:00:53<1:31:42, 25.13s/it]

199: Processing slide: TCGA-CA-5254_nonMSIH

🔍 Processing slides:  48%|█████████████████████████▊                            | 199/417 [1:01:09<1:21:17, 22.37s/it]

200: Processing slide: TCGA-CA-5255_nonMSIH

🔍 Processing slides:  48%|█████████████████████████▉                            | 200/417 [1:01:32<1:22:20, 22.77s/it]

201: Processing slide: TCGA-CA-5256_nonMSIH

🔍 Processing slides:  48%|██████████████████████████                            | 201/417 [1:01:45<1:11:05, 19.75s/it]

202: Processing slide: TCGA-CA-5796_nonMSIH

🔍 Processing slides:  48%|██████████████████████████▏                           | 202/417 [1:02:20<1:27:25, 24.40s/it]

203: Processing slide: TCGA-CA-5797_nonMSIH

🔍 Processing slides:  49%|██████████████████████████▎                           | 203/417 [1:02:37<1:19:05, 22.18s/it]

204: Processing slide: TCGA-CA-6715_nonMSIH

🔍 Processing slides:  49%|██████████████████████████▍                           | 204/417 [1:03:06<1:25:30, 24.09s/it]

205: Processing slide: TCGA-CA-6716_nonMSIH

🔍 Processing slides:  49%|██████████████████████████▌                           | 205/417 [1:03:31<1:26:33, 24.50s/it]

206: Processing slide: TCGA-CA-6717_nonMSIH

🔍 Processing slides:  49%|██████████████████████████▋                           | 206/417 [1:03:48<1:17:57, 22.17s/it]

207: Processing slide: TCGA-CA-6718_nonMSIH

🔍 Processing slides:  50%|██████████████████████████▊                           | 207/417 [1:04:10<1:17:52, 22.25s/it]

208: Processing slide: TCGA-CA-6719_nonMSIH

🔍 Processing slides:  50%|██████████████████████████▉                           | 208/417 [1:04:30<1:14:37, 21.42s/it]

209: Processing slide: TCGA-CI-6622_nonMSIH

🔍 Processing slides:  50%|████████████████████████████                            | 209/417 [1:04:35<57:23, 16.56s/it]

210: Processing slide: TCGA-CI-6624_nonMSIH

🔍 Processing slides:  50%|████████████████████████████▏                           | 210/417 [1:04:46<50:42, 14.70s/it]

211: Processing slide: TCGA-CK-4947_nonMSIH

🔍 Processing slides:  51%|███████████████████████████▎                          | 211/417 [1:05:26<1:17:25, 22.55s/it]

212: Processing slide: TCGA-CK-4948_nonMSIH

🔍 Processing slides:  51%|███████████████████████████▍                          | 212/417 [1:06:06<1:34:49, 27.75s/it]

213: Processing slide: TCGA-CK-4950_nonMSIH

🔍 Processing slides:  51%|███████████████████████████▌                          | 213/417 [1:06:54<1:54:21, 33.63s/it]

214: Processing slide: TCGA-CK-4951_MSIH

🔍 Processing slides:  51%|███████████████████████████▋                          | 214/417 [1:07:18<1:44:47, 30.97s/it]

215: Processing slide: TCGA-CK-4952_nonMSIH

🔍 Processing slides:  52%|███████████████████████████▊                          | 215/417 [1:07:46<1:41:02, 30.01s/it]

216: Processing slide: TCGA-CK-5912_nonMSIH

🔍 Processing slides:  52%|███████████████████████████▉                          | 216/417 [1:08:38<2:02:28, 36.56s/it]

217: Processing slide: TCGA-CK-5913_MSIH

🔍 Processing slides:  52%|████████████████████████████                          | 217/417 [1:09:35<2:22:33, 42.77s/it]

218: Processing slide: TCGA-CK-5914_nonMSIH

🔍 Processing slides:  52%|████████████████████████████▏                         | 218/417 [1:10:19<2:22:42, 43.03s/it]

219: Processing slide: TCGA-CK-5915_nonMSIH

🔍 Processing slides:  53%|████████████████████████████▎                         | 219/417 [1:11:29<2:48:19, 51.01s/it]

220: Processing slide: TCGA-CK-5916_MSIH

🔍 Processing slides:  53%|████████████████████████████▍                         | 220/417 [1:12:27<2:54:22, 53.11s/it]

221: Processing slide: TCGA-CK-6746_MSIH

🔍 Processing slides:  53%|████████████████████████████▌                         | 221/417 [1:13:15<2:48:27, 51.57s/it]

222: Processing slide: TCGA-CK-6747_MSIH

🔍 Processing slides:  53%|████████████████████████████▋                         | 222/417 [1:14:18<2:58:51, 55.03s/it]

223: Processing slide: TCGA-CK-6748_nonMSIH

🔍 Processing slides:  53%|████████████████████████████▉                         | 223/417 [1:15:18<3:02:50, 56.55s/it]

224: Processing slide: TCGA-CK-6751_nonMSIH

🔍 Processing slides:  54%|█████████████████████████████                         | 224/417 [1:15:52<2:40:25, 49.87s/it]

225: Processing slide: TCGA-CL-4957_nonMSIH

🔍 Processing slides:  54%|█████████████████████████████▏                        | 225/417 [1:16:31<2:29:32, 46.73s/it]

226: Processing slide: TCGA-CL-5917_nonMSIH

🔍 Processing slides:  54%|█████████████████████████████▎                        | 226/417 [1:17:01<2:12:16, 41.55s/it]

227: Processing slide: TCGA-CL-5918_nonMSIH

🔍 Processing slides:  54%|█████████████████████████████▍                        | 227/417 [1:17:35<2:04:15, 39.24s/it]

228: Processing slide: TCGA-CM-4743_MSIH

🔍 Processing slides:  55%|█████████████████████████████▌                        | 228/417 [1:18:26<2:14:37, 42.74s/it]

229: Processing slide: TCGA-CM-4744_nonMSIH

🔍 Processing slides:  55%|█████████████████████████████▋                        | 229/417 [1:19:20<2:24:58, 46.27s/it]

230: Processing slide: TCGA-CM-4746_MSIH

🔍 Processing slides:  55%|█████████████████████████████▊                        | 230/417 [1:20:15<2:31:50, 48.72s/it]

231: Processing slide: TCGA-CM-4747_nonMSIH

🔍 Processing slides:  55%|█████████████████████████████▉                        | 231/417 [1:20:54<2:22:05, 45.84s/it]

232: Processing slide: TCGA-CM-4750_nonMSIH

🔍 Processing slides:  56%|██████████████████████████████                        | 232/417 [1:21:40<2:21:56, 46.04s/it]

233: Processing slide: TCGA-CM-4751_nonMSIH

🔍 Processing slides:  56%|██████████████████████████████▏                       | 233/417 [1:22:07<2:03:42, 40.34s/it]

234: Processing slide: TCGA-CM-4752_nonMSIH

🔍 Processing slides:  56%|██████████████████████████████▎                       | 234/417 [1:22:32<1:48:21, 35.53s/it]

235: Processing slide: TCGA-CM-5341_nonMSIH

🔍 Processing slides:  56%|██████████████████████████████▍                       | 235/417 [1:22:55<1:36:26, 31.79s/it]

236: Processing slide: TCGA-CM-5344_nonMSIH

🔍 Processing slides:  57%|██████████████████████████████▌                       | 236/417 [1:23:30<1:39:18, 32.92s/it]

237: Processing slide: TCGA-CM-5348_nonMSIH

🔍 Processing slides:  57%|██████████████████████████████▋                       | 237/417 [1:24:03<1:38:20, 32.78s/it]

238: Processing slide: TCGA-CM-5349_nonMSIH

🔍 Processing slides:  57%|██████████████████████████████▊                       | 238/417 [1:24:47<1:48:12, 36.27s/it]

239: Processing slide: TCGA-CM-5860_nonMSIH

🔍 Processing slides:  57%|██████████████████████████████▉                       | 239/417 [1:25:20<1:44:56, 35.37s/it]

240: Processing slide: TCGA-CM-5861_MSIH

🔍 Processing slides:  58%|███████████████████████████████                       | 240/417 [1:25:45<1:34:32, 32.05s/it]

241: Processing slide: TCGA-CM-5862_nonMSIH

🔍 Processing slides:  58%|███████████████████████████████▏                      | 241/417 [1:26:24<1:40:22, 34.22s/it]

242: Processing slide: TCGA-CM-5863_nonMSIH

🔍 Processing slides:  58%|███████████████████████████████▎                      | 242/417 [1:26:59<1:40:37, 34.50s/it]

243: Processing slide: TCGA-CM-5864_nonMSIH

🔍 Processing slides:  58%|███████████████████████████████▍                      | 243/417 [1:27:37<1:42:57, 35.50s/it]

244: Processing slide: TCGA-CM-5868_nonMSIH

🔍 Processing slides:  59%|███████████████████████████████▌                      | 244/417 [1:28:24<1:52:46, 39.11s/it]

245: Processing slide: TCGA-CM-6161_nonMSIH

🔍 Processing slides:  59%|███████████████████████████████▋                      | 245/417 [1:29:05<1:53:17, 39.52s/it]

246: Processing slide: TCGA-CM-6162_MSIH

🔍 Processing slides:  59%|███████████████████████████████▊                      | 246/417 [1:29:32<1:42:06, 35.83s/it]

247: Processing slide: TCGA-CM-6163_nonMSIH

🔍 Processing slides:  59%|███████████████████████████████▉                      | 247/417 [1:30:05<1:39:20, 35.06s/it]

248: Processing slide: TCGA-CM-6164_nonMSIH

🔍 Processing slides:  59%|████████████████████████████████                      | 248/417 [1:30:31<1:31:04, 32.33s/it]

249: Processing slide: TCGA-CM-6165_nonMSIH

🔍 Processing slides:  60%|████████████████████████████████▏                     | 249/417 [1:31:08<1:33:48, 33.50s/it]

250: Processing slide: TCGA-CM-6166_nonMSIH

🔍 Processing slides:  60%|████████████████████████████████▎                     | 250/417 [1:31:35<1:28:04, 31.64s/it]

251: Processing slide: TCGA-CM-6167_nonMSIH

🔍 Processing slides:  60%|████████████████████████████████▌                     | 251/417 [1:32:08<1:28:44, 32.08s/it]

252: Processing slide: TCGA-CM-6168_nonMSIH

🔍 Processing slides:  60%|████████████████████████████████▋                     | 252/417 [1:32:47<1:34:10, 34.24s/it]

253: Processing slide: TCGA-CM-6169_nonMSIH

🔍 Processing slides:  61%|████████████████████████████████▊                     | 253/417 [1:33:20<1:32:05, 33.69s/it]

254: Processing slide: TCGA-CM-6170_nonMSIH

🔍 Processing slides:  61%|████████████████████████████████▉                     | 254/417 [1:33:35<1:16:51, 28.29s/it]

255: Processing slide: TCGA-CM-6171_MSIH

🔍 Processing slides:  61%|█████████████████████████████████                     | 255/417 [1:34:12<1:23:06, 30.78s/it]

256: Processing slide: TCGA-CM-6172_nonMSIH

🔍 Processing slides:  61%|█████████████████████████████████▏                    | 256/417 [1:34:36<1:17:12, 28.77s/it]

257: Processing slide: TCGA-CM-6674_MSIH

🔍 Processing slides:  62%|█████████████████████████████████▎                    | 257/417 [1:35:23<1:31:03, 34.15s/it]

258: Processing slide: TCGA-CM-6675_nonMSIH

🔍 Processing slides:  62%|█████████████████████████████████▍                    | 258/417 [1:36:13<1:43:06, 38.91s/it]

259: Processing slide: TCGA-CM-6676_nonMSIH

🔍 Processing slides:  62%|█████████████████████████████████▌                    | 259/417 [1:36:39<1:32:18, 35.05s/it]

260: Processing slide: TCGA-CM-6677_nonMSIH

🔍 Processing slides:  62%|█████████████████████████████████▋                    | 260/417 [1:37:23<1:38:32, 37.66s/it]

261: Processing slide: TCGA-CM-6678_nonMSIH

🔍 Processing slides:  63%|█████████████████████████████████▊                    | 261/417 [1:37:42<1:23:23, 32.07s/it]

262: Processing slide: TCGA-CM-6679_nonMSIH

🔍 Processing slides:  63%|█████████████████████████████████▉                    | 262/417 [1:38:26<1:32:21, 35.75s/it]

263: Processing slide: TCGA-D5-5537_nonMSIH

🔍 Processing slides:  63%|██████████████████████████████████                    | 263/417 [1:38:58<1:29:16, 34.78s/it]

264: Processing slide: TCGA-D5-5538_nonMSIH

🔍 Processing slides:  63%|██████████████████████████████████▏                   | 264/417 [1:39:36<1:30:39, 35.55s/it]

265: Processing slide: TCGA-D5-5539_nonMSIH

🔍 Processing slides:  64%|██████████████████████████████████▎                   | 265/417 [1:39:55<1:17:31, 30.60s/it]

266: Processing slide: TCGA-D5-5540_nonMSIH

🔍 Processing slides:  64%|██████████████████████████████████▍                   | 266/417 [1:40:13<1:07:56, 27.00s/it]

267: Processing slide: TCGA-D5-5541_nonMSIH

🔍 Processing slides:  64%|██████████████████████████████████▌                   | 267/417 [1:40:42<1:08:42, 27.48s/it]

268: Processing slide: TCGA-D5-6529_nonMSIH

🔍 Processing slides:  64%|██████████████████████████████████▋                   | 268/417 [1:41:11<1:09:14, 27.88s/it]

269: Processing slide: TCGA-D5-6530_MSIH

🔍 Processing slides:  65%|██████████████████████████████████▊                   | 269/417 [1:42:03<1:26:49, 35.20s/it]

270: Processing slide: TCGA-D5-6531_nonMSIH

🔍 Processing slides:  65%|██████████████████████████████████▉                   | 270/417 [1:42:34<1:22:57, 33.86s/it]

271: Processing slide: TCGA-D5-6532_nonMSIH

🔍 Processing slides:  65%|███████████████████████████████████                   | 271/417 [1:43:09<1:23:33, 34.34s/it]

272: Processing slide: TCGA-D5-6533_nonMSIH

🔍 Processing slides:  65%|███████████████████████████████████▏                  | 272/417 [1:43:38<1:19:02, 32.71s/it]

273: Processing slide: TCGA-D5-6534_nonMSIH

🔍 Processing slides:  65%|███████████████████████████████████▎                  | 273/417 [1:44:07<1:15:21, 31.40s/it]

274: Processing slide: TCGA-D5-6535_nonMSIH

🔍 Processing slides:  66%|███████████████████████████████████▍                  | 274/417 [1:44:37<1:13:51, 30.99s/it]

275: Processing slide: TCGA-D5-6536_nonMSIH

🔍 Processing slides:  66%|███████████████████████████████████▌                  | 275/417 [1:45:10<1:14:56, 31.66s/it]

276: Processing slide: TCGA-D5-6537_nonMSIH

🔍 Processing slides:  66%|███████████████████████████████████▋                  | 276/417 [1:45:42<1:14:34, 31.74s/it]

277: Processing slide: TCGA-D5-6538_nonMSIH

🔍 Processing slides:  66%|███████████████████████████████████▊                  | 277/417 [1:46:11<1:12:25, 31.04s/it]

278: Processing slide: TCGA-D5-6539_nonMSIH

🔍 Processing slides:  67%|████████████████████████████████████                  | 278/417 [1:46:33<1:05:12, 28.15s/it]

279: Processing slide: TCGA-D5-6540_MSIH

🔍 Processing slides:  67%|████████████████████████████████████▏                 | 279/417 [1:47:00<1:03:58, 27.81s/it]

280: Processing slide: TCGA-D5-6541_nonMSIH

🔍 Processing slides:  67%|████████████████████████████████████▎                 | 280/417 [1:47:35<1:08:31, 30.01s/it]

281: Processing slide: TCGA-D5-6898_nonMSIH

🔍 Processing slides:  67%|█████████████████████████████████████▋                  | 281/417 [1:47:44<54:05, 23.87s/it]

282: Processing slide: TCGA-D5-6920_nonMSIH

🔍 Processing slides:  68%|█████████████████████████████████████▊                  | 282/417 [1:47:50<41:23, 18.40s/it]

283: Processing slide: TCGA-D5-6922_nonMSIH

🔍 Processing slides:  68%|██████████████████████████████████████                  | 283/417 [1:47:59<34:57, 15.65s/it]

284: Processing slide: TCGA-D5-6924_nonMSIH

🔍 Processing slides:  68%|██████████████████████████████████████▏                 | 284/417 [1:48:11<32:00, 14.44s/it]

285: Processing slide: TCGA-D5-6926_nonMSIH

🔍 Processing slides:  68%|██████████████████████████████████████▎                 | 285/417 [1:48:22<29:36, 13.46s/it]

286: Processing slide: TCGA-D5-6927_MSIH

🔍 Processing slides:  69%|██████████████████████████████████████▍                 | 286/417 [1:48:33<27:53, 12.78s/it]

287: Processing slide: TCGA-D5-6928_MSIH

🔍 Processing slides:  69%|██████████████████████████████████████▌                 | 287/417 [1:48:40<23:33, 10.87s/it]

288: Processing slide: TCGA-D5-6929_nonMSIH

🔍 Processing slides:  69%|██████████████████████████████████████▋                 | 288/417 [1:49:33<51:08, 23.78s/it]

289: Processing slide: TCGA-D5-6930_MSIH

🔍 Processing slides:  69%|██████████████████████████████████████▊                 | 289/417 [1:49:41<40:26, 18.95s/it]

290: Processing slide: TCGA-D5-6931_nonMSIH

🔍 Processing slides:  70%|██████████████████████████████████████▉                 | 290/417 [1:49:55<37:00, 17.49s/it]

291: Processing slide: TCGA-D5-6932_nonMSIH

🔍 Processing slides:  70%|███████████████████████████████████████                 | 291/417 [1:50:06<32:46, 15.61s/it]

292: Processing slide: TCGA-D5-7000_nonMSIH

🔍 Processing slides:  70%|███████████████████████████████████████▏                | 292/417 [1:50:14<27:46, 13.33s/it]

293: Processing slide: TCGA-DC-4745_nonMSIH

🔍 Processing slides:  70%|███████████████████████████████████████▎                | 293/417 [1:50:40<35:05, 16.98s/it]

294: Processing slide: TCGA-DC-4749_nonMSIH

🔍 Processing slides:  71%|███████████████████████████████████████▍                | 294/417 [1:51:05<39:42, 19.37s/it]

295: Processing slide: TCGA-DC-5337_nonMSIH

🔍 Processing slides:  71%|███████████████████████████████████████▌                | 295/417 [1:51:22<38:02, 18.71s/it]

296: Processing slide: TCGA-DC-5869_nonMSIH

🔍 Processing slides:  71%|███████████████████████████████████████▊                | 296/417 [1:52:04<51:45, 25.67s/it]

297: Processing slide: TCGA-DC-6154_MSIH

🔍 Processing slides:  71%|███████████████████████████████████████▉                | 297/417 [1:52:23<47:17, 23.64s/it]

298: Processing slide: TCGA-DC-6155_nonMSIH

🔍 Processing slides:  71%|████████████████████████████████████████                | 298/417 [1:53:08<59:48, 30.16s/it]

299: Processing slide: TCGA-DC-6157_nonMSIH

🔍 Processing slides:  72%|████████████████████████████████████████▏               | 299/417 [1:53:33<56:06, 28.53s/it]

300: Processing slide: TCGA-DC-6158_nonMSIH

🔍 Processing slides:  72%|████████████████████████████████████████▎               | 300/417 [1:53:52<50:19, 25.81s/it]

301: Processing slide: TCGA-DC-6160_nonMSIH

🔍 Processing slides:  72%|████████████████████████████████████████▍               | 301/417 [1:54:33<58:31, 30.27s/it]

302: Processing slide: TCGA-DC-6681_nonMSIH

🔍 Processing slides:  72%|███████████████████████████████████████               | 302/417 [1:55:22<1:08:30, 35.75s/it]

303: Processing slide: TCGA-DC-6682_nonMSIH

🔍 Processing slides:  73%|███████████████████████████████████████▏              | 303/417 [1:55:44<1:00:01, 31.59s/it]

304: Processing slide: TCGA-DC-6683_nonMSIH

🔍 Processing slides:  73%|███████████████████████████████████████▎              | 304/417 [1:56:24<1:04:14, 34.11s/it]

305: Processing slide: TCGA-DM-A0X9_nonMSIH

🔍 Processing slides:  73%|███████████████████████████████████████▍              | 305/417 [1:57:02<1:06:03, 35.38s/it]

306: Processing slide: TCGA-DM-A0XD_nonMSIH

🔍 Processing slides:  73%|█████████████████████████████████████████               | 306/417 [1:57:09<49:55, 26.99s/it]

307: Processing slide: TCGA-DM-A0XF_nonMSIH

🔍 Processing slides:  74%|█████████████████████████████████████████▏              | 307/417 [1:57:41<51:55, 28.32s/it]

308: Processing slide: TCGA-DM-A1D0_nonMSIH

🔍 Processing slides:  74%|█████████████████████████████████████████▎              | 308/417 [1:58:15<54:52, 30.21s/it]

309: Processing slide: TCGA-DM-A1D4_nonMSIH

🔍 Processing slides:  74%|█████████████████████████████████████████▍              | 309/417 [1:58:40<51:24, 28.56s/it]

310: Processing slide: TCGA-DM-A1D6_nonMSIH

🔍 Processing slides:  74%|█████████████████████████████████████████▋              | 310/417 [1:59:04<48:18, 27.09s/it]

311: Processing slide: TCGA-DM-A1D7_nonMSIH

🔍 Processing slides:  75%|█████████████████████████████████████████▊              | 311/417 [1:59:20<42:12, 23.89s/it]

312: Processing slide: TCGA-DM-A1D8_nonMSIH

🔍 Processing slides:  75%|█████████████████████████████████████████▉              | 312/417 [1:59:35<37:06, 21.21s/it]

313: Processing slide: TCGA-DM-A1D9_nonMSIH

🔍 Processing slides:  75%|██████████████████████████████████████████              | 313/417 [2:00:10<43:44, 25.23s/it]

314: Processing slide: TCGA-DM-A1DA_nonMSIH

🔍 Processing slides:  75%|██████████████████████████████████████████▏             | 314/417 [2:00:45<48:19, 28.15s/it]

315: Processing slide: TCGA-DM-A1DB_nonMSIH

🔍 Processing slides:  76%|██████████████████████████████████████████▎             | 315/417 [2:01:36<59:43, 35.14s/it]

316: Processing slide: TCGA-DM-A1HA_nonMSIH

🔍 Processing slides:  76%|████████████████████████████████████████▉             | 316/417 [2:02:14<1:00:34, 35.99s/it]

317: Processing slide: TCGA-DM-A280_nonMSIH

🔍 Processing slides:  76%|█████████████████████████████████████████             | 317/417 [2:03:11<1:10:32, 42.33s/it]

318: Processing slide: TCGA-DM-A282_nonMSIH

🔍 Processing slides:  76%|█████████████████████████████████████████▏            | 318/417 [2:04:31<1:28:34, 53.68s/it]

319: Processing slide: TCGA-DM-A285_nonMSIH

🔍 Processing slides:  76%|█████████████████████████████████████████▎            | 319/417 [2:05:22<1:26:24, 52.90s/it]

320: Processing slide: TCGA-DM-A288_nonMSIH

🔍 Processing slides:  77%|█████████████████████████████████████████▍            | 320/417 [2:06:27<1:31:09, 56.39s/it]

321: Processing slide: TCGA-DM-A28A_nonMSIH

🔍 Processing slides:  77%|█████████████████████████████████████████▌            | 321/417 [2:07:20<1:28:51, 55.54s/it]

322: Processing slide: TCGA-DM-A28E_nonMSIH

🔍 Processing slides:  77%|█████████████████████████████████████████▋            | 322/417 [2:07:54<1:17:39, 49.05s/it]

323: Processing slide: TCGA-DM-A28F_nonMSIH

🔍 Processing slides:  77%|█████████████████████████████████████████▊            | 323/417 [2:08:13<1:02:19, 39.78s/it]

324: Processing slide: TCGA-DM-A28G_nonMSIH

🔍 Processing slides:  78%|███████████████████████████████████████████▌            | 324/417 [2:08:41<56:28, 36.44s/it]

325: Processing slide: TCGA-DM-A28H_nonMSIH

🔍 Processing slides:  78%|███████████████████████████████████████████▋            | 325/417 [2:09:07<51:05, 33.33s/it]

326: Processing slide: TCGA-DM-A28K_nonMSIH

🔍 Processing slides:  78%|██████████████████████████████████████████▏           | 326/417 [2:10:20<1:08:22, 45.09s/it]

327: Processing slide: TCGA-DM-A28M_nonMSIH

🔍 Processing slides:  78%|██████████████████████████████████████████▎           | 327/417 [2:11:15<1:12:18, 48.20s/it]

328: Processing slide: TCGA-DT-5265_nonMSIH

🔍 Processing slides:  79%|██████████████████████████████████████████▍           | 328/417 [2:11:41<1:01:38, 41.56s/it]

329: Processing slide: TCGA-DY-A0XA_nonMSIH

🔍 Processing slides:  79%|██████████████████████████████████████████▌           | 329/417 [2:12:59<1:16:45, 52.34s/it]

330: Processing slide: TCGA-DY-A1DC_nonMSIH

🔍 Processing slides:  79%|██████████████████████████████████████████▋           | 330/417 [2:13:41<1:11:21, 49.21s/it]

331: Processing slide: TCGA-DY-A1DD_nonMSIH

🔍 Processing slides:  79%|██████████████████████████████████████████▊           | 331/417 [2:14:34<1:12:27, 50.55s/it]

332: Processing slide: TCGA-DY-A1DF_nonMSIH

🔍 Processing slides:  80%|████████████████████████████████████████████▌           | 332/417 [2:14:55<59:05, 41.71s/it]

333: Processing slide: TCGA-DY-A1DG_nonMSIH

🔍 Processing slides:  80%|████████████████████████████████████████████▋           | 333/417 [2:15:36<58:05, 41.50s/it]

334: Processing slide: TCGA-EF-5830_nonMSIH

🔍 Processing slides:  80%|████████████████████████████████████████████▊           | 334/417 [2:16:01<50:14, 36.32s/it]

335: Processing slide: TCGA-EI-6506_nonMSIH

🔍 Processing slides:  80%|████████████████████████████████████████████▉           | 335/417 [2:16:18<41:49, 30.60s/it]

336: Processing slide: TCGA-EI-6507_MSIH

🔍 Processing slides:  81%|█████████████████████████████████████████████           | 336/417 [2:16:44<39:37, 29.35s/it]

337: Processing slide: TCGA-EI-6508_nonMSIH

🔍 Processing slides:  81%|█████████████████████████████████████████████▎          | 337/417 [2:17:06<36:13, 27.17s/it]

338: Processing slide: TCGA-EI-6509_nonMSIH

🔍 Processing slides:  81%|█████████████████████████████████████████████▍          | 338/417 [2:17:21<30:35, 23.24s/it]

339: Processing slide: TCGA-EI-6510_nonMSIH

🔍 Processing slides:  81%|█████████████████████████████████████████████▌          | 339/417 [2:17:47<31:18, 24.09s/it]

340: Processing slide: TCGA-EI-6511_nonMSIH

🔍 Processing slides:  82%|█████████████████████████████████████████████▋          | 340/417 [2:18:44<43:45, 34.10s/it]

341: Processing slide: TCGA-EI-6512_nonMSIH

🔍 Processing slides:  82%|█████████████████████████████████████████████▊          | 341/417 [2:19:34<49:05, 38.76s/it]

342: Processing slide: TCGA-EI-6513_nonMSIH

🔍 Processing slides:  82%|█████████████████████████████████████████████▉          | 342/417 [2:20:29<54:32, 43.63s/it]

343: Processing slide: TCGA-EI-6514_nonMSIH

🔍 Processing slides:  82%|██████████████████████████████████████████████          | 343/417 [2:21:02<49:48, 40.38s/it]

344: Processing slide: TCGA-EI-6881_nonMSIH

🔍 Processing slides:  82%|██████████████████████████████████████████████▏         | 344/417 [2:21:07<36:24, 29.93s/it]

345: Processing slide: TCGA-EI-6882_MSIH

🔍 Processing slides:  83%|██████████████████████████████████████████████▎         | 345/417 [2:21:23<30:44, 25.62s/it]

346: Processing slide: TCGA-EI-6883_nonMSIH

🔍 Processing slides:  83%|██████████████████████████████████████████████▍         | 346/417 [2:21:47<29:54, 25.27s/it]

347: Processing slide: TCGA-EI-6884_nonMSIH

🔍 Processing slides:  83%|██████████████████████████████████████████████▌         | 347/417 [2:21:56<23:49, 20.43s/it]

348: Processing slide: TCGA-EI-6885_nonMSIH

🔍 Processing slides:  83%|██████████████████████████████████████████████▋         | 348/417 [2:22:07<20:06, 17.48s/it]

349: Processing slide: TCGA-EI-6917_nonMSIH

🔍 Processing slides:  84%|██████████████████████████████████████████████▊         | 349/417 [2:22:16<17:09, 15.14s/it]

350: Processing slide: TCGA-EI-7002_nonMSIH

🔍 Processing slides:  84%|███████████████████████████████████████████████         | 350/417 [2:22:27<15:26, 13.83s/it]

351: Processing slide: TCGA-EI-7004_nonMSIH

🔍 Processing slides:  84%|███████████████████████████████████████████████▏        | 351/417 [2:22:35<13:04, 11.88s/it]

352: Processing slide: TCGA-F4-6459_nonMSIH

🔍 Processing slides:  84%|███████████████████████████████████████████████▎        | 352/417 [2:23:46<32:12, 29.73s/it]

353: Processing slide: TCGA-F4-6460_nonMSIH

🔍 Processing slides:  85%|███████████████████████████████████████████████▍        | 353/417 [2:24:38<38:49, 36.40s/it]

354: Processing slide: TCGA-F4-6461_nonMSIH

🔍 Processing slides:  85%|███████████████████████████████████████████████▌        | 354/417 [2:25:33<43:56, 41.85s/it]

355: Processing slide: TCGA-F4-6463_nonMSIH

🔍 Processing slides:  85%|███████████████████████████████████████████████▋        | 355/417 [2:25:41<33:01, 31.96s/it]

356: Processing slide: TCGA-F4-6569_nonMSIH

🔍 Processing slides:  85%|███████████████████████████████████████████████▊        | 356/417 [2:25:57<27:36, 27.15s/it]

357: Processing slide: TCGA-F4-6570_MSIH

🔍 Processing slides:  86%|███████████████████████████████████████████████▉        | 357/417 [2:26:17<24:54, 24.91s/it]

358: Processing slide: TCGA-F4-6703_MSIH

🔍 Processing slides:  86%|████████████████████████████████████████████████        | 358/417 [2:26:36<22:36, 23.00s/it]

359: Processing slide: TCGA-F4-6704_nonMSIH

🔍 Processing slides:  86%|████████████████████████████████████████████████▏       | 359/417 [2:26:48<19:02, 19.70s/it]

360: Processing slide: TCGA-F4-6805_nonMSIH

🔍 Processing slides:  86%|████████████████████████████████████████████████▎       | 360/417 [2:27:06<18:22, 19.34s/it]

361: Processing slide: TCGA-F4-6806_nonMSIH

🔍 Processing slides:  87%|████████████████████████████████████████████████▍       | 361/417 [2:27:36<20:54, 22.40s/it]

362: Processing slide: TCGA-F4-6807_nonMSIH

🔍 Processing slides:  87%|████████████████████████████████████████████████▌       | 362/417 [2:28:12<24:20, 26.56s/it]

363: Processing slide: TCGA-F4-6808_nonMSIH

🔍 Processing slides:  87%|████████████████████████████████████████████████▋       | 363/417 [2:28:46<26:02, 28.93s/it]

364: Processing slide: TCGA-F4-6809_nonMSIH

🔍 Processing slides:  87%|████████████████████████████████████████████████▉       | 364/417 [2:29:16<25:46, 29.17s/it]

365: Processing slide: TCGA-F4-6854_nonMSIH

🔍 Processing slides:  88%|█████████████████████████████████████████████████       | 365/417 [2:29:29<21:10, 24.43s/it]

366: Processing slide: TCGA-F4-6855_nonMSIH

🔍 Processing slides:  88%|█████████████████████████████████████████████████▏      | 366/417 [2:29:36<16:18, 19.18s/it]

367: Processing slide: TCGA-F4-6856_MSIH

🔍 Processing slides:  88%|█████████████████████████████████████████████████▎      | 367/417 [2:30:28<24:11, 29.03s/it]

368: Processing slide: TCGA-F5-6464_nonMSIH

🔍 Processing slides:  88%|█████████████████████████████████████████████████▍      | 368/417 [2:31:23<30:06, 36.86s/it]

369: Processing slide: TCGA-F5-6465_nonMSIH

🔍 Processing slides:  88%|█████████████████████████████████████████████████▌      | 369/417 [2:32:00<29:30, 36.89s/it]

370: Processing slide: TCGA-F5-6571_nonMSIH

🔍 Processing slides:  89%|█████████████████████████████████████████████████▋      | 370/417 [2:32:50<31:48, 40.61s/it]

371: Processing slide: TCGA-F5-6702_nonMSIH

🔍 Processing slides:  89%|█████████████████████████████████████████████████▊      | 371/417 [2:33:18<28:24, 37.05s/it]

372: Processing slide: TCGA-F5-6811_nonMSIH

🔍 Processing slides:  89%|█████████████████████████████████████████████████▉      | 372/417 [2:33:26<21:09, 28.22s/it]

373: Processing slide: TCGA-F5-6814_nonMSIH

🔍 Processing slides:  89%|██████████████████████████████████████████████████      | 373/417 [2:33:59<21:39, 29.52s/it]

374: Processing slide: TCGA-F5-6863_nonMSIH

🔍 Processing slides:  90%|██████████████████████████████████████████████████▏     | 374/417 [2:34:21<19:34, 27.31s/it]

375: Processing slide: TCGA-F5-6864_nonMSIH

🔍 Processing slides:  90%|██████████████████████████████████████████████████▎     | 375/417 [2:34:35<16:15, 23.23s/it]

376: Processing slide: TCGA-G4-6293_nonMSIH

🔍 Processing slides:  90%|██████████████████████████████████████████████████▍     | 376/417 [2:34:57<15:41, 22.97s/it]

377: Processing slide: TCGA-G4-6294_nonMSIH

🔍 Processing slides:  90%|██████████████████████████████████████████████████▋     | 377/417 [2:35:31<17:33, 26.34s/it]

378: Processing slide: TCGA-G4-6295_nonMSIH

🔍 Processing slides:  91%|██████████████████████████████████████████████████▊     | 378/417 [2:35:55<16:33, 25.47s/it]

379: Processing slide: TCGA-G4-6297_nonMSIH

🔍 Processing slides:  91%|██████████████████████████████████████████████████▉     | 379/417 [2:36:26<17:19, 27.35s/it]

380: Processing slide: TCGA-G4-6298_nonMSIH

🔍 Processing slides:  91%|███████████████████████████████████████████████████     | 380/417 [2:37:03<18:39, 30.24s/it]

381: Processing slide: TCGA-G4-6299_nonMSIH

🔍 Processing slides:  91%|███████████████████████████████████████████████████▏    | 381/417 [2:37:31<17:37, 29.37s/it]

382: Processing slide: TCGA-G4-6302_MSIH

🔍 Processing slides:  92%|███████████████████████████████████████████████████▎    | 382/417 [2:37:49<15:14, 26.12s/it]

383: Processing slide: TCGA-G4-6303_nonMSIH

🔍 Processing slides:  92%|███████████████████████████████████████████████████▍    | 383/417 [2:38:05<13:03, 23.03s/it]

384: Processing slide: TCGA-G4-6304_MSIH

🔍 Processing slides:  92%|███████████████████████████████████████████████████▌    | 384/417 [2:38:43<15:09, 27.55s/it]

385: Processing slide: TCGA-G4-6306_nonMSIH

🔍 Processing slides:  92%|███████████████████████████████████████████████████▋    | 385/417 [2:39:05<13:45, 25.79s/it]

386: Processing slide: TCGA-G4-6307_nonMSIH

🔍 Processing slides:  93%|███████████████████████████████████████████████████▊    | 386/417 [2:39:28<12:59, 25.14s/it]

387: Processing slide: TCGA-G4-6309_MSIH

🔍 Processing slides:  93%|███████████████████████████████████████████████████▉    | 387/417 [2:39:52<12:19, 24.65s/it]

388: Processing slide: TCGA-G4-6311_nonMSIH

🔍 Processing slides:  93%|████████████████████████████████████████████████████    | 388/417 [2:40:13<11:23, 23.58s/it]

389: Processing slide: TCGA-G4-6315_nonMSIH

🔍 Processing slides:  93%|████████████████████████████████████████████████████▏   | 389/417 [2:40:40<11:32, 24.74s/it]

390: Processing slide: TCGA-G4-6317_nonMSIH

🔍 Processing slides:  94%|████████████████████████████████████████████████████▎   | 390/417 [2:41:03<10:46, 23.96s/it]

391: Processing slide: TCGA-G4-6320_MSIH

🔍 Processing slides:  94%|████████████████████████████████████████████████████▌   | 391/417 [2:41:21<09:37, 22.22s/it]

392: Processing slide: TCGA-G4-6321_nonMSIH

🔍 Processing slides:  94%|████████████████████████████████████████████████████▋   | 392/417 [2:41:38<08:36, 20.66s/it]

393: Processing slide: TCGA-G4-6322_nonMSIH

🔍 Processing slides:  94%|████████████████████████████████████████████████████▊   | 393/417 [2:42:08<09:23, 23.49s/it]

394: Processing slide: TCGA-G4-6323_nonMSIH

🔍 Processing slides:  94%|████████████████████████████████████████████████████▉   | 394/417 [2:42:25<08:15, 21.52s/it]

395: Processing slide: TCGA-G4-6586_MSIH

🔍 Processing slides:  95%|█████████████████████████████████████████████████████   | 395/417 [2:42:49<08:08, 22.21s/it]

396: Processing slide: TCGA-G4-6588_MSIH

🔍 Processing slides:  95%|█████████████████████████████████████████████████████▏  | 396/417 [2:43:22<08:57, 25.59s/it]

397: Processing slide: TCGA-G4-6626_nonMSIH

🔍 Processing slides:  95%|█████████████████████████████████████████████████████▎  | 397/417 [2:44:00<09:46, 29.34s/it]

398: Processing slide: TCGA-G4-6627_nonMSIH

🔍 Processing slides:  95%|█████████████████████████████████████████████████████▍  | 398/417 [2:44:59<12:05, 38.18s/it]

399: Processing slide: TCGA-G4-6628_MSIH

🔍 Processing slides:  96%|█████████████████████████████████████████████████████▌  | 399/417 [2:45:48<12:27, 41.53s/it]

400: Processing slide: TCGA-G5-6641_nonMSIH

🔍 Processing slides:  96%|█████████████████████████████████████████████████████▋  | 400/417 [2:46:11<10:08, 35.79s/it]

401: Processing slide: TCGA-NH-A50T_nonMSIH

🔍 Processing slides:  96%|█████████████████████████████████████████████████████▊  | 401/417 [2:46:57<10:25, 39.09s/it]

402: Processing slide: TCGA-NH-A50U_nonMSIH

🔍 Processing slides:  96%|█████████████████████████████████████████████████████▉  | 402/417 [2:47:33<09:28, 37.90s/it]

403: Processing slide: TCGA-NH-A50V_nonMSIH

🔍 Processing slides:  97%|██████████████████████████████████████████████████████  | 403/417 [2:48:08<08:38, 37.04s/it]

404: Processing slide: TCGA-NH-A5IV_MSIH

🔍 Processing slides:  97%|██████████████████████████████████████████████████████▎ | 404/417 [2:48:55<08:40, 40.02s/it]

405: Processing slide: TCGA-NH-A6GA_nonMSIH

🔍 Processing slides:  97%|██████████████████████████████████████████████████████▍ | 405/417 [2:49:22<07:14, 36.25s/it]

406: Processing slide: TCGA-NH-A6GB_nonMSIH

🔍 Processing slides:  97%|██████████████████████████████████████████████████████▌ | 406/417 [2:50:09<07:14, 39.47s/it]

407: Processing slide: TCGA-NH-A6GC_nonMSIH

🔍 Processing slides:  98%|██████████████████████████████████████████████████████▋ | 407/417 [2:50:45<06:24, 38.42s/it]

408: Processing slide: TCGA-NH-A8F8_nonMSIH

🔍 Processing slides:  98%|██████████████████████████████████████████████████████▊ | 408/417 [2:51:19<05:33, 37.11s/it]

409: Processing slide: TCGA-QG-A5YV_nonMSIH

🔍 Processing slides:  98%|██████████████████████████████████████████████████████▉ | 409/417 [2:52:01<05:07, 38.43s/it]

410: Processing slide: TCGA-QG-A5YW_nonMSIH

🔍 Processing slides:  98%|███████████████████████████████████████████████████████ | 410/417 [2:52:28<04:05, 35.09s/it]

411: Processing slide: TCGA-QG-A5YX_nonMSIH

🔍 Processing slides:  99%|███████████████████████████████████████████████████████▏| 411/417 [2:53:00<03:25, 34.24s/it]

412: Processing slide: TCGA-QG-A5Z1_nonMSIH

🔍 Processing slides:  99%|███████████████████████████████████████████████████████▎| 412/417 [2:53:30<02:45, 33.02s/it]

413: Processing slide: TCGA-QG-A5Z2_MSIH

🔍 Processing slides:  99%|███████████████████████████████████████████████████████▍| 413/417 [2:54:07<02:16, 34.23s/it]

414: Processing slide: TCGA-QL-A97D_nonMSIH

🔍 Processing slides:  99%|███████████████████████████████████████████████████████▌| 414/417 [2:54:36<01:37, 32.61s/it]

415: Processing slide: TCGA-SS-A7HO_nonMSIH

🔍 Processing slides: 100%|███████████████████████████████████████████████████████▋| 415/417 [2:55:19<01:11, 35.81s/it]

416: Processing slide: TCGA-T9-A92H_nonMSIH

🔍 Processing slides: 100%|███████████████████████████████████████████████████████▊| 416/417 [2:56:00<00:37, 37.13s/it]

417: Processing slide: TCGA-WS-AB45_MSIH

🔍 Processing slides: 100%|████████████████████████████████████████████████████████| 417/417 [2:56:40<00:00, 25.42s/it]

## Post Processing

In [12]:
update_df = pd.DataFrame(updates, columns=['updated_patchName', 'tissue_label'])
update_df

                                         updated_patchName  tissue_label
0        TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...             0
1        TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...             0
2        TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...             0
3        TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...             0
4        TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...             0
...                                                    ...           ...
6889660    TCGA-WS-AB45_MSIH_x9664_y37888_patch00199_1.png             4
6889661    TCGA-WS-AB45_MSIH_x9664_y37888_patch00199_2.png             4
6889662    TCGA-WS-AB45_MSIH_x9664_y37888_patch00199_3.png             4
6889663    TCGA-WS-AB45_MSIH_x9664_y37888_patch00199_4.png             2
6889664    TCGA-WS-AB45_MSIH_x9664_y37888_patch00199_5.png             4

[6889665 rows x 2 columns]

In [13]:
len(set(update_df["updated_patchName"]))

6889665

In [14]:
# update_df = pd.DataFrame(updates, columns=['updated_patchName', 'tissue_label'])
df_expanded.set_index('updated_patchName', inplace=True)
df_expanded.update(update_df.set_index('updated_patchName'))
df_expanded.reset_index(inplace=True)

In [15]:
df_expanded = df_expanded.merge(update_df, on='updated_patchName', how='inner')

# Save the updated CSV if needed
df_expanded.to_csv("conch_labeled_df.csv", index=False)

In [16]:
df_expanded

,updated_patchName,patch_location,patch_name,patch_number,patch_x,patch_y,avg_R,avg_G,avg_B,std_R,std_G,std_B,label,tissue_label
0,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.png,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,0
1,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.png,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,0
2,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.png,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,0
3,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.png,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,0
4,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.png,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6889660,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_1.png,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.png,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,7
6889661,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_2.png,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.png,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,1
6889662,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_3.png,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.png,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,3
6889663,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_4.png,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.png,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,1
6889664,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_5.png,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.png,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,1

## Slide Aggregation

In [17]:
non_white_df= df_expanded.copy()

In [18]:
# non_white_df['patch_name'] = non_white_df['patch_name'].str.replace('.png', '.pt', regex=False)
import re
non_white_df['patch_name'] = non_white_df['patch_name'].str.replace('.png', '.pt', regex=False)
# non_white_df['patch_name'] = non_white_df['patch_name'].str.replace(r'_patch\d{5}', '', regex=True)

In [19]:
non_white_df

,updated_patchName,patch_location,patch_name,patch_number,patch_x,patch_y,avg_R,avg_G,avg_B,std_R,std_G,std_B,label,tissue_label
0,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.pt,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,0
1,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.pt,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,0
2,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.pt,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,0
3,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.pt,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,0
4,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159_...,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-3L-AA1B_nonMSIH_x10288_y12512_patch00159.pt,159,10288,12512,237.72,225.94,230.83,15.18,32.27,25.42,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6889660,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_1.png,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.pt,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,7
6889661,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_2.png,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.pt,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,1
6889662,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_3.png,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.pt,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,3
6889663,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_4.png,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.pt,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,1
6889664,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531_5.png,D:/Aamir Gulzar/KSA_project2/dataset/patch_dat...,TCGA-WS-AB45_MSIH_x54208_y25088_patch04531.pt,4531,54208,25088,231.00,221.49,227.52,26.98,38.33,28.96,0,1

## Slide aggregation pipeline

In [20]:
import os
import torch
import numpy as np
from tqdm import tqdm
import pandas as pd

# ---------------- CONFIG ----------------
root_dir = r"D:\Aamir Gulzar\KSA_project2\dataset\Features\Conch_v1_5_fivecrop_Updated"
saving_path = r"D:\Aamir Gulzar\KSA_project2\dataset\slide_aggregation\2-Averaging_FiveCrop\conch_224_fivecrop"
num_classes = 9
# ----------------------------------------

os.makedirs(saving_path, exist_ok=True)

# Load label CSV once. Expect columns 'patch_name' and 'tissue_label'.
# We'll create two maps:
#   1) split_name_map: exact filename without extension -> label  (for cases non_white has _1.._5)
#   2) base_name_map: base patch name (without _1.._5) -> label (fallback)
non_white_df['patch_name'] = non_white_df['patch_name'].astype(str)

split_name_map = {}  # exact match
base_name_map = {}   # fallback by base (without last _idx)
for pn, label in zip(non_white_df['patch_name'], non_white_df['tissue_label']):
    name = os.path.splitext(pn)[0]
    split_name_map[name] = label
    # derive base by removing trailing _<num> if present
    parts = name.rsplit('_', 1)
    if len(parts) == 2 and parts[1].isdigit():
        base = parts[0]
    else:
        base = name
    # only set if not set, keep first occurrence
    if base not in base_name_map:
        base_name_map[base] = label

# Process each slide folder
for slide_name in tqdm(os.listdir(root_dir), desc="Slides"):
    slide_path = os.path.join(root_dir, slide_name)
    if not os.path.isdir(slide_path):
        continue

    files = [f for f in os.listdir(slide_path) if f.endswith('.pt')]
    if not files:
        continue

    # We'll collect features and labels in two lists, then convert to numpy arrays
    features_list = []
    labels_list = []

    for fname in files:
        pt_path = os.path.join(slide_path, fname)
        # load to CPU
        try:
            t = torch.load(pt_path, map_location="cpu")
        except Exception as e:
            print(f"ERROR loading {pt_path}: {e}")
            continue

        # normalize tensor to 2D: (num_crops, D)
        if isinstance(t, torch.Tensor):
            t = t.detach().cpu()
            t = t.squeeze()
            if t.ndim == 1:
                crops = t.unsqueeze(0).numpy()  # (1, D)
            elif t.ndim == 2:
                crops = t.numpy()               # (N, D) e.g., (5, 768)
            else:
                # flatten any extra dims into second dim (rare)
                crops = t.view(t.shape[0], -1).numpy()
        else:
            # skip non-tensor objects
            print(f"Skipping (not tensor): {pt_path}")
            continue

        base_name = os.path.splitext(fname)[0]  # original base without extension

        # For each crop of this patch, create split name and determine label (fast, without saving)
        # We avoid any heavy string ops in loops; simple concatenation and map lookups only.
        for idx in range(crops.shape[0]):
            split_name = f"{base_name}_{idx+1}"  # like file_1, file_2, ...
            features_list.append(crops[idx])     # append numpy 1D array
            # label resolution: exact split name -> fallback to base map
            lbl = split_name_map.get(split_name)
            if lbl is None:
                # fallback: try base name (original patch name without _idx)
                # base_candidate: remove trailing _<digit> if any
                parts = base_name.rsplit('_', 1)
                if len(parts) == 2 and parts[1].isdigit():
                    base_candidate = parts[0]
                else:
                    base_candidate = base_name
                lbl = base_name_map.get(base_candidate, np.nan)
            labels_list.append(lbl)

    # If nothing collected skip
    if not features_list:
        continue

    # Convert lists to arrays
    feats = np.stack(features_list, axis=0).astype(np.float32)  # shape (N, D)
    labels = np.array(labels_list, dtype=np.float32)            # shape (N,)

    # Compute feature dimension
    D = feats.shape[1]

    # Compute group averages per class (0..num_classes-1)
    group_avgs = np.zeros((num_classes, D), dtype=np.float32)

    # Use vectorized grouping: for each label, mask and mean
    # Slight optimization: if labels array contains NaNs, comparisons will be False
    for cls in range(num_classes):
        mask = (labels == cls)
        if mask.any():
            group_avgs[cls] = feats[mask].mean(axis=0)
        else:
            # remains zeros
            pass

    final_tensor = torch.from_numpy(group_avgs)  # shape (num_classes, D)

    # Save the aggregated slide-level tensor
    save_path = os.path.join(saving_path, f"{slide_name}.pt")
    torch.save(final_tensor, save_path)

Slides: 100%|██████████████████████████████████████████████████████████████████████| 417/417 [4:08:01<00:00, 35.69s/it]

In [23]:
import torch

# Path to your .pt file
pt_path = r"D:\Aamir Gulzar\KSA_project2\dataset\slide_aggregation\2-Averaging_FiveCrop\TCGA-AA-3678_nonMSIH.pt"

# Load to CPU to avoid GPU dependency
tensor = torch.load(pt_path, map_location="cpu")

# If it's a tensor
if isinstance(tensor, torch.Tensor):
    print("Shape:", tensor.shape)
    print("Values:\n", tensor)
else:
    print("Loaded object type:", type(tensor))
    print("Value:", tensor)

Shape: torch.Size([9, 768])
Values:
 tensor([[-0.5847, -0.3429, -1.2125,  ...,  2.1690,  0.7562,  0.4149],
        [-0.3209, -0.4401, -0.8908,  ...,  2.2065,  0.4518,  0.4030],
        [-0.4376, -0.6947, -1.2316,  ...,  1.7534,  0.4005,  0.4160],
        ...,
        [-0.4609, -0.2849, -1.4860,  ...,  1.7434,  1.0410,  0.4686],
        [-0.5748, -0.4138, -1.4791,  ...,  1.8163,  0.5344,  0.4690],
        [-0.4650, -0.6612, -1.4538,  ...,  1.6533,  0.6672,  0.4750]])